# -*- coding: utf-8 -*-
"""transfomer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T6qBSaLkZlDYOFgfhq16nFMjzKGW-kks
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
import math
import matplotlib.pyplot as plt

class PositionalEncoding(nn.Module):
    """Pozisyonel kodlama modülü - Dizi sırasını modele öğretir."""
    def __init__(self, d_model, max_len=5000):
        super().__init__()
        pe = torch.zeros(max_len, d_model)
        position = torch.arange(0, max_len, dtype=torch.float).unsqueeze(1)
        div_term = torch.exp(torch.arange(0, d_model, 2).float() * (-math.log(10000.0) / d_model))
        pe[:, 0::2] = torch.sin(position * div_term)
        pe[:, 1::2] = torch.cos(position * div_term)
        self.register_buffer("pe", pe.unsqueeze(0))

    def forward(self, x):
        return x + self.pe[:, : x.size(1), :]


class MultiHeadAttention(nn.Module):
    """Çok başlı dikkat mekanizması - Kelimeler arası ilişkileri kurar."""
    def __init__(self, d_model, num_heads):
        super().__init__()
        assert d_model % num_heads == 0, "d_model baş sayısına tam bölünmeli!"
        self.d_model = d_model
        self.num_heads = num_heads
        self.d_k = d_model // num_heads

        self.W_q = nn.Linear(d_model, d_model)
        self.W_k = nn.Linear(d_model, d_model)
        self.W_v = nn.Linear(d_model, d_model)
        self.W_o = nn.Linear(d_model, d_model)

    def split_heads(self, x):
        batch_size, seq_len, _ = x.size()
        return x.view(batch_size, seq_len, self.num_heads, self.d_k).transpose(1, 2)

    def combine_heads(self, x):
        batch_size, _, seq_len, _ = x.size()
        return x.transpose(1, 2).contiguous().view(batch_size, seq_len, self.d_model)

    def forward(self, query, key, value, mask=None):
        Q = self.split_heads(self.W_q(query))
        K = self.split_heads(self.W_k(key))
        V = self.split_heads(self.W_v(value))

        scores = torch.matmul(Q, K.transpose(-2, -1)) / math.sqrt(self.d_k)
        if mask is not None:
            scores = scores.masked_fill(mask == 0, float("-inf"))

        attn = F.softmax(scores, dim=-1)
        context = torch.matmul(attn, V)
        output = self.W_o(self.combine_heads(context))
        return output, attn


class PositionwiseFeedForward(nn.Module):
    """Pozisyon bazlı ileri beslemeli ağ - Özellikleri doğrusal olmayan şekilde işler."""
    def __init__(self, d_model, d_ff, dropout=0.1):
        super().__init__()
        self.linear1 = nn.Linear(d_model, d_ff)
        self.linear2 = nn.Linear(d_ff, d_model)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        return self.linear2(self.dropout(F.gelu(self.linear1(x))))


class EncoderLayer(nn.Module):
    """Tek bir Encoder Katmanı."""
    def __init__(self, d_model, num_heads, d_ff, dropout=0.1):
        super().__init__()
        self.self_attn = MultiHeadAttention(d_model, num_heads)
        self.feed_forward = PositionwiseFeedForward(d_model, d_ff, dropout)
        self.norm1 = nn.LayerNorm(d_model)
        self.norm2 = nn.LayerNorm(d_model)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x, mask=None):
        # Pre-Layer Normalization for self-attention
        _x = self.norm1(x)
        attn_out, _ = self.self_attn(_x, _x, _x, mask)
        x = x + self.dropout(attn_out) # Add residual after attention

        # Pre-Layer Normalization for feed-forward
        _x = self.norm2(x)
        ff_out = self.feed_forward(_x)
        x = x + self.dropout(ff_out) # Add residual after feed-forward
        return x


class DecoderLayer(nn.Module):
    """Tek bir Decoder Katmanı."""
    def __init__(self, d_model, num_heads, d_ff, dropout=0.1):
        super().__init__()
        self.self_attn = MultiHeadAttention(d_model, num_heads)
        self.cross_attn = MultiHeadAttention(d_model, num_heads)
        self.feed_forward = PositionwiseFeedForward(d_model, d_ff, dropout)
        self.norm1 = nn.LayerNorm(d_model)
        self.norm2 = nn.LayerNorm(d_model)
        self.norm3 = nn.LayerNorm(d_model)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x, enc_output, src_mask=None, tgt_mask=None):
        # Pre-Layer Normalization for self-attention
        _x = self.norm1(x)
        attn_out, _ = self.self_attn(_x, _x, _x, tgt_mask)
        x = x + self.dropout(attn_out)

        # Pre-Layer Normalization for cross-attention
        _x = self.norm2(x)
        cross_out, _ = self.cross_attn(_x, enc_output, enc_output, src_mask)
        x = x + self.dropout(cross_out)

        # Pre-Layer Normalization for feed-forward
        _x = self.norm3(x)
        ff_out = self.feed_forward(_x)
        x = x + self.dropout(ff_out)
        return x


class Transformer(nn.Module):
    """Tam Transformer Modeli (Encoder-Decoder)"""
    def __init__(self, src_vocab_size, tgt_vocab_size, d_model=512, num_heads=8,
                 num_layers=6, d_ff=2048, max_len=100, dropout=0.1):
        super().__init__()
        self.encoder_embedding = nn.Embedding(src_vocab_size, d_model)
        self.decoder_embedding = nn.Embedding(tgt_vocab_size, d_model)
        self.positional_encoding = PositionalEncoding(d_model, max_len)

        self.encoder_layers = nn.ModuleList(
            [EncoderLayer(d_model, num_heads, d_ff, dropout) for _ in range(num_layers)]
        )
        self.decoder_layers = nn.ModuleList(
            [DecoderLayer(d_model, num_heads, d_ff, dropout) for _ in range(num_layers)]
        )

        self.fc_out = nn.Linear(d_model, tgt_vocab_size)
        self.dropout = nn.Dropout(dropout)
        self.final_norm = nn.LayerNorm(d_model) # Yeni eklenen final normalizasyon

    def generate_mask(self, src, tgt):
        src_mask = (src != 0).unsqueeze(1).unsqueeze(2)  # (batch, 1, 1, src_len)
        tgt_mask = (tgt != 0).unsqueeze(1).unsqueeze(3)  # (batch, 1, tgt_len, 1)

        seq_len = tgt.size(1)
        nopeak_mask = (1 - torch.triu(torch.ones(1, seq_len, seq_len), diagonal=1)).bool()
        tgt_mask = tgt_mask & nopeak_mask.to(tgt.device)
        return src_mask, tgt_mask

    def encode(self, src, src_mask):
        x = self.dropout(self.positional_encoding(self.encoder_embedding(src)))
        for layer in self.encoder_layers:
            x = layer(x, src_mask)
        return x

    def decode(self, tgt, enc_output, src_mask, tgt_mask):
        x = self.dropout(self.positional_encoding(self.decoder_embedding(tgt)))
        for layer in self.decoder_layers:
            x = layer(x, enc_output, src_mask, tgt_mask)
        return x

    def forward(self, src, tgt):
        src_mask, tgt_mask = self.generate_mask(src, tgt)
        enc_output = self.encode(src, src_mask)
        dec_output = self.decode(tgt, enc_output, src_mask, tgt_mask)
        return self.fc_out(self.final_norm(dec_output)) # Final normalizasyonu uygulandı

VOCAB_SIZE = 30       # Küçük kelime dağarcığı (0-29)
SEQ_LEN = 8           # Üretilecek rastgele sayıların uzunluğu
SOS, EOS, PAD = 1, 2, 0

def make_batch(batch_size=32, seq_len=SEQ_LEN, vocab_size=VOCAB_SIZE):
    """Modelin kopyalamayı öğrenmesi için yapay veri üretir."""
    # 3 ile 29 arasında rastgele sayılar üret (0, 1, 2 özel tokenlar için ayrıldı)
    seq = torch.randint(3, vocab_size, (batch_size, seq_len))
    src = seq

    # Hedef dizinin başına SOS, sonuna EOS ekle
    tgt_full = torch.cat(
        [torch.full((batch_size, 1), SOS), seq, torch.full((batch_size, 1), EOS)], dim=1
    )
    tgt_input = tgt_full[:, :-1]   # Decoder girdisi (SOS ile başlar, EOS içermez)
    tgt_output = tgt_full[:, 1:]   # Gerçek etiket (SOS içermez, EOS ile biter)
    return src, tgt_input, tgt_output

toy_model = Transformer(
    src_vocab_size=VOCAB_SIZE,
    tgt_vocab_size=VOCAB_SIZE,
    d_model=64,
    num_heads=4,
    num_layers=2,
    d_ff=128,
    max_len=20
)

# Parametre sayısını kontrol edelim
total_params = sum(p.numel() for p in toy_model.parameters())
print(f"Model başarıyla kuruldu. Toplam parametre sayısı: {total_params:,}\n")

optimizer = torch.optim.Adam(toy_model.parameters(), lr=1e-3)
criterion = nn.CrossEntropyLoss(ignore_index=PAD) # Dolgu tokenlarını hesaplamaya katma

print("Eğitim başlatılıyor...")
toy_model.train()
losses = []

for epoch in range(300):
    src, tgt_input, tgt_output = make_batch(batch_size=32)

    optimizer.zero_grad()
    logits = toy_model(src, tgt_input)

    # Logitleri ve Hedefleri CrossEntropyLoss için boyutlandırıyoruz
    loss = criterion(logits.reshape(-1, VOCAB_SIZE), tgt_output.reshape(-1))
    loss.backward()
    optimizer.step()
    losses.append(loss.item())

    if epoch % 50 == 0 or epoch == 299:
        print(f"Epoch {epoch:3d} | Kayıp (loss): {loss.item():.4f}")

print("\nEğitim tamamlandı!\n")

plt.figure(figsize=(10, 6))
plt.plot(losses)
plt.title("Eğitim Kaybı (Training Loss)")
plt.xlabel("Epoch")
plt.ylabel("Kayıp (Loss)")
plt.grid(True)
plt.show()

@torch.no_grad()
def greedy_decode(model, src, max_len=SEQ_LEN + 2):
    """Eğitilen modelin adım adım çıktı üretmesini sağlar."""
    model.eval()
    src_mask, _ = model.generate_mask(src, src)
    enc_output = model.encode(src, src_mask)

    # Çıkarıma sadece SOS (Start of Sentence) tokenı ile başla
    ys = torch.full((src.size(0), 1), SOS, dtype=torch.long).to(src.device)

    for _ in range(max_len - 1):
        _, tgt_mask = model.generate_mask(src, ys)
        out = model.decode(ys, enc_output, src_mask, tgt_mask)
        logits = model.fc_out(out[:, -1, :]) # Son üretilen adımın logit'i
        next_token = logits.argmax(dim=-1, keepdim=True) # En yüksek olasılıklı kelimeyi seç
        ys = torch.cat([ys, next_token], dim=1)

        # Eğer üretilen token EOS (End of Sentence) ise üretimi durdurabiliriz (opsiyonel)
        # Bu satır, toplu işlem (batch processing) sırasında 'item()' çağrıldığında hataya neden oluyordu.
        # 'max_len' zaten maksimum uzunluğu sınırladığı için kaldırıldı.

    return ys

# Modeli test etmek için tek bir örnek (batch_size=1) üretelim
test_src, _, _ = make_batch(batch_size=1)
prediction = greedy_decode(toy_model, test_src)

print("=== TEST SONUCU ===")
print("Girdi dizisi (Kaynak) :", test_src.tolist()[0])
print("Model çıktısı (Tahmin):", prediction.tolist()[0])

def evaluate_model(model, num_test_batches=100, batch_size=32):
    model.eval() # Modeli değerlendirme moduna al
    correct_predictions = 0
    total_predictions = 0

    print("\nModel test ediliyor...")

    for _ in range(num_test_batches):
        src_test, _, tgt_output_test = make_batch(batch_size=batch_size) # Test verisi oluştur

        # Tahminleri al
        predictions = greedy_decode(model, src_test, max_len=SEQ_LEN + 2)

        # Hedef çıktıya SOS tokenını ekleyip karşılaştırılabilir hale getir
        # greedy_decode SOS ile başladığı için tgt_output_test'e de ekliyoruz.
        tgt_with_sos = torch.cat(
            [torch.full((batch_size, 1), SOS, dtype=torch.long), tgt_output_test], dim=1
        )

        # Tahmin ve gerçek değerlerin uzunluklarını eşitlemek için pad veya kesme yap
        max_len_pred = predictions.size(1)
        max_len_tgt = tgt_with_sos.size(1)

        # En uzun diziye göre padleme veya kesme yap
        if max_len_pred > max_len_tgt:
            # Tahmin daha uzunsa hedefi padle
            padded_tgt = F.pad(tgt_with_sos, (0, max_len_pred - max_len_tgt), 'constant', PAD)
            padded_predictions = predictions
        elif max_len_tgt > max_len_pred:
            # Hedef daha uzunsa tahmini padle
            padded_predictions = F.pad(predictions, (0, max_len_tgt - max_len_pred), 'constant', PAD)
            padded_tgt = tgt_with_sos
        else:
            padded_predictions = predictions
            padded_tgt = tgt_with_sos

        # EOS tokenından sonrası önemsiz olduğu için karşılaştırmayı yapay olarak durdurabiliriz
        # Ancak 'copy' görevi olduğu için tüm dizinin doğru olması idealdir.
        # Basitlik için direk tüm diziyi karşılaştırıyorum.

        # Tam dizi eşleşmesini kontrol et
        batch_correct = (padded_predictions == padded_tgt).all(dim=1).sum().item()
        correct_predictions += batch_correct
        total_predictions += batch_size

    accuracy = correct_predictions / total_predictions
    print(f"Test setinde doğruluk: {accuracy:.4f} ({correct_predictions}/{total_predictions})\n")

evaluate_model(toy_model)

evaluate_model(toy_model)

evaluate_model(toy_model)

evaluate_model(toy_model)