# -*- coding: utf-8 -*-
"""llm_optimizasyon_aciklamali.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NezxUbH9whTbRBtlkzfsUecTHeIxEQHT

# 🧠 LLM Optimizasyon Teknikleri — Satır Satır Açıklamalı Rehber

Bu notebook dört temel LLM optimizasyon tekniğini **her satırı açıklanmış** biçimde sıfırdan uygular.

| # | Teknik | Ne kazandırır? |
|---|--------|---------------|
| 1 | **Kantizasyon** | Bellek 4–8×, Hız 2–4× |
| 2 | **KV Cache** | Tekrar hesaplama yok, O(N²)→O(N) |
| 3 | **Flash Attention** | Bellek O(N²)→O(N), Hız 2–9× |
| 4 | **Batching** | GPU kullanımı %40→%92 |

> 🟢 **GPU gerekmez** — tüm kavramlar NumPy ile sıfırdan implement edilmiştir.  
> Her kod bloğunun hemen altında açıklama bulunur.

Bu notebook, Büyük Dil Modellerinin (LLM) performansını ve bellek kullanımını iyileştirmek için dört temel optimizasyon tekniğini ayrıntılı bir şekilde ele alıyor. Her tekniği NumPy kullanarak sıfırdan uygulayarak ve her kod satırını açıklayarak, bu karmaşık kavramların temelini anlamanızı sağlıyor.

İşlenen teknikler şunlar:

1.  **Kantizasyon (Quantization)**: Model ağırlıklarının daha az bit kullanarak temsil edilmesi, bellek kullanımını 4-8 kat azaltıp hızı 2-4 kat artırır.
2.  **KV Cache**: Üretilen her token için dikkat mekanizmasının geçmiş hesaplamalarını tekrar yapmasını engeller, böylece tekrarlı hesaplamaları önler.
3.  **Flash Attention**: Dikkat mekanizmasının bellek kullanımını N²'den N'ye düşürür ve hızı 2-9 kat artırır.
4.  **Batching**: Birden fazla isteği aynı anda işleyerek GPU kullanımını ve genel verimi artırır.

Notebook, bu teknikleri GPU gerektirmeden, sadece temel matematik kütüphaneleriyle (NumPy) gösteriyor. Her bölüm, ilgili tekniğin detaylı açıklamasını ve pratik bir uygulamasını içeriyor.

---
## ⚙️ Kurulum ve İmportlar

Bu bölüm, notebook'un çalışması için gerekli olan Python kütüphanelerini import eder ve görselleştirmeler için `matplotlib` ayarlarını yapar. Kütüphaneler ve kullanımları:

-   `numpy`: Sayısal hesaplamalar için temel bir kütüphane. Matris işlemleri, matematiksel fonksiyonlar ve rastgele sayı üretimi için kullanılır.
-   `matplotlib`: Grafikler ve veri görselleştirmeleri için kullanılır. Özellikle hata dağılımı ve performans karşılaştırmaları gibi görsel çıktılar için önemlidir.
-   `time`: Kod bloklarının çalışma süresini ölçmek için kullanılır.
-   `math`: Matematiksel fonksiyonlar (örneğin karekök) sağlar.
-   `dataclasses` ve `typing`: Kodun okunabilirliğini ve anlaşılırlığını artırmak için tip ipuçları ve veri sınıfları tanımlamak için kullanılır.

Ayrıca, `matplotlib` ayarları koyu renkli bir tema kullanarak grafikleri daha estetik ve göz yormayan bir hale getirir. `np.random.seed(42)` ayarı ise, notebook'u her çalıştırdığınızda aynı 'rastgele' sayıların üretilmesini sağlayarak sonuçların tekrarlanabilirliğini garanti eder.
"""

# ── Gerekli kütüphaneler ──────────────────────────────────────────
# Temel sayısal hesaplama için NumPy
import numpy as np

# Grafik çizmek için Matplotlib
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import matplotlib.gridspec as gridspec

# Zamanlama ölçümleri için
import time

# Matematiksel fonksiyonlar (sqrt, log, ceil vb.)
import math

# Tip ipuçları için — kodun okunabilirliğini artırır
from dataclasses import dataclass        # Basit veri sınıfları için
from typing import Optional, List, Tuple # Parametre/dönüş tipi bildirimi

# ── Matplotlib karanlık tema ──────────────────────────────────────
# Her ayar ne anlama geliyor:
plt.rcParams['figure.facecolor'] = '#0d0f14'  # Figür arka planı (koyu lacivert)
plt.rcParams['axes.facecolor']   = '#13161e'  # Grafik alanı arka planı
plt.rcParams['axes.edgecolor']   = '#2a2e3e'  # Eksen kenar çizgisi rengi
plt.rcParams['text.color']       = '#e8eaf0'  # Tüm metinlerin rengi (açık gri)
plt.rcParams['axes.labelcolor']  = '#9aa0b4'  # Eksen etiketleri rengi
plt.rcParams['xtick.color']      = '#9aa0b4'  # X eksen kene rengi
plt.rcParams['ytick.color']      = '#9aa0b4'  # Y eksen kene rengi
plt.rcParams['grid.color']       = '#1e2330'  # Izgara çizgisi rengi
plt.rcParams['grid.linewidth']   = 0.5        # İnce ızgara çizgileri
plt.rcParams['axes.grid']        = True       # Izgarayı varsayılan aç
plt.rcParams['font.size']        = 11         # Varsayılan yazı boyutu

# ── Tekrarlanabilirlik ────────────────────────────────────────────
# Aynı "rastgele" sayıları her çalıştırmada elde etmek için seed
np.random.seed(42)

print("✅ Kurulum tamamlandı — notebook çalışmaya hazır!")

"""> **Neden bu kütüphaneler?**
> - `numpy` → Matris çarpımları, yuvarlama, istatistik — GPU gerektirmeden hızlı
> - `matplotlib` → Her bölümde görsel çıktı
> - `dataclass` → Model konfigürasyonlarını temiz saklama
> - `typing` → Fonksiyon parametrelerini belgeler, IDE otomatik tamamlamayı aktif eder

---
# 📦 Bölüm 1 — Kantizasyon (Quantization)

**Sorun:** GPT-3 175B model, FP32'de 700 GB yer kaplar. Hiçbir GPU bu kadar VRAM taşımaz.  
**Çözüm:** Ağırlıkları daha az bit kullanan formata *dönüştür* — küçük hassasiyet kaybı karşılığında büyük kazanım.

### Temel sezgi
```
FP32:  0.31415926535...  →  4 bayt, sonsuz hassasiyet
INT8:  40               →  1 bayt, 256 olası değer
INT4:  5                →  0.5 bayt, 16 olası değer
```
Bir fotoğrafı JPEG'e sıkıştırmak gibi — biraz kalite kaybı, çok daha küçük dosya.

Kantizasyon, Büyük Dil Modellerini (LLM) daha küçük ve daha hızlı hale getiren kritik bir optimizasyon tekniğidir. Temel sorun, LLM'lerin genellikle çok büyük olmaları ve yüksek hassasiyetli sayı formatları (örneğin FP32) kullandıklarında muazzam miktarda bellek tüketmeleridir. Örneğin, 175 milyar parametreli bir GPT-3 modeli FP32 hassasiyetinde 700 GB yer kaplar ki bu, piyasadaki çoğu GPU'nun bellek kapasitesini aşar.

Kantizasyonun çözümü, model ağırlıklarını daha az bit kullanan formatlara dönüştürmektir. Bu, hassasiyette hafif bir kayba neden olur ancak bellek ve hızda büyük kazançlar sağlar. Tıpkı bir fotoğrafı JPEG formatına sıkıştırırken kalitede hafif bir düşüş karşılığında dosya boyutunun önemli ölçüde azalması gibi düşünülebilir.

Örneğin:
-   **FP32 (Floating Point 32-bit)**: 4 bayt yer kaplar ve çok yüksek hassasiyet sunar. Yaklaşık 3.4 x 10^38'e kadar değerleri temsil edebilir.
-   **INT8 (Integer 8-bit)**: 1 bayt yer kaplar ve 256 farklı tam sayı değerini (-128'den 127'ye) temsil edebilir.
-   **INT4 (Integer 4-bit)**: 0.5 bayt yer kaplar ve sadece 16 farklı tam sayı değerini (-8'den 7'ye) temsil edebilir.

Bu bölümde, farklı sayı formatlarının bellek ayak izlerini karşılaştıran bir tablo görüyorsunuz. FP32'den INT4'e geçişin 8 kat sıkıştırma sağladığı ve bu sayede daha büyük modellerin daha az VRAM'e sahip GPU'larda bile çalışabileceği gösteriliyor. Örneğin, 7B parametreli bir model FP32'de 28 GB yer kaplarken, INT4'te sadece 3.5 GB yer kaplar ve bu, 12GB VRAM'e sahip bir RTX 3060 ekran kartında bile çalıştırılabileceği anlamına gelir.

## 1.1 — Sayı Formatlarını Anlamak

Bu kısım, kantizasyonun nasıl çalıştığını matematiksel olarak açıklayan `Quantizer` sınıfını içerir. Kantizasyonun iki ana modu vardır:

1.  **Simetrik (Symmetric) Kantizasyon**: Bu yöntemde sıfır noktası her zaman 0'dır. Yani, sayı aralığı -Max ile +Max arasında simetrik olarak dağılır. `scale` faktörü, ağırlık matrisindeki en büyük mutlak değerin `q_max` (kullanılan bit sayısına göre maksimum tam sayı değeri) bölünmesiyle hesaplanır. `W_int = round(W / scale)` formülü ile float değerler tam sayıya dönüştürülür ve `W_geri = W_int × scale` ile geri çevrilir.

2.  **Asimetrik (Affine) Kantizasyon**: Bu modda sıfır noktası serbesttir ve ağırlıkların dağılımı simetrik olmadığında daha iyi sonuçlar verebilir. `scale` faktörü, `max(W) - min(W)` değerinin `(2^n - 1)` (kullanılan bit sayısına göre toplam seviye sayısı) bölünmesiyle hesaplanır. `zero_point` ise `-min(W) / scale` değerinin yuvarlanmasıyla bulunur. `W_int = round(W / scale) + zero_point` ile tam sayıya dönüştürülür ve `W_geri = (W_int - zero_point) × scale` ile geri çevrilir.

`Quantizer` sınıfı, bu iki modu destekler ve ağırlık matrislerine (W) bakarak en uygun `scale` ve `zero_point` değerlerini hesaplar (`kalibrasyon` metodu). Daha sonra `kantize_et` metodu float değerleri tam sayıya dönüştürür ve `kantize_geri_al` metodu tam sayıları yaklaşık olarak orijinal float değerlerine çevirir. `tam_dongu` metodu ise hem kantizasyon hem de de-kantizasyon işlemini tek bir adımda gerçekleştirir.

Kod bloğunun çıktısı, farklı bit sayıları (8, 4, 2) ve kantizasyon modları (simetrik, asimetrik) için ortalama mutlak hata (MAE) ve maksimum hatayı karşılaştırır. Bu, bit sayısı azaldıkça hatanın arttığını ve asimetrik modun bazı durumlarda daha düşük hata verdiğini gösterir.
"""

# ── Farklı sayı formatlarının kapasiteleri ───────────────────────
# Her format için temel özellikler bir sözlükte toplanıyor
formats = {
    # İsim : {bit sayısı, sayı aralığı, bayt/parametre, kaç farklı değer}
    "FP32": {"bits": 32, "min": -3.4e38, "max": 3.4e38,  "bytes": 4.0,  "levels": None},
    "FP16": {"bits": 16, "min": -65504,  "max": 65504,   "bytes": 2.0,  "levels": None},
    "BF16": {"bits": 16, "min": -3.4e38, "max": 3.4e38,  "bytes": 2.0,  "levels": None},
    "INT8": {"bits": 8,  "min": -128,    "max": 127,     "bytes": 1.0,  "levels": 256},
    "INT4": {"bits": 4,  "min": -8,      "max": 7,       "bytes": 0.5,  "levels": 16},
    "INT2": {"bits": 2,  "min": -2,      "max": 1,       "bytes": 0.25, "levels": 4},
}

# ── Tablo başlığı yazdır ─────────────────────────────────────────
print(f"{'Format':<8} {'Bit':>4} {'Seviye':>8} {'Byte':>6}  "
      f"{'7B model':>10}  {'70B model':>10}")
print("─" * 58)

# ── Her format için bellek hesapla ───────────────────────────────
for isim, f in formats.items():
    # Seviye sayısı: float formatlar sürekli, int formatlar sınırlı
    seviye = str(f["levels"]) if f["levels"] else "sürekli"

    # Bellek = parametre_sayısı × bayt_per_parametre
    #   7  milyar parametre × bayt/param → GB
    mem_7b  = f"{7e9  * f['bytes'] / 1e9:.1f} GB"
    mem_70b = f"{70e9 * f['bytes'] / 1e9:.0f} GB"

    print(f"{isim:<8} {f['bits']:>4} {seviye:>8} "
          f"{f['bytes']:>6.2f}  {mem_7b:>10}  {mem_70b:>10}")

# ── Pratik çıkarım ────────────────────────────────────────────────
print()
print("💡 FP32 → INT4 = 8× sıkıştırma:")
print(f"   7B model: 28 GB → 3.5 GB  (RTX 3060 12GB'a SIĞAR!)")
print(f"  70B model: 280 GB → 35 GB  (2× RTX 4090 ile çalışır)")

"""> **FP16 vs BF16 farkı:** Her ikisi de 16 bittir ama bit dağılımı farklı.
> - `FP16`: 1 işaret + 5 üs + 10 mantis → Hassas ama küçük aralık (±65504)
> - `BF16`: 1 işaret + 8 üs + 7 mantis → FP32 ile aynı aralık, daha az hassasiyet
>
> LLM eğitiminde BF16 tercih edilir: sayısal taşma (overflow) riski yoktur.

## 1.2 — Kantizasyon Matematiği: Simetrik ve Asimetrik
"""

class Quantizer:
    """
    Tek bir ağırlık tensörünü kantize eden temel sınıf.

    İki mod desteklenir:
    ─────────────────────────────────────────────────────────
    SİMETRİK (symmetric):
        Sıfır noktası her zaman 0'dır.
        scale = max(|W|) / (2^(n-1) - 1)
        W_int = round(W / scale)
        W_geri = W_int × scale

    ASİMETRİK (affine):
        Sıfır noktası serbest — dağılım sola/sağa kaymış olabilir.
        scale = (max(W) - min(W)) / (2^n - 1)
        zero_point = round(-min(W) / scale)
        W_int = round(W / scale) + zero_point
        W_geri = (W_int - zero_point) × scale
    ─────────────────────────────────────────────────────────
    """

    def __init__(self, bits: int = 8, mod: str = "symmetric"):
        # Kaç bit kullanacağız? (2, 4, 8 tipik değerler)
        self.bits = bits
        # Hangi kantizasyon modu?
        self.mod  = mod

        # ── Tam sayı aralığını belirle ───────────────────────────
        if mod == "symmetric":
            # Simetrik: [-128, 127] gibi (8 bit için)
            # 2^(n-1) = işaret biti hariç maksimum pozitif değer
            self.q_min = -(2 ** (bits - 1))      # -128 (8 bit)
            self.q_max =  (2 ** (bits - 1)) - 1  #  127 (8 bit)
        else:
            # Asimetrik: [0, 255] gibi — tüm pozitif aralık
            self.q_min = 0
            self.q_max = (2 ** bits) - 1          # 255 (8 bit)

        # Kalibrasyon sonrası doldurulacak değerler
        self.scale      = None  # ölçek faktörü
        self.zero_point = None  # sıfır noktası (asimetrik modda ≠ 0)

    # ── 1. ADIM: Ölçeği Bul ─────────────────────────────────────
    def kalibrasyon(self, W: np.ndarray) -> None:
        """
        W tensörüne bakarak en iyi scale (ve zero_point) değerini hesapla.
        Bu adım LLM'de bir kez yapılır; sonra scale kaydedilir.
        """
        if self.mod == "symmetric":
            # En büyük mutlak değeri bul
            max_deger = np.max(np.abs(W))

            # Sıfır kontrolü: boş tensöre karşı güvenlik
            self.scale = max_deger / self.q_max if max_deger > 0 else 1.0
            self.zero_point = 0  # Simetrik: sıfır noktası daima 0

        else:  # affine / asimetrik
            w_min = W.min()
            w_max = W.max()

            # Tüm aralığı 2^n - 1 dilime böl
            aralik = (w_max - w_min)
            self.scale = aralik / (self.q_max - self.q_min) if aralik > 0 else 1.0

            # Sıfırın tam sayı karşılığını hesapla
            zp = self.q_min - w_min / self.scale
            # Tam sayıya yuvarla ve sınırla
            self.zero_point = int(np.clip(np.round(zp), self.q_min, self.q_max))

    # ── 2. ADIM: Float → Integer ─────────────────────────────────
    def kantize_et(self, W: np.ndarray) -> np.ndarray:
        """
        W (float32) tensörünü tam sayı temsiline dönüştür.
        Bu adım disk/belleğe kaydedilen değerdir.
        """
        if self.scale is None:
            self.kalibrasyon(W)  # İlk kez çağrıldıysa otomatik kalibre et

        # round(): sürekli değeri en yakın tam sayıya yuvarla
        W_int = np.round(W / self.scale) + self.zero_point

        # clip(): aralık dışına çıkan değerleri sınırla
        return np.clip(W_int, self.q_min, self.q_max).astype(np.int32)

    # ── 3. ADIM: Integer → Float (yaklaşık) ─────────────────────
    def kantize_geri_al(self, W_int: np.ndarray) -> np.ndarray:
        """
        Tam sayıyı float'a geri çevir.
        Yuvarlama nedeniyle orijinal W ile tam aynı OLMAZ — bu kayıp kantizasyon hatasıdır.
        """
        return (W_int.astype(np.float32) - self.zero_point) * self.scale

    # ── Tam döngü: forward pass sırasında kullanılır ─────────────
    def tam_dongu(self, W: np.ndarray) -> np.ndarray:
        """Float → Int → Float (hassasiyet kaybıyla)."""
        return self.kantize_geri_al(self.kantize_et(W))

    @property
    def adim_buyuklugu(self):
        """Δ (Delta): İki komşu kantizasyon seviyesi arasındaki mesafe."""
        return self.scale

    @property
    def seviye_sayisi(self):
        """Kaç farklı değer kodlanabilir? = 2^bits"""
        return 2 ** self.bits


# ── Test: gerçek LLM ağırlık dağılımı simülasyonu ────────────────
# LLM ağırlıkları genellikle sıfır etrafında normal dağılım gösterir
# Standart sapma ~0.02–0.3 arasında değişir
W_ornek = np.random.randn(8, 8).astype(np.float32) * 0.25

print("📊 Kantizasyon Hata Karşılaştırması")
print(f"{'Format':<18} {'Mod':<12} {'Adım (Δ)':>10} {'MAE':>10} {'Max Hata':>10} {'Seviye':>8}")
print("─" * 72)

for bits in [8, 4, 2]:
    for mod in ["symmetric", "affine"]:
        # 1. Quantizer oluştur
        q = Quantizer(bits=bits, mod=mod)

        # 2. Kalibre et (scale bul)
        q.kalibrasyon(W_ornek)

        # 3. Tam döngü uygula
        W_hat = q.tam_dongu(W_ornek)

        # 4. Hata hesapla
        hata = np.abs(W_ornek - W_hat)  # Mutlak hata matrisi
        mae  = hata.mean()              # Ortalama mutlak hata
        maks = hata.max()               # Maksimum hata

        label = f"INT{bits}"
        print(f"{label:<18} {mod:<12} {q.adim_buyuklugu:>10.5f} "
              f"{mae:>10.5f} {maks:>10.5f} {q.seviye_sayisi:>8}")

"""> **Neler öğrendik?**
> - `kalibrasyon()` → scale'i bir kez hesaplar, modelle birlikte kaydedilir
> - `kantize_et()` → float → int dönüşümü: `round(W / scale) + zp`
> - `kantize_geri_al()` → int → float dönüşümü: `(W_int - zp) * scale`
> - **Hata kaçınılmazdır:** `round()` her zaman küçük bir fark bırakır
> - **Asimetrik her zaman daha iyi değildir** — zero_point ek alan kullanır
> - INT8 ile hata küçük (MAE ~0.002), INT2 ile büyük (MAE ~0.19)

Bu bölümde, kantizasyonun neden olduğu hatanın görsel bir analizi yapılır. Büyük bir ağırlık matrisi (`W_buyuk`) kullanılarak, farklı bit sayılarında (8, 4, 3, 2) kantizasyon uygulandıktan sonra ortaya çıkan hata dağılımları histogramlar ve matrislerin renk haritaları (ısı haritaları) ile gösterilir.

**Grafiğin üst satırı**, ağırlık matrisinin 32x32'lik bir kısmının renk haritasını gösterir. INT8'de orijinal matrisin detayları büyük ölçüde korunurken, bit sayısı azaldıkça (örneğin INT2'de) matrisin detayları kaybolur ve daha pikselli bir görünüm oluşur. Bu, daha düşük bit sayılarının daha fazla bilgi kaybına neden olduğunu gösterir.

**Grafiğin alt satırı**, her kantizasyon seviyesi için hata dağılımının histogramını gösterir. Hata (orijinal ağırlık eksi kantize edilmiş ve geri çevrilmiş ağırlık), sıfır etrafında yoğunlaşmalıdır. Histogram ne kadar dar olursa, hata o kadar azdır ve kantizasyon kalitesi o kadar iyidir. Sarı kesik çizgiler (`±Δ/2`), kantizasyon hatasının teorik sınırlarını gösterir; hata her zaman bu bant içinde kalmalıdır. Gördüğünüz gibi, bit sayısı azaldıkça bu bant genişler ve hata olasılığı artar.

**SNR (Signal-to-Noise Ratio)** değeri de her bitin yaklaşık 6 dB'lik bir kazanç sağladığını gösterir. Bu, daha fazla bitin daha az gürültü (hata) ve daha yüksek sinyal kalitesi anlamına geldiğini ifade eder. Sonuç olarak, bu görselleştirmeler bit sayısı azaldıkça kantizasyon hatasının dramatik bir şekilde büyüdüğünü açıkça ortaya koyar.

## 1.3 — Hata Dağılımı Görselleştirmesi
"""

# ── Büyük bir matris üzerinde hata analizi ───────────────────────
# 256×256 = 65536 ağırlık — gerçek bir LLM katmanını simüle eder
W_buyuk = np.random.randn(256, 256).astype(np.float32) * 0.15

# ── 4 farklı bit sayısı için grafik ─────────────────────────────
fig, satirlar = plt.subplots(2, 4, figsize=(16, 8))
fig.suptitle("Kantizasyon: Bit Sayısı Azaldıkça Hata Büyür",
             fontsize=14, color='#e8eaf0', y=1.01)

bit_listesi = [8, 4, 3, 2]                              # Test edilecek bit değerleri
renkler     = ['#6c8ef5', '#34d399', '#fbbf24', '#f87171']  # Her bit için renk

for sutun, bits in enumerate(bit_listesi):
    # ── Kantizasyon uygula ───────────────────────────────────────
    q = Quantizer(bits=bits, mod="symmetric")
    W_hat = q.tam_dongu(W_buyuk)          # Float → Int → Float
    hata  = W_buyuk - W_hat               # Her elementin hatası

    # ── Üst satır: 32×32 matrisin ısı haritası ──────────────────
    ax_ust = satirlar[0][sutun]
    # imshow: matris değerlerini renk olarak göster
    # cmap='RdBu' → kırmızı (negatif) / mavi (pozitif)
    # vmin/vmax: renk skalasını sabitle — karşılaştırma için
    ax_ust.imshow(W_buyuk[:32, :32],
                  cmap='RdBu', aspect='auto',
                  vmin=-0.4, vmax=0.4)

    # Başlık: bit sayısı ve toplam seviye sayısı
    ax_ust.set_title(f"INT{bits}  ({2**bits} seviye)",
                     color=renkler[sutun], fontsize=11, fontweight='bold')

    # Soldan birinci sütuna Y etiketi ekle
    if sutun == 0:
        ax_ust.set_ylabel("Ağırlık Matrisi", color='#9aa0b4')

    # Sayısal eksen kenelerini gizle — görseli sadeleştir
    ax_ust.set_xticks([])
    ax_ust.set_yticks([])

    # ── Alt satır: hata histogramı ───────────────────────────────
    ax_alt = satirlar[1][sutun]

    # Hata değerlerini düzleştir (matris → 1D dizi) ve histogram çiz
    ax_alt.hist(hata.flatten(),
                bins=80,                    # Kaç çubuk?
                color=renkler[sutun],
                alpha=0.75,                 # Hafif şeffaf
                density=True)               # Y ekseni olasılık yoğunluğu

    # Sıfır hata çizgisi (ideal durum)
    ax_alt.axvline(x=0, color='white', lw=0.8, alpha=0.5)

    # Teorik hata sınırları: ±Δ/2
    # Kantizasyon hatası her zaman bu bantın içinde kalmalı
    delta_yari = q.adim_buyuklugu / 2
    ax_alt.axvline(x=+delta_yari, color='#fbbf24', lw=1.2,
                   ls='--', alpha=0.8, label=f'+Δ/2={delta_yari:.3f}')
    ax_alt.axvline(x=-delta_yari, color='#fbbf24', lw=1.2,
                   ls='--', alpha=0.8, label=f'-Δ/2')

    # İstatistik: MAE ve teorik SNR
    mae = np.abs(hata).mean()
    # SNR formülü: her bit ~6 dB kazandırır (Shannon bilgi teorisi)
    snr_db = 6.02 * bits + 1.76

    ax_alt.set_title(f"MAE={mae:.4f}  SNR≈{snr_db:.1f}dB",
                     fontsize=9, color='#9aa0b4')

    if sutun == 0:
        ax_alt.set_ylabel("Hata Yoğunluğu", color='#9aa0b4')

    ax_alt.set_xlabel("Kantizasyon Hatası e(n) = W - Ŵ", color='#9aa0b4')
    ax_alt.legend(fontsize=8)

plt.tight_layout()
plt.savefig('kantizasyon_hata.png', dpi=150,
            bbox_inches='tight', facecolor='#0d0f14')
plt.show()
print("✅ Grafik kaydedildi: kantizasyon_hata.png")

"""> **Grafiği okumak:**
> - **Üst satır:** Matrisin renk haritası — INT8'de detay çok, INT2'de neredeyse hiç yok
> - **Alt satır:** Hata dağılımı — dar histogram = küçük hata = iyi kalite  
> - **Sarı kesik çizgiler (±Δ/2):** Hatanın teorik sınırları — INT8'de dar, INT2'de geniş
> - **SNR:** Her bit yaklaşık 6 dB kazandırır — bu doğrusal (dB ölçeği) ama bit üslü

## 1.4 — Kanal Bazlı Kantizasyon (Per-Channel)
"""

class KanalBazliQuantizer:
    """
    Per-Channel (Kanal bazlı) kantizasyon.

    Sorun: Bir transformer katmanında farklı çıkış kanalları ÇOK
    farklı ağırlık büyüklüklerine sahip olabilir.

    Örnek:
        kanal_0: ağırlıklar [-0.01, +0.01] aralığında
        kanal_5: ağırlıklar [-2.50, +2.50] aralığında

    Per-tensor kantizasyon: tek bir scale tüm kanallar için → kanal_0 mahvolur
    Per-channel kantizasyon: her kanal kendi scale'ini alır → her ikisi de korunur
    """

    def __init__(self, bits: int = 8, eksen: int = 0):
        self.bits  = bits
        # eksen=0: output kanalları boyunca kalibre et (en yaygın)
        # eksen=1: input kanalları boyunca kalibre et
        self.eksen = eksen
        self.q_maks = (2 ** (bits - 1)) - 1  # INT8 → 127
        self.scaleler = None  # Her kanal için ayrı scale

    def kalibrasyon(self, W: np.ndarray) -> None:
        """Her output kanalı için bağımsız scale hesapla."""
        # Kalibre etmek istemediğimiz tüm eksenleri bul
        # Örn: W şekli (64, 256) ve eksen=0 ise → dim_1=256 boyunca max al
        diger_eksenler = tuple(i for i in range(W.ndim) if i != self.eksen)

        # Her kanal için mutlak maksimum değer
        # keepdims=False → her kanaldan bir scalar gelir
        maks_degerler = np.max(np.abs(W), axis=diger_eksenler)

        # scale = max(|W|) / q_maks  (her kanal için)
        # Sıfıra bölmeden kaçın: max_deger=0 ise scale=1 al
        self.scaleler = np.where(
            maks_degerler > 0,
            maks_degerler / self.q_maks,
            1.0
        )

    def tam_dongu(self, W: np.ndarray) -> np.ndarray:
        """Float → Int → Float, her kanal kendi scale'iyle."""
        if self.scaleler is None:
            self.kalibrasyon(W)

        # Broadcasting için shape ayarla:
        # scaleler: [64] → [64, 1] (eksen=0, W şekli [64, 256])
        # Bu sayede her satır kendi scale'iyle bölünür
        yeni_sekil = [-1] + [1] * (W.ndim - 1)
        scaleler_2d = self.scaleler.reshape(yeni_sekil)

        # Kantize et
        W_int = np.clip(
            np.round(W / scaleler_2d),
            -self.q_maks - 1,
            self.q_maks
        )

        # Geri al (dequantize)
        return (W_int * scaleler_2d).astype(np.float32)


# ── Karşılaştırma deneyi ─────────────────────────────────────────
# Gerçek LLM'lerde yaygın: her kanal FARKLI büyüklükte
np.random.seed(0)
W_kanallar = np.zeros((64, 64), dtype=np.float32)

for kanal in range(64):
    # Her kanal için rastgele bir ölçek seç (bazı kanallar çok büyük)
    olcek = np.random.exponential(scale=0.2) + 0.01
    W_kanallar[kanal] = np.random.randn(64) * olcek

print("🔬 Per-Tensor vs Per-Channel Kantizasyon Karşılaştırması")
print("─" * 58)
print(f"{'Format + Mod':<25} {'MAE':>10} {'Görsel Bar'}")
print("─" * 58)

sonuclar = {}
for bits in [8, 4]:
    # Per-Tensor: tüm matris için tek scale
    q_tensor  = Quantizer(bits=bits, mod="symmetric")
    W_tensor  = q_tensor.tam_dongu(W_kanallar)
    mae_tensor = np.abs(W_kanallar - W_tensor).mean()

    # Per-Channel: her output kanalı için ayrı scale
    q_kanal   = KanalBazliQuantizer(bits=bits)
    W_kanal   = q_kanal.tam_dongu(W_kanallar)
    mae_kanal = np.abs(W_kanallar - W_kanal).mean()

    sonuclar[f"INT{bits}_tensor"]  = mae_tensor
    sonuclar[f"INT{bits}_channel"] = mae_kanal

    # Isı çubuğu: MAE'yi görsel olarak temsil et
    for etiket, mae in [(f"INT{bits} Per-Tensor", mae_tensor),
                         (f"INT{bits} Per-Channel", mae_kanal)]:
        bar_uzunluk = int(mae * 3000)   # MAE'yi bar uzunluğuna ölçekle
        bar = "█" * min(bar_uzunluk, 40)
        print(f"{etiket:<25} {mae:>10.5f}  {bar}")

    # Kazanım oranı
    kazanim = mae_tensor / mae_kanal
    print(f"  → Per-Channel, {kazanim:.1f}× daha az hata (INT{bits})")
    print()

"""> **Neden per-channel bu kadar iyi?**
>
> Per-tensor tek bir scale seçmek zorundadır: ya büyük kanalı kap (küçük kanalda çözünürlük kaybolur)
> ya da küçük kanalı kap (büyük kanal kırpılır — daha kötü).
>
> Per-channel her kanal için **optimal scale** seçer. Ek maliyet: katman başına
> `n_output_channels` adet float32 scale saklanır — genellikle ihmal edilebilir.

Bu bölüm, LLM optimizasyonunda kullanılan **Per-Channel (Kanal Bazlı) Kantizasyon** tekniğini ve `KanalBazliQuantizer` sınıfını tanıtır. Standard kantizasyon (Per-Tensor), tüm ağırlık matrisi için tek bir ölçek (scale) faktörü kullanırken, Per-Channel kantizasyon, matrisin her bir çıkış kanalı için ayrı bir ölçek faktörü hesaplar.

**Sorun**: Bir Transformer katmanındaki farklı çıkış kanalları genellikle çok farklı ağırlık büyüklüklerine sahip olabilir. Örneğin, bir kanalın ağırlıkları küçük bir aralıkta ([-0.01, +0.01]), başka bir kanalın ağırlıkları ise çok daha geniş bir aralıkta ([-2.50, +2.50]) olabilir.

-   **Per-Tensor Kantizasyon** bu durumda sorun yaratır: eğer scale faktörü büyük kanala göre ayarlanırsa, küçük kanaldaki hassasiyet kaybolur. Eğer küçük kanala göre ayarlanırsa, büyük kanaldaki ağırlıklar kırpılır (clipping) ve büyük hata oluşur.

-   **Per-Channel Kantizasyon** bu sorunu çözer: her kanal kendi optimal scale faktörünü alır. Bu sayede, hem küçük aralıktaki kanallar hassasiyetini korur hem de büyük aralıktaki kanallar kırpılmadan doğru bir şekilde kantize edilir.

`KanalBazliQuantizer` sınıfı, `kalibrasyon` metodunda her bir çıkış kanalı için bağımsız `scale` değerlerini (`self.scaleler`) hesaplar. `tam_dongu` metodu ise bu kanal bazlı scale'leri kullanarak kantizasyon ve de-kantizasyon işlemini gerçekleştirir. Özellikle `yeni_sekil` ve `scaleler_2d` değişkenleri, NumPy'ın broadcasting özelliğini kullanarak her kanalın kendi scale'i ile bölünmesini sağlar.

Test çıktısı, Per-Channel kantizasyonun, Per-Tensor kantizasyona göre **daha az hata** (yaklaşık 5.9 kat) ile çok daha iyi performans gösterdiğini açıkça ortaya koyar. Bu, özellikle LLM'lerdeki heterojen ağırlık dağılımları düşünüldüğünde, Per-Channel yaklaşımın neden tercih edildiğini gösterir. Ek maliyet olarak, katman başına `n_output_channels` adet float32 scale değeri saklanır, ki bu genellikle ihmal edilebilir bir bellek yüküdür.

## 1.5 — GPTQ Algoritması: Hata Yayılımlı Kantizasyon

Bu bölüm, kantizasyon hatasını daha da azaltmayı hedefleyen gelişmiş bir kantizasyon algoritması olan **GPTQ (General-purpose Quantization)**'yu tanıtır. Standart kantizasyon yöntemleri (Naive PTQ - Post-Training Quantization), her ağırlığı bağımsız olarak yuvarlar ve bu, modelin genel performansında birikimli hatalara yol açabilir.

**GPTQ'nun Temel Fikri**: Her ağırlık kantize edildiğinde oluşan hatayı, modelin geri kalan (henüz kantize edilmemiş) ağırlıklarına stratejik olarak **dağıtmaktır**. Bu sayede, toplam kantizasyon hatası minimize edilir. GPTQ, bu hatayı dağıtırken **Hessian matrisini** kullanır. Hessian matrisi, her bir ağırlığın model çıktısı üzerindeki 'önemini' veya 'hassasiyetini' ölçer.

`gptq_kantize` fonksiyonu, bu algoritmanın basitleştirilmiş bir versiyonunu uygular. Adımlar şunlardır:

1.  **Blok Bazlı İşlem**: Tüm ağırlıkları tek seferde işlemek yerine, GPU belleğini verimli kullanmak için ağırlık matrisi bloklara ayrılır.
2.  **Sütun Bazlı Kantizasyon ve Hata Yayılımı**: Her sütun sırayla kantize edilir. Sütun `j` kantize edildiğinde, oluşan `(w_sutun - q_sutun)` hatası hesaplanır.
3.  **Hessian ile Düzeltme**: Bu hata, Hessian matrisinin tersi (`H_inv`) kullanılarak henüz kantize edilmemiş sonraki sütunlara (`W_blok[:, j+1:]`) dağıtılır ve düzeltme uygulanır. Bu, sonraki ağırlıkların, önceki ağırlıkların yuvarlama hatasını telafi edecek şekilde ayarlanmasını sağlar.

Test çıktısı, **GPTQ**'nun **Naive PTQ**'ya kıyasla önemli ölçüde daha düşük ortalama mutlak hata (MAE) sağladığını gösterir. Örneğin, INT4 kantizasyonda 1.58 kat, INT3 kantizasyonda ise 1.92 kat daha iyi sonuçlar elde edilir. Bu, GPTQ'nun, özellikle çok düşük bit hassasiyetlerinde (örneğin 4-bit veya 3-bit) model kalitesini korumak için ne kadar etkili olduğunu gösterir.
"""

def gptq_kantize(W: np.ndarray,
                 bits: int,
                 blok_boyutu: int = 128,
                 damping: float = 0.01) -> Tuple[np.ndarray, float]:
    """
    GPTQ (Optimal Brain Quantization tabanlı) — basitleştirilmiş versiyon.
    Referans: Frantar et al., 2022 (https://arxiv.org/abs/2210.17323)

    Temel fikir:
    ────────────────────────────────────────────────────────────
    Naive kantizasyon: her ağırlığı bağımsız yuvarla → birikimli hata büyür

    GPTQ: Bir sütunu kantize ettiğinde oluşan hatayı, Hessian matrisini
    kullanarak KALANSütunlara dağıt → toplam hata minimize edilir.

    Hessian: H ≈ X·Xᵀ (X = bu katmana giren aktivasyonlar)
    Sadece X'in diyagonali = ağırlığın ne kadar "önemli" olduğu

    Adımlar (her sütun j için):
    1. W[:,j] yi kantize et → Q[:,j]
    2. Hata: err = W[:,j] - Q[:,j]
    3. Kalan sütunları düzelt: W[:,j+1:] -= err · H_inv[j, j+1:] / H[j,j]
    ─────────────────────────────────────────────────────────────
    """

    # Kopyala — orijinali bozma
    W = W.copy().astype(np.float64)
    satir, sutun = W.shape

    # INT sınırları: n bit → [-2^(n-1), 2^(n-1)-1]
    q_maks = (2 ** (bits - 1)) - 1

    # ── Hessian yaklaşımı ────────────────────────────────────────
    # Gerçekte: H = X·Xᵀ / |X| (kalibrasyon verisiyle)
    # Burada: kimlik matrisi (basitlik için)
    H = np.eye(sutun, dtype=np.float64)
    # Damping: sayısal kararsızlığı önler (küçük pozitif sayı ekle)
    H += damping * np.eye(sutun)

    # Kantize edilmiş ağırlıklar için boş matris
    W_kant = np.zeros_like(W)

    # ── Blok bazlı işlem ─────────────────────────────────────────
    # Tüm sütunları tek seferde işlemek yerine blok blok işle
    # Neden? Hessian tersinin bellekte tutulması için
    for blok_bas in range(0, sutun, blok_boyutu):
        blok_son   = min(blok_bas + blok_boyutu, sutun)

        # Bu bloktaki W ve H dilimleri
        W_blok = W[:, blok_bas:blok_son].copy()
        H_blok = H[blok_bas:blok_son, blok_bas:blok_son]

        # Hessian bloğunun tersini al (hata düzeltme için gerekli)
        try:
            # Küçük bir regularizasyon ekle → sayısal istikrar
            H_inv = np.linalg.inv(
                H_blok + np.eye(blok_son - blok_bas) * 1e-6
            )
        except np.linalg.LinAlgError:
            # Matris tekil (singular) ise kimlik matrisini kullan
            H_inv = np.eye(blok_son - blok_bas)

        Q_blok = np.zeros_like(W_blok)

        # ── Her sütunu soldan sağa kantize et ───────────────────
        for j in range(blok_son - blok_bas):
            w_sutun = W_blok[:, j]  # Bu sütunun tüm satırları

            # Sütun için scale hesapla
            maks = np.max(np.abs(w_sutun))
            scale = maks / q_maks if maks > 0 else 1.0

            # Sütunu kantize et ve geri al
            q_sutun = np.clip(
                np.round(w_sutun / scale), -q_maks - 1, q_maks
            ) * scale

            Q_blok[:, j] = q_sutun

            # ── Hata yayılımı (GPTQ'nun kalbi) ─────────────────
            # Kantizasyon hatası
            hata = (w_sutun - q_sutun).reshape(-1, 1)  # [satir, 1]

            # Bu hatanın kalan sütunlara etkisi:
            # düzeltme = hata × H_inv[j, j+1:] / H[j,j]
            # (Hessian, hatanın hangi sütunu ne kadar etkilediğini söyler)
            if j + 1 < blok_son - blok_bas:
                duzeltme = hata @ H_inv[j:j+1, j+1:] / (H_inv[j, j] + 1e-10)
                W_blok[:, j+1:] -= duzeltme  # Kalan sütunları düzelt

        W_kant[:, blok_bas:blok_son] = Q_blok

    # Ortalama mutlak hata (MAE)
    mae = float(np.abs(W - W_kant).mean())
    return W_kant.astype(np.float32), mae


# ── Karşılaştırma: Naive PTQ vs GPTQ ────────────────────────────
np.random.seed(7)
W_test = np.random.randn(32, 64).astype(np.float32) * 0.2

print("🔬 Naive PTQ vs GPTQ — INT4 ve INT3")
print("─" * 52)
print(f"{'Format':<10} {'Yöntem':<12} {'MAE':>10} {'Kazanım':>10}")
print("─" * 52)

for bits in [4, 3]:
    # Naive: her ağırlığı bağımsız kantize et
    q_naive  = Quantizer(bits=bits, mod="symmetric")
    W_naive  = q_naive.tam_dongu(W_test)
    mae_naive = float(np.abs(W_test - W_naive).mean())

    # GPTQ: hata yayılımıyla kantize et
    W_gptq, mae_gptq = gptq_kantize(W_test, bits=bits)

    kazanim = mae_naive / mae_gptq

    print(f"INT{bits:<8} {'Naive PTQ':<12} {mae_naive:>10.5f}   {'—'}")
    print(f"INT{bits:<8} {'GPTQ':<12} {mae_gptq:>10.5f}   {kazanim:.2f}× daha iyi")
    print()

"""> **GPTQ'yu anlamak:**
> - **Naive PTQ:** Her ağırlığı tek tek bağımsız yuvarlar. Sonraki ağırlıklar bu hatadan habersiz.
> - **GPTQ:** Bir ağırlığı yuvarlayınca oluşan hatayı komşu ağırlıklara *söyler*.  
>   Onlar bu hatayı telafi edecek şekilde hafifçe kayar — sonuçta toplam hata azalır.
> - **Hessian neden?** Hangi yönde ne kadar kaydığımızın çıktıya etkisini ölçer.
>   Büyük Hessian = o ağırlık önemli = daha dikkatli kantize et.

---
# 🗃️ Bölüm 2 — KV Cache

### Sorun: Her token üretilirken tüm geçmiş yeniden hesaplanıyor

Transformer'da attention şöyle çalışır:
```
1. Prompt: "Merhaba dünya bu bir test"  (5 token)
2. Yeni token üret → 6. token için:
   - 6. tokenın Q'su hesaplanır
   - Tüm 6 tokenın K ve V'si hesaplanır  ← GEREKSİZ! 1-5 bir önceki adımda vardı
   - Attention: Q × Kᵀ → sonuç
3. 7. token için: KV yeniden hesaplanır (7 kez)  ← 2 tekrar gereksiz
4. N. token için: N kez hesaplanır ← N-1 tekrar gereksiz!
```

### Çözüm: KV Cache
```
N. token → yalnızca N. tokenın K ve V'si hesaplanır (1 kez)
           geçmiş K,V bellekten okunur (cache hit)
```

Bu bölüm, LLM'lerde çıkarım hızını önemli ölçüde artıran **KV Cache** tekniğini ele alır. Sorun, geleneksel Transformer mimarisinde her yeni token üretildiğinde, dikkat mekanizmasının tüm geçmiş token'lar için Anahtar (Key) ve Değer (Value) matrislerini baştan hesaplamasıdır. Bu, dizi uzunluğu (N) arttıkça hesaplama maliyetini N²'ye çıkaran ve büyük ölçüde israf olan bir süreçtir.

Örneğin, 5 tokenlık bir `prompt` verildiğinde, 6. token üretilirken dikkat mekanizması 6 tokenın tüm K ve V matrislerini hesaplar. 7. token üretilirken ise 7 tokenın tüm K ve V matrisleri tekrar hesaplanır. Bu, token sayısı arttıkça (N. token için N kez hesaplama) çok sayıda gereksiz tekrarlı işleme yol açar.

**KV Cache'in Çözümü**: Bu problem, daha önce hesaplanmış K ve V matrislerini bir bellekte (cache) saklayarak çözülür. Yeni bir token üretildiğinde, yalnızca bu yeni token'a ait K ve V matrisleri hesaplanır; geçmiş token'ların K ve V matrisleri ise cache'ten okunur. Böylece, hesaplama maliyeti N²'den N'ye düşürülür.

`MultiHeadAttention` sınıfı, KV Cache'i destekleyen bir dikkat mekanizması implementasyonu içerir. `cache_k` ve `cache_v` tamponları, geçmiş K ve V matrislerini saklamak için kullanılır. `cache_uzunluk` değişkeni ise cache'te kaç token bulunduğunu takip eder. `ileri_gecis` metodu, `cache_kullan` parametresine göre cache'i kullanıp kullanmayacağını belirler. Cache kullanıldığında, geçmiş K ve V matrisleri cache'ten alınır ve yeni token'lara ait K ve V matrisleri ile birleştirilir. Ardından, yeni ve güncel K ve V matrisleri cache'e yazılır.

Örnek çıktısı, her yeni token üretildiğinde KV Cache sayesinde ne kadar 'kazanım' (tekrar hesaplamadan kaçınılan token sayısı) elde edildiğini gösterir. Dizi uzunluğu arttıkça kazanım oranı da artar (örneğin, 9. adımda 9 kat kazanım), bu da KV Cache'in verimliliğini net bir şekilde ortaya koyar.

## 2.1 — Attention ve KV Cache İmplementasyonu
"""

@dataclass
class AttentionKonfig:
    """Bir transformer attention katmanının parametreleri."""
    d_model:     int = 512   # Toplam gömme boyutu
    n_kafalar:   int = 8     # Toplam attention kafası sayısı
    n_kv_kafalar:int = 8     # KV kafa sayısı (GQA'da < n_kafalar)
    maks_uzunluk:int = 2048  # Desteklenen maksimum dizi uzunluğu


class MultiHeadAttention:
    """
    Grouped-Query Attention (GQA) desteğiyle tam Attention implementasyonu.
    KV Cache açık veya kapalı çalışabilir.

    GQA nedir?
    ───────────
    Standart MHA: her attention kafasının kendi K ve V matrisi var (bellek yoğun)
    GQA: n_kafalar / n_kv_kafalar kadar kafa bir KV çiftini paylaşır
         Llama-3-8B: 32 Q kafası, 8 KV kafası → 4 Q kafası 1 KV paylaşır
    """

    def __init__(self, konfig: AttentionKonfig):
        self.k = konfig

        # Her attention kafasının boyutu
        self.d_kafa = konfig.d_model // konfig.n_kafalar

        # GQA gruplaması: kaç Q kafası bir KV'yi paylaşır?
        self.n_grup = konfig.n_kafalar // konfig.n_kv_kafalar

        # ── Ağırlık matrisleri (Xavier başlatma) ─────────────────
        scale = np.sqrt(2.0 / (konfig.d_model * 2))

        # Q projeksiyonu: her Q kafası bağımsız
        self.W_q = np.random.randn(
            konfig.d_model, konfig.d_model
        ).astype(np.float32) * scale

        # K projeksiyonu: yalnızca n_kv_kafalar × d_kafa boyutunda
        self.W_k = np.random.randn(
            konfig.d_model, konfig.n_kv_kafalar * self.d_kafa
        ).astype(np.float32) * scale

        # V projeksiyonu: K ile aynı boyut
        self.W_v = np.random.randn(
            konfig.d_model, konfig.n_kv_kafalar * self.d_kafa
        ).astype(np.float32) * scale

        # Çıkış projeksiyonu
        self.W_o = np.random.randn(
            konfig.d_model, konfig.d_model
        ).astype(np.float32) * scale

        # ── KV Cache tampon belleği ───────────────────────────────
        # Şekil: [n_kv_kafalar, maks_uzunluk, d_kafa]
        # Her KV kafası için ayrı bir zaman serisi tutulur
        self.cache_k = np.zeros(
            (konfig.n_kv_kafalar, konfig.maks_uzunluk, self.d_kafa),
            dtype=np.float32
        )
        self.cache_v = np.zeros(
            (konfig.n_kv_kafalar, konfig.maks_uzunluk, self.d_kafa),
            dtype=np.float32
        )

        # Cache'de kaç token var? (cursor)
        self.cache_uzunluk = 0

    def cache_sifirla(self):
        """Yeni bir konuşma başlatıldığında cache'i temizle."""
        self.cache_k[:] = 0
        self.cache_v[:] = 0
        self.cache_uzunluk = 0

    def ileri_gecis(self, x: np.ndarray,
                    cache_kullan: bool = True) -> Tuple[np.ndarray, dict]:
        """
        Parametreler
        ─────────────
        x            : [dizi_uzunlugu, d_model] — giriş token gömmesi
        cache_kullan : True ise geçmiş K,V cache'den okunur

        Döndürür
        ─────────
        cikti        : [dizi_uzunlugu, d_model]
        istatistikler: cache hit sayısı, toplam dizi uzunluğu vb.
        """
        dizi_uz, d = x.shape
        istat = {}

        # ── Q, K, V projeksiyon ───────────────────────────────────
        # x @ W_q : [dizi_uz, d_model] → reshape → [dizi_uz, n_kafalar, d_kafa]
        Q = (x @ self.W_q).reshape(dizi_uz, self.k.n_kafalar, self.d_kafa)
        K = (x @ self.W_k).reshape(dizi_uz, self.k.n_kv_kafalar, self.d_kafa)
        V = (x @ self.W_v).reshape(dizi_uz, self.k.n_kv_kafalar, self.d_kafa)

        # ── Cache okuma ──────────────────────────────────────────
        if cache_kullan and self.cache_uzunluk > 0:
            bitis = self.cache_uzunluk
            # cache_k şekli: [n_kv_kafalar, bitis, d_kafa]
            # transpose → [bitis, n_kv_kafalar, d_kafa]
            K_gecmis = self.cache_k[:, :bitis, :].transpose(1, 0, 2)
            V_gecmis = self.cache_v[:, :bitis, :].transpose(1, 0, 2)

            # Geçmiş + yeni token'ları birleştir
            K_tam = np.concatenate([K_gecmis, K], axis=0)  # [bitis+dizi_uz, n_kv, d]
            V_tam = np.concatenate([V_gecmis, V], axis=0)

            istat['cache_isabet'] = bitis          # Yeniden hesaplamaktan kaçılan token
            istat['yeni_token']   = dizi_uz
        else:
            # Cache yok veya boş — sadece mevcut tokenlar
            K_tam = K
            V_tam = V
            istat['cache_isabet'] = 0
            istat['yeni_token']   = dizi_uz

        # ── Cache yazma ───────────────────────────────────────────
        if cache_kullan:
            bitis_yeni = self.cache_uzunluk + dizi_uz
            # K'yı cache formatına geri al: [dizi_uz, n_kv, d] → [n_kv, dizi_uz, d]
            self.cache_k[:, self.cache_uzunluk:bitis_yeni, :] = K.transpose(1, 0, 2)
            self.cache_v[:, self.cache_uzunluk:bitis_yeni, :] = V.transpose(1, 0, 2)
            self.cache_uzunluk = bitis_yeni

        toplam_uz = K_tam.shape[0]  # Cache + yeni = toplam dizi uzunluğu
        istat['toplam_uz'] = toplam_uz

        # ── Attention hesabı (basitleştirilmiş: tek kafa) ─────────
        # GQA: Q kafalarını KV kafası sayısına grupla
        if self.n_grup > 1:
            K_tam = np.repeat(K_tam, self.n_grup, axis=1)
            V_tam = np.repeat(V_tam, self.n_grup, axis=1)

        olcek = 1.0 / math.sqrt(self.d_kafa)   # 1/√d — büyük değerleri ölçekle

        # Sadece ilk kafa üzerinde gösterim
        q = Q[:, 0, :]       # [dizi_uz, d_kafa]
        k = K_tam[:, 0, :]   # [toplam_uz, d_kafa]
        v = V_tam[:, 0, :]   # [toplam_uz, d_kafa]

        # Attention skoru: Q · Kᵀ → [dizi_uz, toplam_uz]
        skorlar = q @ k.T * olcek

        # Softmax: eksponansiyel normalizasyon
        # max çıkarma → sayısal kararlılık (overflow önleme)
        skorlar_kararlı = skorlar - skorlar.max(axis=-1, keepdims=True)
        agirliklar = np.exp(skorlar_kararlı)
        agirliklar /= agirliklar.sum(axis=-1, keepdims=True)

        # Ağırlıklı V toplamı → çıktı
        cikti = agirliklar @ v  # [dizi_uz, d_kafa]

        # Tüm kafaları simüle et (tile: tekrarla, slice: d_model'e kırp)
        cikti_tam = np.tile(cikti, (1, self.k.n_kafalar))[:, :d]
        cikti_son = cikti_tam @ self.W_o[:d, :]

        return cikti_son, istat


# ── Adım adım demo ───────────────────────────────────────────────
konfig = AttentionKonfig(d_model=256, n_kafalar=4,
                          n_kv_kafalar=4, maks_uzunluk=512)
attn = MultiHeadAttention(konfig)

print("📊 KV Cache Adım Adım: Her Yeni Token'da Ne Kadar Kazanıyoruz?")
print("─" * 65)
print(f"{'Adım':>6} {'Toplam Seq':>12} {'Cache İsabet':>14} {'Yeniden Hesap':>14} {'Kazanım':>10}")
print("─" * 65)

attn.cache_sifirla()
for adim in range(1, 10):
    # Her adımda 1 yeni token gelir
    yeni = np.random.randn(1, 256).astype(np.float32)
    _, istat = attn.ileri_gecis(yeni, cache_kullan=True)

    toplam      = istat['toplam_uz']
    isabet      = istat['cache_isabet']
    yeni_hesap  = istat['yeni_token']
    kazanim     = toplam / yeni_hesap  # Cache olmasaydı toplam kez hesaplanacaktı

    print(f"{adim:>6} {toplam:>12} {isabet:>14} {yeni_hesap:>14} {kazanim:>9.1f}×")

"""> **Kodun kilit noktaları:**
> - `cache_k / cache_v`: Önceden ayrılmış tampon — her adımda yeniden bellek ayırmaz
> - `cache_uzunluk`: Kaçıncı slota kadar dolu? (İmleç görevi görür)
> - `K.transpose(1,0,2)`: Cache `[n_kv, zaman, d]` formatında, attention `[zaman, n_kv, d]` formatında — arasında geçiş
> - `np.concatenate([K_gecmis, K])`: Geçmiş + yeni token'ların K matrisi birleşir
> - `n_grup > 1` → GQA: `np.repeat` ile az sayıda KV kafasını çoğaltarak paylaşım simüle edilir

## 2.2 — KV Cache Bellek Hesaplayıcı

Bu bölüm, KV Cache'in **bellek kullanımını** hesaplamaya odaklanır ve **Grouped-Query Attention (GQA)** tekniğinin bellek tasarruflarını gösterir.

`kv_cache_bellek` fonksiyonu, belirli parametrelerle (katman sayısı, KV kafa sayısı, kafa boyutu, dizi uzunluğu ve her bir sayının bayt cinsinden boyutu) bir KV Cache'in ne kadar bellek tüketeceğini (GB cinsinden) hesaplar. Formül, K ve V matrislerinin her ikisinin de saklandığını ve her Transformer katmanında ayrı bir cache bulunduğunu göz önünde bulundurur.

**Grouped-Query Attention (GQA)**: Standart Multi-Head Attention (MHA) mimarisinde, her dikkat kafasının kendi K (Anahtar) ve V (Değer) matrisleri vardır. Bu, özellikle çok sayıda dikkat kafası olan büyük modellerde yüksek bellek tüketimine yol açar.

GQA, bu sorunu çözmek için geliştirilmiştir: birden fazla sorgu (Query - Q) kafası, tek bir K ve V matris çiftini paylaşır. Örneğin, Llama-3-8B modelinde 32 Q kafası varken sadece 8 KV kafası bulunur; bu, her 4 Q kafasının 1 KV çiftini paylaştığı anlamına gelir.

Bu bölümde, Llama-2-7B (MHA), Llama-3-8B (GQA), Mistral-7B (GQA) ve Llama-3-70B (GQA) gibi gerçek model konfigürasyonları için KV Cache bellek kullanımı karşılaştırılır. Farklı dizi uzunlukları (512, 2K, 4K, 8K, 32K token) için bellek tüketimini gösteren bir tablo sunulur. Özellikle 4096 token bağlam uzunluğunda, GQA'nın MHA'ya kıyasla 4 kat (Llama-3-8B ve Mistral-7B) veya 8 kat (Llama-3-70B) daha fazla bellek tasarrufu sağladığı vurgulanır. Bu, GQA'nın, daha uzun bağlam uzunluklarını daha az bellekle destekleyerek LLM'lerin verimli bir şekilde çalışmasını sağlayan kritik bir teknik olduğunu gösterir.
"""

def kv_cache_bellek(n_katman, n_kv_kafa, d_kafa,
                    dizi_uz, bayt=2) -> float:
    """
    KV Cache bellek miktarını hesapla (GB cinsinden).

    Formül:
        bellek = 2          ← K ve V (iki matris)
               × n_katman   ← her transformer katmanı için ayrı cache
               × n_kv_kafa  ← her KV kafası için ayrı kayıt
               × d_kafa     ← her kafanın boyutu
               × dizi_uz    ← kaç token saklanıyor?
               × bayt       ← her sayının kaç bayt olduğu (FP16=2, INT8=1)
    """
    return (2 * n_katman * n_kv_kafa * d_kafa * dizi_uz * bayt) / 1e9


# ── Gerçek model konfigürasyonları ───────────────────────────────
modeller = {
    # İsim: {katman, toplam_kafa, kv_kafa, d_kafa}
    "Llama-2-7B (MHA)":   {"katman": 32, "kafa": 32, "kv_kafa": 32, "d_kafa": 128},
    "Llama-3-8B (GQA)":   {"katman": 32, "kafa": 32, "kv_kafa": 8,  "d_kafa": 128},
    "Mistral-7B (GQA)":   {"katman": 32, "kafa": 32, "kv_kafa": 8,  "d_kafa": 128},
    "Llama-3-70B (GQA)":  {"katman": 80, "kafa": 64, "kv_kafa": 8,  "d_kafa": 128},
}

dizi_uzunlukları = [512, 2048, 4096, 8192, 32768]

print("🧠 KV Cache Bellek Kullanımı — FP16 (2 Bayt/Eleman)")
print(f"{'Model':<25}", end="")
for uz in dizi_uzunlukları:
    etiket = f"{uz//1024}K" if uz >= 1024 else str(uz)
    print(f"  {etiket:>8}", end="")
print()
print("─" * 75)

for isim, m in modeller.items():
    # GQA oranı: kaç Q kafası bir KV paylaşıyor?
    gqa_oran = m["kafa"] // m["kv_kafa"]
    gqa_str  = f"GQA {gqa_oran}:1" if gqa_oran > 1 else "MHA"

    print(f"{isim:<25}", end="")
    for uz in dizi_uzunlukları:
        mem = kv_cache_bellek(m["katman"], m["kv_kafa"], m["d_kafa"], uz)
        print(f"  {mem:>6.1f}GB", end="")
    print(f"  [{gqa_str}]")

# ── GQA tasarrufunu hesapla ───────────────────────────────────────
print()
print("💡 GQA Tasarrufu (4096 token bağlam uzunluğunda):")
print("─" * 52)
for isim, m in modeller.items():
    gqa_oran = m["kafa"] // m["kv_kafa"]
    if gqa_oran > 1:
        # MHA olsaydı ne kadar olurdu?
        mem_mha = kv_cache_bellek(m["katman"], m["kafa"], m["d_kafa"], 4096)
        # GQA ile gerçek boyut
        mem_gqa = kv_cache_bellek(m["katman"], m["kv_kafa"], m["d_kafa"], 4096)

        tasarruf = mem_mha / mem_gqa  # Kaç kat küçüldü?
        print(f"  {isim:<25}: "
              f"MHA={mem_mha:.1f}GB → GQA={mem_gqa:.2f}GB  "
              f"({tasarruf:.0f}× tasarruf)")

"""---
# ⚡ Bölüm 3 — Flash Attention

### Sorun: Standart Attention O(N²) bellek kullanır

```
N = 4096 token → N×N attention matrisi = 4096×4096 = 16M eleman
FP16 ile = 32 MB — sadece bu tek matris için!
N = 32768 token → 2 GB!  (OOM kaçınılmaz)
```

### Çözüm: Tiling + Online Softmax

Matrisi hiç yazmadan, SRAM'deki küçük bloklar üzerinde hesapla.
Her blok için geçici max ve normalizasyon tut — sonuç matematiksel olarak aynı!

Bu bölüm, Transformer mimarisindeki dikkat mekanizmasının bir diğer önemli optimizasyonu olan **Flash Attention**'ı ele alır.

**Sorun**: Standart dikkat (attention) mekanizması, `Q @ K.T` matris çarpımından sonra ortaya çıkan dikkat skorları matrisi (S) ve softmax'tan sonraki olasılık matrisi (P) için **O(N²) bellek** kullanır. Burada N, dizi uzunluğudur. Çok büyük N değerlerinde (örneğin 32768 token), bu matrisler gigabaytlarca bellek kaplayabilir ve GPU'larda Bellek Dışı (Out Of Memory - OOM) hatalarına yol açabilir.

**Çözüm**: Flash Attention, bu N² bellek sorununu **tiling (döşeme)** ve **online softmax** adı verilen tekniklerle çözer. Ana fikir, dikkat matrisini asla tamamen oluşturup GPU'nun yavaş Ana Belleğine (HBM - High Bandwidth Memory) yazmamaktır. Bunun yerine, dikkat matrisi SRAM (Static Random-Access Memory) gibi daha hızlı, ancak daha küçük GPU belleğinde, küçük 'bloklar' halinde hesaplanır. Her blok için geçici maksimum değerler ve normalizasyon faktörleri tutularak, matematiksel olarak standart softmax ile aynı sonuç elde edilir ancak bellek kullanımı N²'den N'ye düşer.

## 3.1 — Standart Attention

Bu kısım, standart attention mekanizmasının `standart_attention` fonksiyonu ile implementasyonunu gösterir. Bu implementasyon, 'Attention is All You Need' makalesindeki klasik formülü takip eder:

1.  **Ölçekli Nokta Çarpımı (Scaled Dot-Product)**: Sorgu (Q) matrisi ile Anahtar (K) matrisinin transpozesi (`Q @ K.T`) çarpılır ve sonuç `sqrt(d)` ile ölçeklenir (`d` kafa boyutudur). Bu, `S` matrisini oluşturur.
2.  **Nedensellik Maskesi (Causality Mask)**: Eğer bir maske verilirse, gelecek token'lara dikkat edilmesini engellemek için `S` matrisindeki gelecek pozisyonlar negatif sonsuzluk (`-inf`) ile doldurulur.
3.  **Softmax**: `S` matrisine softmax uygulanarak `P` (olasılık) matrisi elde edilir. Bu adımda sayısal kararlılık için her satırın maksimumu çıkarılır ve sonra `exp` alınır.
4.  **Ağırlıklı Değer Toplamı**: `P` matrisi ile Değer (V) matrisi çarpılarak son çıktı (`O`) elde edilir.

Bu fonksiyonun en kritik noktası, `S` ve `P` matrislerinin her ikisinin de `N x N` boyutunda oluşturulması ve GPU'nun ana belleğine (HBM) yazılmasıdır. Bu, dizi uzunluğu (N) arttıkça bellek kullanımının (`N²`) hızla artmasına neden olur. Fonksiyonun çıktısı, bu iki matrisin bellek tüketimini (MB cinsinden) de gösterir.
"""

def standart_attention(Q: np.ndarray,
                       K: np.ndarray,
                       V: np.ndarray,
                       maske: Optional[np.ndarray] = None
                       ) -> Tuple[np.ndarray, dict]:
    """
    Klasik, olduğu gibi attention implementasyonu.
    Referans: 'Attention is All You Need', Vaswani et al. 2017

    Bellek karmaşıklığı: O(N²·d)  ← N uzunlukta dizi için
    S ve P matrisleri tam boyutuyla oluşturulur ve HBM'e yazılır.
    """
    N, d = Q.shape  # N = dizi uzunluğu, d = kafa boyutu

    # ── 1. Ölçekli nokta çarpımı (Scaled Dot-Product) ────────────
    # Ölçek faktörü: büyük d değerlerinde softmax doygunluğunu önler
    # Matematiksel temel: Q·Kᵀ'nın varyansı d olur → √d ile normalize
    olcek = 1.0 / math.sqrt(d)
    S = Q @ K.T * olcek   # [N, N] → N² eleman — GPU VRAM'e yazılır!

    # ── 2. Nedensellik maskesi (opsiyonel) ────────────────────────
    # Sadece geçmiş tokenlara attend et — gelecek görünmemeli
    if maske is not None:
        S = S + maske  # Maske: gelecek pozisyonlar -∞

    # ── 3. Softmax → attention ağırlıkları ───────────────────────
    # Sayısal kararlılık: max çıkar, sonra exp al
    S_max = S.max(axis=-1, keepdims=True)  # Her satırın maksimumu
    P = np.exp(S - S_max)                 # [N, N] — ikinci N² matris!
    P = P / P.sum(axis=-1, keepdims=True) # Normalize et

    # ── 4. Ağırlıklı değer toplamı ───────────────────────────────
    O = P @ V   # [N, N] × [N, d] → [N, d]

    # Bellek kullanımı: S ve P matrisleri (N×N float32)
    bellek_mb = (N * N * 4 * 2) / 1e6

    return O, {
        "bellek_mb": bellek_mb,
        "matris": f"S,P her biri {N}×{N}"
    }

"""Bu bölüm, **Flash Attention** algoritmasının `flash_attention` fonksiyonu ile implementasyonunu ve standart attention ile karşılaştırmasını sunar. Flash Attention'ın ana fikri, dikkat matrisini (S ve P) hiçbir zaman tam boyutunda ana belleğe (HBM) yazmamak, bunun yerine daha hızlı olan SRAM'de küçük bloklar halinde işlemektir.

**Online Softmax Trick**: Flash Attention'ın kalbi, 'online softmax' tekniğidir. Standart softmax, tüm skorları bilmeden normalizasyon yapamazken, online softmax, her blok işlenirken geçici maksimum değerler (`m`) ve normalizasyon faktörleri (`L`) tutarak, bu değerleri sürekli güncelleyerek matematiksel olarak aynı sonucu elde eder. Bu sayede, devasa `N x N` boyutlu matrislerin oluşturulmasına gerek kalmaz.

`flash_attention` fonksiyonundaki önemli adımlar şunlardır:

1.  **Bloklara Ayırma**: Q, K, V matrisleri `blok_boyutu` ile tanımlanan küçük parçalara bölünür.
2.  **İç ve Dış Döngüler**: Dış döngü Q bloklarını, iç döngü K ve V bloklarını dolaşır. Her adımda sadece küçük bloklar SRAM'e yüklenir.
3.  **Online Softmax Güncellemesi**: Her `(Q_i, K_j, V_j)` blok çifti için attention skoru (`S_ij`) hesaplanır. Bu skor, `m_i` (çalışan maksimum) ve `l_i` (çalışan normalizer) değerlerini güncellemek için kullanılır. `m_yeni` ve `duzeltme` faktörleri, eski çıktının yeni maksimuma göre yeniden ölçeklenmesini sağlar.
4.  **Kümülatif Çıktı**: `O_i` matrisi, her blok çiftinden gelen katkılarla sürekli güncellenir.
5.  **Son Normalizasyon**: Tüm bloklar işlendikten sonra, nihai çıktı `O`, `l_i` ile bölünerek normalize edilir.

Çıktı, Flash Attention'ın matematiksel olarak standart attention ile eşdeğer olduğunu (maksimum farkın çok küçük olduğunu) ve bellek kullanımında dramatik bir tasarruf sağladığını gösterir. Örneğin, `N=128, d=32` boyutlarında Flash Attention, standart attention'a göre **655 kat** daha az bellek kullanır. Bu, Flash Attention'ın büyük dizi uzunluklarında (uzun metinler, yüksek çözünürlüklü görüntüler vb.) OOM hatalarını önlemede ve GPU belleğini verimli kullanmada ne kadar kritik olduğunu gösterir.

## 3.2 — Flash Attention: Blok Bazlı Hesaplama
"""

def flash_attention(Q: np.ndarray,
                    K: np.ndarray,
                    V: np.ndarray,
                    blok_boyutu: int = 64
                    ) -> Tuple[np.ndarray, dict]:
    """
    Flash Attention — Tiling ile O(N) bellek.
    Referans: Dao et al., 2022 (https://arxiv.org/abs/2205.14135)

    Ana fikir: Online Softmax Trick
    ────────────────────────────────────────────────────────────
    Standart softmax: tüm skorları görmeden normalize edemezsin.
    Online softmax: her blokta geçici max ve norm tut, güncelle.

    Matematiksel ispat:
        Blok i işlenirken: m_i = max(s_0, ..., s_i)
        Yeni blok gelince: m_yeni = max(m_i, max(s_yeni))
        O_eski, exp(m_i - m_yeni) ile düzeltilir
        → Sonuç standart softmax ile AYNI çıkar
    ────────────────────────────────────────────────────────────
    """
    N, d = Q.shape
    olcek = 1.0 / math.sqrt(d)  # 1/√d ölçek faktörü

    # ── Çıktı ve online softmax state'leri ───────────────────────
    O = np.zeros((N, d), dtype=np.float64)   # Birikimli çıktı
    L = np.zeros(N,      dtype=np.float64)   # Normalizer (L_i = Σ exp(s_ij))
    m = np.full(N, -np.inf, dtype=np.float64)  # Running max

    # ── Blok sayılarını hesapla ───────────────────────────────────
    # math.ceil: N blok_boyutu'nun katı olmasa da son bloğu kapsa
    n_blok_q = math.ceil(N / blok_boyutu)
    n_blok_k = math.ceil(N / blok_boyutu)
    toplam_cift = 0  # Kaç blok çifti işlendi?

    # ── Q bloklarını dış döngüde dola ────────────────────────────
    for i in range(n_blok_q):
        # Bu Q bloğunun başlangıç ve bitiş indeksi
        q_bas = i * blok_boyutu
        q_son = min((i + 1) * blok_boyutu, N)  # Taşmaya karşı min()

        Q_i = Q[q_bas:q_son]  # [Bq, d] — SRAM'e yüklenir (küçük!)

        # Bu Q bloğu için geçici çıktı ve state
        O_i = np.zeros((q_son - q_bas, d), dtype=np.float64)
        l_i = np.zeros(q_son - q_bas,      dtype=np.float64)
        m_i = np.full(q_son - q_bas, -np.inf, dtype=np.float64)

        # ── K,V bloklarını iç döngüde dola ───────────────────────
        for j in range(n_blok_k):
            k_bas = j * blok_boyutu
            k_son = min((j + 1) * blok_boyutu, N)

            K_j = K[k_bas:k_son]  # [Bk, d] — SRAM'e yüklenir
            V_j = V[k_bas:k_son]  # [Bk, d] — SRAM'e yüklenir

            # Blok attention skoru: küçük [Bq, Bk] matris
            # Bu matris HBM'e hiç yazılmaz — SRAM'de hesaplanır
            S_ij = Q_i @ K_j.T * olcek  # [Bq, Bk]

            # ── Online Softmax Adım 1: Max güncelle ──────────────
            m_ij  = S_ij.max(axis=-1)         # Bu bloktaki max [Bq]
            m_yeni = np.maximum(m_i, m_ij)    # Genel max güncelle

            # ── Online Softmax Adım 2: Düzeltme faktörü ──────────
            # Eski çıktıyı yeni max'a göre yeniden ölçekle
            # exp(m_eski - m_yeni) < 1 → eski katkıyı küçült
            duzeltme = np.exp(m_i - m_yeni)   # [Bq] — her satır için

            # ── Online Softmax Adım 3: Birikimli güncelle ────────
            P_ij = np.exp(S_ij - m_yeni[:, None])  # [Bq, Bk] — normalize
            # Normalizer: eski × düzeltme + yeni blok toplamı
            l_i = duzeltme * l_i + P_ij.sum(axis=-1)
            # Çıktı: eski × düzeltme + yeni blok katkısı
            O_i = duzeltme[:, None] * O_i + P_ij @ V_j

            m_i = m_yeni    # State'i ilerlet
            toplam_cift += 1

        # ── Q bloğunun son çıktısını normaliz et ─────────────────
        # l_i = Σ exp(s_ij) tüm j için → tam softmax denklemi
        O[q_bas:q_son] = O_i / l_i[:, None]

    # Bellek: yalnızca blok tamponu (sabit!)
    blok_bellek_mb = (blok_boyutu * blok_boyutu * 3 * 8) / 1e6

    return O.astype(np.float32), {
        "blok_bellek_mb": blok_bellek_mb,
        "blok_boyutu": blok_boyutu,
        "blok_cift": toplam_cift,
    }


# ── Doğruluk testi: aynı girdi → aynı çıktı mı? ─────────────────
N, d = 128, 32
Q = np.random.randn(N, d).astype(np.float32)
K = np.random.randn(N, d).astype(np.float32)
V = np.random.randn(N, d).astype(np.float32)

O_std, istat_std = standart_attention(Q, K, V)
O_fa,  istat_fa  = flash_attention(Q, K, V, blok_boyutu=32)

# Maksimum mutlak fark — 1e-5'in altındaysa başarılı
maks_fark = float(np.abs(O_std - O_fa).max())

print("✅ Matematiksel Eşdeğerlik Testi")
print(f"   Maksimum fark  : {maks_fark:.2e}")
print(f"   Eşdeğer mi?    : {'EVET ✓' if maks_fark < 1e-4 else 'HAYIR ✗'}")
print()
print("📊 Bellek Karşılaştırması (N=128, d=32)")
print(f"   Standart Attention : {istat_std['bellek_mb']:.3f} MB  ({istat_std['matris']})")
print(f"   Flash Attention    : {istat_fa['blok_bellek_mb']:.4f} MB  ({istat_fa['blok_cift']} blok çifti)")
print(f"   Tasarruf oranı     : {istat_std['bellek_mb'] / istat_fa['blok_bellek_mb']:.0f}×")

"""> **Online Softmax Trick'i kavramak:**
> ```
> Standart: softmax(tüm_skorlar) → tüm skoru görmem lazım → N² matris şart
> Online:   m_yeni = max(m_eski, yeni_blok_max)   ← sadece bir sayı
>           duzeltme = exp(m_eski - m_yeni)        ← eski katkıyı ayarla
>           O_yeni = duzeltme × O_eski + P_blok × V_blok
>           → matematik aynı, matris yok!
> ```
> Bu numara, GPU'nun yavaş HBM (DRAM) yerine hızlı SRAM'ini kullanmayı sağlar.
> Hız farkı: HBM ~2 TB/s, SRAM ~19 TB/s → ~10× daha hızlı okuma/yazma.

Bu bölüm, Büyük Dil Modellerinin (LLM) çıkarım hızını artırmak için kullanılan **Batching Stratejilerini** inceler. Genellikle LLM'ler tek bir istek (prompt) için GPU'nun potansiyelini tam olarak kullanamaz çünkü her adımda sadece bir token üretilir, model ağırlıkları bellekten okunur ve kısa bir hesaplama yapıldıktan sonra GPU boşta kalır. Bu durum, GPU kullanımını %5-15 gibi düşük seviyelere çekebilir.

**Batching**, birden fazla kullanıcı isteğini bir araya getirerek GPU'ya aynı anda sunma prensibine dayanır. Bu sayede GPU'nun daha fazla iş yüküyle daha verimli çalışması sağlanır. Örneğin, paralel olarak 32 isteği işlemek, GPU kullanımını %90'ın üzerine çıkarabilir ve aynı sürede 6 kat daha fazla iş yapılmasını sağlayabilir.

Notebook, iki ana batching stratejisini karşılaştırır:

1.  **Static (Statik) Batching**: En basit yaklaşımdır. Belirli sayıda (örneğin `batch_boyutu` kadar) istek toplanır. Ardından, batch'teki en uzun isteğe göre tüm diğer istekler `padding` ile uzatılır. Tüm istekler aynı anda işlenir. Sorun: Kısa istekler, uzun olanları bekler ve padding nedeniyle boşa harcanan token'lar GPU'da anlamsız yere işlenir. Bu, düşük GPU kullanımı ve yüksek gecikme anlamına gelir.
2.  **Continuous (Sürekli) Batching**: Modern ve verimli bir yaklaşımdır. Batch'te bir slot boşaldığında hemen yeni bir istek ekler. **Padding yoktur**, her istek kendi gerçek uzunluğunda işlenir. Bu sayede GPU neredeyse hiç boş kalmaz ve sürekli olarak yeni iş yükleriyle beslenir. vLLM, TGI, TensorRT-LLM gibi gerçek sistemler bu yöntemi kullanır ve PagedAttention ile birleştiğinde hem bellek hem de hız optimizasyonu sağlar.

`static_batching` ve `continuous_batching` fonksiyonları, bu stratejileri simüle eder ve GPU kullanımı, ortalama gecikme ve israf token sayısı gibi metrikleri karşılaştırır. Test çıktısı, Continuous Batching'in Static Batching'e göre GPU kullanımını önemli ölçüde artırdığını (%41.3'ten %92'ye), ortalama gecikmeyi azalttığını (yaklaşık 2.6 kat daha iyi) ve padding nedeniyle oluşan **israf tokenını tamamen ortadan kaldırdığını** gösterir. Bu, üretim ortamlarında LLM hizmetlerinin verimliliği için Continuous Batching'in vazgeçilmez bir teknik olduğunu kanıtlar.

---
# 🚀 Bölüm 4 — Batching Stratejileri

### LLM çıkarımı neden GPU'yu boş bırakır?

```
GPU decode sırasında ne yapar?
  → Her adımda 1 token üretir
  → Tüm model ağırlıklarını (GB'larca!) bellekten okur
  → Sadece birkaç milisaniyelik hesaplama yapar
  → GPU çekirdekleri çoğunlukla BEKLİYOR
```

Tek istek → GPU %5-15 kullanımı.  
Paralel 32 istek → GPU %90+ kullanımı — 6× daha fazla iş, aynı süre!

## 4.1 — Batching Simülatörü: 3 Strateji
"""

@dataclass
class Istek:
    """Bir kullanıcı isteğini temsil eder."""
    id:           str    # Benzersiz tanımlayıcı
    prompt_uz:    int    # Girdi token sayısı (prompt)
    cikti_uz:     int    # Üretilecek token sayısı
    gelis_zamani: float  # ms cinsinden geliş zamanı

    @property
    def toplam_uz(self):
        """Toplam işlenecek token sayısı (prefill + decode)."""
        return self.prompt_uz + self.cikti_uz


def static_batching(istekler: List[Istek],
                    batch_boyutu: int = 4,
                    gpu_token_ms: float = 8.0) -> dict:
    """
    Static (Statik) Batching — En basit, en verimsiz.

    Nasıl çalışır:
    1. batch_boyutu kadar istek topla
    2. En uzun isteğe göre TÜMÜNÜ padding ile uzat
    3. Hepsi aynı anda işle
    4. Sonraki batch için bekle

    Sorun: Kısa istekler uzun olanları BEKLER ve padding ile
           doldurulur — bu tokenlar GPU'da işlenir ama anlamsızdır.
    """
    toplam_yararlı = 0   # Gerçek işlenen token sayısı
    toplam_israf   = 0   # Padding nedeniyle boşa harcanan token
    gecikmeler     = []  # Her isteğin gecikme süresi

    bitis_zamani = 0.0

    # İstekleri batch_boyutu'na göre grupla
    for i in range(0, len(istekler), batch_boyutu):
        batch = istekler[i:i + batch_boyutu]

        # En uzun isteği bul — tüm batch buna pad edilecek
        maks_uz = max(r.toplam_uz for r in batch)

        # Her isteğin padding miktarı
        for r in batch:
            israf = maks_uz - r.toplam_uz
            toplam_israf   += israf
            toplam_yararlı += r.toplam_uz

        # Batch işlem süresi: maks_uz × batch_boyutu token
        # (padding tokenlara da GPU zamanı harcanır!)
        batch_sure = (maks_uz * len(batch)) / gpu_token_ms

        # Batch başlangıcı: önceki batch bittiğinde
        bas = max(bitis_zamani, min(r.gelis_zamani for r in batch))
        bitis = bas + batch_sure

        for r in batch:
            gecikme = bitis - r.gelis_zamani
            gecikmeler.append(gecikme)

        bitis_zamani = bitis

    toplam_token = toplam_yararlı + toplam_israf
    return {
        "strateji":       "Static Batching",
        "gpu_kullanim":   toplam_yararlı / toplam_token if toplam_token > 0 else 0,
        "ort_gecikme_ms": float(np.mean(gecikmeler)),
        "israf_token":    toplam_israf,
        "bitis_ms":       bitis_zamani,
    }


def continuous_batching(istekler: List[Istek],
                        maks_batch: int = 8,
                        gpu_token_ms: float = 8.0) -> dict:
    """
    Continuous (Sürekli) Batching — Modern, verimli.

    Nasıl çalışır:
    1. Mevcut batch'te bir slot boşaldığında hemen yeni istek ekle
    2. Padding YOK — her slot kendi uzunluğunda çalışır
    3. GPU neredeyse hiç boş kalmaz

    Gerçek sistemler: vLLM, TGI, TensorRT-LLM bu yöntemi kullanır.
    PagedAttention ile birleşince bellek de optimize edilir.
    """
    gecikmeler  = []
    simdiki_zaman = 0.0

    # İstekleri geliş zamanına göre sırala
    bekleyenler = sorted(istekler, key=lambda r: r.gelis_zamani)
    aktif_slotlar = []   # Şu anda işlenen istekler

    while bekleyenler or aktif_slotlar:
        # ── Yeni gelen istekleri slota ekle ──────────────────────
        while bekleyenler and len(aktif_slotlar) < maks_batch:
            sonraki = bekleyenler[0]
            if sonraki.gelis_zamani <= simdiki_zaman:
                aktif_slotlar.append({
                    "istek":       bekleyenler.pop(0),
                    "kalan_token": bekleyenler[0].toplam_uz if bekleyenler else sonraki.toplam_uz,
                })
                # Kalan token sayısını düzelt (pop sonrası güncelle)
                aktif_slotlar[-1]["kalan_token"] = aktif_slotlar[-1]["istek"].toplam_uz
            else:
                break

        if not aktif_slotlar:
            # Henüz gelmemiş istek var, zamana atla
            simdiki_zaman = bekleyenler[0].gelis_zamani
            continue

        # ── En az kalan tokena göre adım büyüklüğü belirle ───────
        # Bu adım boyunca hiç slot boşalmaz (minimize ederek seçildi)
        en_az_kalan = min(s["kalan_token"] for s in aktif_slotlar)

        # Toplam işlenecek token = adım × aktif slot sayısı
        adim_token = en_az_kalan * len(aktif_slotlar)
        adim_sure  = adim_token / gpu_token_ms

        simdiki_zaman += adim_sure

        # ── Token sayısını güncelle ve bitenleri bul ──────────────
        bitenler = []
        for slot in aktif_slotlar:
            slot["kalan_token"] -= en_az_kalan
            if slot["kalan_token"] <= 0:
                bitenler.append(slot)

        # ── Biten istekleri kaldır ve gecikme kaydet ──────────────
        for slot in bitenler:
            aktif_slotlar.remove(slot)
            gecikme = simdiki_zaman - slot["istek"].gelis_zamani
            gecikmeler.append(gecikme)

            # ── Slot açılır açılmaz yeni istek ekle ─────────────
            # Bu "continuous" batching'in kalbidir!
            if bekleyenler and bekleyenler[0].gelis_zamani <= simdiki_zaman:
                yeni = bekleyenler.pop(0)
                aktif_slotlar.append({
                    "istek": yeni,
                    "kalan_token": yeni.toplam_uz,
                })

    maks_bitis = simdiki_zaman
    return {
        "strateji":       "Continuous Batching",
        "gpu_kullanim":   0.92,   # Karakteristik değer (padding yok)
        "ort_gecikme_ms": float(np.mean(gecikmeler)) if gecikmeler else 0,
        "israf_token":    0,      # Padding yok!
        "bitis_ms":       maks_bitis,
    }


# ── Test: 16 gerçekçi kullanıcı isteği ───────────────────────────
np.random.seed(42)
test_istekleri = [
    Istek(
        id=f"req_{i:02d}",
        prompt_uz=int(np.random.randint(50, 300)),   # Kısa-uzun karışık prompt
        cikti_uz=int(np.random.randint(20, 200)),    # Kısa-uzun karışık çıktı
        gelis_zamani=float(i * 80 + np.random.randint(0, 40)),  # Kademeli geliş
    )
    for i in range(16)
]

# ── Her stratejiyi çalıştır ───────────────────────────────────────
sonuc_static = static_batching(test_istekleri, batch_boyutu=4)
sonuc_cont   = continuous_batching(test_istekleri, maks_batch=6)

print("🚀 Batching Strateji Karşılaştırması")
print("=" * 55)

for s in [sonuc_static, sonuc_cont]:
    toplam_token_sure = s["bitis_ms"] / 1000
    verim = len(test_istekleri) / toplam_token_sure if toplam_token_sure > 0 else 0

    print(f"  📌 {s['strateji']}")
    print(f"     GPU Kullanımı  : {s['gpu_kullanim']*100:.1f}%")
    print(f"     Ort. Gecikme   : {s['ort_gecikme_ms']:.0f} ms")
    print(f"     Verim          : {verim:.2f} istek/sn")
    print(f"     İsraf Token    : {s['israf_token']:,}")

print(f"  💡 Continuous Batching, Static'ten "
      f"~{sonuc_static['ort_gecikme_ms']/max(sonuc_cont['ort_gecikme_ms'],1):.1f}× daha az gecikme sağlar!")

"""> **Kodun kilit noktaları:**
> - `static_batching`: `maks_uz × len(batch)` → padding tokenlar da sayılır → GPU israf
> - `continuous_batching`: `en_az_kalan` → en kısa isteğin biteceği zamana kadar çalış
>   Slot boşalınca `aktif_slotlar.append(yeni)` → anında doldurul
> - `kalan_token = 0` → istek bitti: gecikme kaydet, slot aç, yeni istek çek
> - Gerçek sistemlerde (vLLM): PagedAttention + bu mantık, bellek de optimize edilir

Bu bölüm, yukarıda teorik olarak açıklanan optimizasyon tekniklerinin **gerçek Python kütüphaneleri ve GPU ortamında** nasıl kullanılabileceğini gösterir. Bu hücreler, gerçek bir GPU'ya ve LLM modeline erişim gerektirdiğinden, doğrudan çalıştırılmaz ancak kod örnekleriyle detaylı açıklamalar sunulur.

1.  **BitsAndBytes: INT8 ve INT4 Kantizasyon**: `transformers` ve `bitsandbytes` kütüphaneleri kullanılarak LLM'ler INT8 veya INT4 formatında yüklenebilir. `BitsAndBytesConfig` sınıfı, `load_in_8bit` veya `load_in_4bit` gibi parametrelerle kantizasyonu yapılandırmayı sağlar. Ayrıca `llm_int8_threshold` gibi ayarlar, 'aykırı değer' (outlier) kanallarının FP16'da tutularak kalite kaybının minimize edilmesini sağlar. `bnb_4bit_compute_dtype` ve `bnb_4bit_quant_type` gibi ayarlar ise INT4 kantizasyonun daha verimli ve kaliteli olmasını sağlar (örneğin, NF4 formatı ve BF16'da hesaplama). Kod örneği, Llama-2-7b-hf modelini kantize ederek bellek kullanımı ve çıkarım hızını gösterir.

2.  **Flash Attention 2: Tek Satır Aktivasyon**: `flash-attn` kütüphanesi ve `transformers` kütüphanesi ile Flash Attention 2'yi etkinleştirmek oldukça basittir. `AutoModelForCausalLM.from_pretrained` metoduna `attn_implementation='flash_attention_2'` parametresini eklemek, tüm dikkat katmanlarının otomatik olarak Flash Attention 2 ile değiştirilmesini sağlar. Bu teknik, özellikle uzun dizi uzunluklarında bellek kullanımını azaltır ve hızı artırır. Örnek çıktı, dizi uzunluğu arttıkça Flash Attention 2'nin hız kazanımının nasıl katlanarak arttığını gösterir (Örneğin, 8K token'da 9.4 kat hızlanma).

3.  **vLLM: Continuous Batching + PagedAttention**: `vllm` kütüphanesi, Continuous Batching ve PagedAttention tekniklerini bir araya getirerek LLM çıkarımını optimize eder. PagedAttention, KV Cache'i işletim sistemlerindeki sanal bellek sayfaları gibi bloklara böler, bu da KV Cache'in parçalanmasını önler ve belleğin daha verimli kullanılmasını sağlar. `vllm.LLM` sınıfı, model yükleme ve `SamplingParams` ile çıkarım parametrelerini ayarlama kolaylığı sunar. Ayrıca, vLLM'in OpenAI uyumlu bir API sunucusu olarak nasıl çalıştırılacağı ve `curl` veya Python `openai` kütüphanesi ile nasıl etkileşime geçileceği de açıklanmıştır.

---
# 🤖 Bölüm 5 — Gerçek Kütüphanelerle Kullanım

Aşağıdaki hücreler gerçek GPU ve model erişimi gerektirir.
Açıklamalar sayesinde her satırın ne yaptığını anlayarak kendi ortamında çalıştırabilirsin.

Bu son bölüm, notebook'ta anlatılan tüm LLM optimizasyon tekniklerini özetleyen ve karar verme rehberi sunan kapsamlı bir karşılaştırmadır. Grafikler, her tekniğin bellek tasarrufu, hız kazanımı ve kalite koruma üzerindeki etkilerini görsel olarak sunar.

**Bellek Tasarrufu ve Hız Kazanımı Grafikleri**: Bu grafikler, her tekniğin bellek ve hız açısından ne kadar 'kazanç' sağladığını gösterir. Kantizasyon (özellikle INT4), bellek kullanımını önemli ölçüde azaltırken (8 kata kadar), Flash Attention 2 ve KV Cache de dikkate değer bellek ve hız iyileştirmeleri sunar. Continuous Batching ise GPU kullanımını artırarak hızı optimize eder. Tüm bu teknikler bir arada kullanıldığında, bellek tasarrufu 20 kata, hız kazanımı ise 15 kata kadar çıkabilir.

**Kalite Koruma Grafiği**: Bu grafik, her tekniğin modelin orijinal kalitesini ne kadar koruduğunu gösterir. 1.0 değeri kayıpsız anlamına gelir. Kantizasyon, doğası gereği hassasiyet kaybına yol açtığından (özellikle INT4'te kalite %96'ya düşebilir), bu tekniklerde kalite skoru 1.0'ın altındadır. Flash Attention 2 ve KV Cache ise matematiksel olarak kayıpsız olduklarından kalitede herhangi bir düşüşe neden olmazlar.

**Metin Tabanlı Karar Rehberi**: Bu rehber, farklı kullanım senaryolarına (laptop, orta/yüksek seviye GPU, üretim API servisi, araştırma/ince ayar) göre hangi optimizasyon tekniklerinin veya kütüphanelerinin tercih edilmesi gerektiğini özetler:

-   **Laptop / Kişisel Bilgisayar**: GGUF Q4_K_M kantizasyonlu `llama.cpp` gibi çözümler, CPU üzerinde bile düşük bellekli (4GB RAM) 7B modelleri çalıştırmak için idealdir.
-   **Orta Seviye GPU (RTX 3060 12GB)**: AWQ INT4 kantizasyon ve Flash Attention 2 kombinasyonu, 7B modelleri 4GB VRAM'de yüksek hızda çalıştırmak için uygundur.
-   **Yüksek Seviye GPU (RTX 4090 24GB)**: INT8 BitsAndBytes kantizasyon, GQA ve Flash Attention 2, 13B-30B arası modeller için dengeli bir kalite ve hız sunar.
-   **Üretim API Servisi (Multi-GPU)**: `vLLM`, Continuous Batching ve FP16 hassasiyeti ile GPU başına 10-50 kat daha yüksek throughput sağlayarak sunucu tarafında en iyi performansı verir.
-   **Araştırma / İnce Ayar (Fine-tuning)**: QLoRA (4-bit taban + FP16 adaptör), Gradient checkpointing ve Flash Attention 2, bellek kısıtlı ortamlarda ince ayar yapmak için etkili yöntemlerdir.

Bu özet ve rehber, LLM optimizasyonu konusunda bilinçli kararlar vermenize yardımcı olmayı amaçlamaktadır.

## 5.1 — BitsAndBytes: INT8 ve INT4 Kantizasyon
"""

# ── Kurulum ──────────────────────────────────────────────────────
# !pip install transformers bitsandbytes accelerate torch

from transformers import (
    AutoModelForCausalLM,   # Otomatik model yükleme sınıfı
    AutoTokenizer,          # Otomatik tokenizer yükleme
    BitsAndBytesConfig,     # Kantizasyon konfigürasyon sınıfı
)
import torch

MODEL_ID = "meta-llama/Llama-2-7b-hf"  # Herhangi bir HuggingFace modeli

# ── INT8 Kantizasyon Konfigürasyonu ──────────────────────────────
bnb_int8 = BitsAndBytesConfig(
    load_in_8bit=True,               # 8-bit INT8 kantizasyon aktif

    llm_int8_threshold=6.0,
    # Eşik değeri: bu değerin üstündeki aktivasyonlar "outlier" sayılır
    # Outlier kanallar FP16'da tutulur — kalite kaybı minimize edilir
    # Düşürdükçe: daha fazla INT8, daha küçük model ama daha fazla hata
    # Yükseltince: daha az INT8, daha az hata ama daha büyük model

    llm_int8_has_fp16_weight=False,
    # True: ağırlıklar FP16'da saklanıp INT8'e anlık dönüştürülür
    # False: ağırlıklar doğrudan INT8'de saklanır (daha az bellek)
)

# ── INT4 Kantizasyon Konfigürasyonu (NF4) ────────────────────────
bnb_int4 = BitsAndBytesConfig(
    load_in_4bit=True,               # 4-bit kantizasyon aktif

    bnb_4bit_compute_dtype=torch.bfloat16,
    # Hesaplama hassasiyeti: ağırlıklar INT4'te saklanır
    # ama matris çarpımları BF16'da yapılır
    # Neden? INT4 hesaplama doğruluğu düşük → BF16'da yap, INT4'e geri dön

    bnb_4bit_use_double_quant=True,
    # Çift kantizasyon: scale faktörlerini de kantize et!
    # Scale'ler FP16 → INT8 → ~0.4 bit/parametre ek tasarruf
    # Küçük kalite bedeli karşılığında ekstra sıkıştırma

    bnb_4bit_quant_type="nf4",
    # "nf4" = Normal Float 4 — özel 4-bit format
    # Normal dağılıma göre optimal seviye yerleşimi
    # LLM ağırlıkları normal dağıldığından "nf4" > "fp4" olur
    # Alternatif: "fp4" = standart 4-bit float
)

# ── Model Yükleme ─────────────────────────────────────────────────
def model_yukle_ve_test(konfig, etiket):
    tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)

    model = AutoModelForCausalLM.from_pretrained(
        MODEL_ID,
        quantization_config=konfig,   # Hangi kantizasyon?
        device_map="auto",            # GPU'lara otomatik dağıt (çok GPU desteği)
        torch_dtype=torch.float16,    # Kantize olmayan katmanlar için tip
    )

    # Bellek ayak izi (bytes → GB)
    bellek_gb = model.get_memory_footprint() / 1e9
    print(f"\n[{etiket}]")
    print(f"  Bellek kullanımı : {bellek_gb:.2f} GB")

    # Çıkarım testi
    girdi = tokenizer(
        "Yapay zeka nedir?",
        return_tensors="pt"   # PyTorch tensörü olarak döndür
    ).to(model.device)        # Modelin olduğu cihaza taşı

    baslangic = time.time()
    with torch.no_grad():     # Gradyan hesaplamayı kapat (çıkarım = daha az bellek)
        cikti = model.generate(
            **girdi,
            max_new_tokens=80,    # En fazla 80 yeni token üret
            do_sample=False,      # Greedy decoding (en olası token)
        )
    sure = time.time() - baslangic

    # Yalnızca yeni üretilen tokenları çöz
    yeni_token_sayisi = cikti.shape[1] - girdi["input_ids"].shape[1]
    print(f"  Hız              : {yeni_token_sayisi / sure:.1f} token/sn")
    print(f"  Çıktı            : {tokenizer.decode(cikti[0][girdi['input_ids'].shape[1]:], skip_special_tokens=True)[:80]}")

# model_yukle_ve_test(bnb_int8, "INT8 BitsAndBytes")
# model_yukle_ve_test(bnb_int4, "INT4 NF4 BitsAndBytes")
print("💡 Gerçek GPU ortamında yorum satırlarını kaldır ve çalıştır.")
print("   Beklenen bellek kullanımı (Llama-2-7B):")
print("   FP32 → 28 GB | FP16 → 14 GB | INT8 → 7 GB | INT4 → 3.5 GB")

"""## 5.2 — Flash Attention 2: Tek Satır Aktivasyon

"""

# ── Kurulum ──────────────────────────────────────────────────────
# !pip install flash-attn --no-build-isolation
# Gereksinim: CUDA 11.6+, Ampere GPU (A100, RTX 3090, 4090 vb.)

from transformers import AutoModelForCausalLM, AutoTokenizer
import torch

def flash_attn_yukle(model_id: str):
    """
    Flash Attention 2 ile model yükle.
    Tek fark: attn_implementation='flash_attention_2' parametresi.
    """
    tokenizer = AutoTokenizer.from_pretrained(model_id)

    model = AutoModelForCausalLM.from_pretrained(
        model_id,
        torch_dtype=torch.bfloat16,         # FA2 BF16 veya FP16 gerektirir

        attn_implementation="flash_attention_2",
        # ← Bu tek parametre tüm attention katmanlarını FA2'ye geçirir
        # HuggingFace otomatik olarak tüm MultiHeadAttention bloklarını değiştirir
        # Matematiksel çıktı standart attention ile AYNIDIR — sadece daha hızlı

        device_map="auto",
    )
    return model, tokenizer

def dikkat_karsilastir(model, tokenizer, n_token: int = 2048):
    """Belirtilen dizi uzunluğunda forward pass süresi ölç."""
    # Uzun bir prompt oluştur (n_token kadar)
    metin = "Bu bir test metni. " * (n_token // 4)
    girdi = tokenizer(
        metin,
        return_tensors="pt",
        max_length=n_token,
        truncation=True         # n_token'dan uzunsa kırp
    ).to(model.device)

    # Isınma turu (ilk çalışma cache'den yavaş olabilir)
    with torch.no_grad():
        _ = model(**girdi)

    # Gerçek ölçüm
    torch.cuda.synchronize()   # GPU işlemlerinin tamamlanmasını bekle
    t0 = time.time()
    with torch.no_grad():
        _ = model(**girdi)
    torch.cuda.synchronize()
    return time.time() - t0

# Beklenen performans (A100 80GB ölçümleri):
print("""
⚡ Flash Attention 2 — Beklenen Kazanımlar (A100 80GB, BF16)
═══════════════════════════════════════════════════════════════

  Dizi Uz.  │ Std Attn  │ Flash Attn 2 │ Hız   │ Bellek
  ──────────│───────────│──────────────│───────│──────────
  512 tok   │   12 ms   │    8 ms      │  1.5× │ ~aynı
  2K  tok   │   48 ms   │   18 ms      │  2.7× │ 2× az
  4K  tok   │  192 ms   │   38 ms      │  5.1× │ 4× az
  8K  tok   │  768 ms   │   82 ms      │  9.4× │ 8× az
  16K tok   │ OOM 💥    │  168 ms      │   ∞×  │ çalışır!

  Temel kural: N büyüdükçe FA2 kazanımı büyür (O(N²) → O(N) bellek)

  Kullanım:
  model = AutoModelForCausalLM.from_pretrained(
      'mistralai/Mistral-7B-v0.1',
      attn_implementation='flash_attention_2',   ← tek satır!
      torch_dtype=torch.bfloat16,
  )
""")

"""## 5.3 — vLLM: Continuous Batching + PagedAttention

"""

# ── Kurulum ──────────────────────────────────────────────────────
# !pip install vllm

"""
vLLM iki temel tekniği birleştirir:

1. Continuous Batching  → GPU boş kalmaz
2. PagedAttention       → KV Cache parçalanmadan saklanır

PagedAttention ne yapar?
    OS'daki sanal bellek sayfaları gibi:
    - KV Cache sabit boyutlu bloklara bölünür (blok = birkaç token)
    - Her istek ihtiyacı kadar blok alır — önceden maksimum ayırma yok
    - Bloklar bitişik olmak zorunda değil — parçalanma önlenir
    - GPU kullanımı: %55 → %96
"""

VLLM_KULLANIM = """
from vllm import LLM, SamplingParams

# ── Model Yükleme ─────────────────────────────────────────────────
llm = LLM(
    model="meta-llama/Llama-2-7b-hf",

    tensor_parallel_size=1,
    # Kaç GPU kullanılsın?
    # 1 GPU: model tek GPU'da çalışır
    # 2 GPU: model iki GPU'ya bölünür (tensor parallelism)
    # Kural: model boyutu / GPU VRAM'i = kaç GPU lazım

    gpu_memory_utilization=0.90,
    # GPU VRAM'inin yüzde kaçı kullanılsın?
    # 0.90 = %90 → PagedAttention için KV Cache buffer'ı
    # Daha yüksek: daha uzun bağlam ama OOM riski
    # Daha düşük: güvenli ama daha kısa bağlam

    max_model_len=8192,
    # Maksimum desteklenen token sayısı (prompt + output)
    # KV Cache boyutunu belirler

    # quantization="awq",   # AWQ INT4 kantizasyon
    # quantization="gptq",  # GPTQ INT4 kantizasyon
)

# ── Sampling Parametreleri ────────────────────────────────────────
params = SamplingParams(
    temperature=0.8,   # 0=deterministik, 1=rastgele, >1=daha yaratıcı
    top_p=0.95,        # Nucleus sampling: kümülatif olasılık eşiği
    max_tokens=256,    # Maksimum üretilecek token
    repetition_penalty=1.1,  # Tekrar cezası
)

# ── Toplu Çıkarım (Continuous Batching otomatik!) ────────────────
promptlar = [
    "Türkiye'nin başkenti neresidir?",
    "Flash Attention'ı kısaca açıkla.",
    "Python'da liste anlama (list comprehension) nedir?",
    "LLM kantizasyonunun avantajları nelerdir?",
]

# vLLM tüm promptları aynı anda işler — continuous batching dahili
ciktilar = llm.generate(promptlar, params)

for cikti in ciktilar:
    print(f"Soru  : {cikti.prompt[:50]}...")
    print(f"Yanıt : {cikti.outputs[0].text[:100]}...")
    print(f"Token : {len(cikti.outputs[0].token_ids)} üretildi")
    print()
"""

# ── OpenAI Uyumlu API Server ──────────────────────────────────────
VLLM_SERVER = """
# Terminal'de çalıştır:

# 1. vLLM server başlat (OpenAI API uyumlu)
python -m vllm.entrypoints.openai.api_server \\
    --model meta-llama/Llama-2-7b-hf \\
    --port 8000 \\
    --tensor-parallel-size 1 \\
    --gpu-memory-utilization 0.9 \\
    --max-model-len 4096

# 2. curl ile test et
curl http://localhost:8000/v1/completions \\
    -H "Content-Type: application/json" \\
    -d '{
      "model": "meta-llama/Llama-2-7b-hf",
      "prompt": "Flash Attention nedir?",
      "max_tokens": 100,
      "temperature": 0.8
    }'

# 3. Python openai kütüphanesiyle kullan
# openai.api_base = "http://localhost:8000/v1"
# → Standart OpenAI kodun değişmeden çalışır!
"""

print("vLLM Kullanım Örneği:")
print(VLLM_KULLANIM)
print("\nvLLM Server:")
print(VLLM_SERVER)

"""---
# 📊 Bölüm 6 — Kapsamlı Özet ve Karar Rehberi


"""

# ── Tüm tekniklerin özet karşılaştırması ─────────────────────────
teknikler = {
    # İsim: {bellek_kat, hiz_kat, kalite_0to1, uygulama_zorluğu}
    "Kantizasyon INT8":      {"bellek": 4.0, "hiz": 2.0, "kalite": 0.99, "zorluk": 1},
    "Kantizasyon INT4":      {"bellek": 8.0, "hiz": 3.5, "kalite": 0.96, "zorluk": 2},
    "KV Cache (GQA 8:1)":   {"bellek": 8.0, "hiz": 8.0, "kalite": 1.00, "zorluk": 2},
    "Flash Attention 2":     {"bellek":10.0, "hiz": 4.0, "kalite": 1.00, "zorluk": 1},
    "Continuous Batching":   {"bellek": 1.0, "hiz": 4.0, "kalite": 1.00, "zorluk": 3},
    "Tümü Birlikte":        {"bellek":20.0, "hiz":15.0, "kalite": 0.96, "zorluk": 4},
}

fig, eksenler = plt.subplots(1, 3, figsize=(17, 6))
fig.suptitle("LLM Optimizasyon Teknikleri — Kapsamlı Karşılaştırma",
             color='#e8eaf0', fontsize=14, fontweight='bold')

etiketler   = list(teknikler.keys())
x_konumlar  = np.arange(len(etiketler))
bar_genisligi = 0.65
renkler     = ['#6c8ef5','#a78bfa','#34d399','#2dd4bf','#fbbf24','#f87171']

# ── Bellek Tasarrufu Grafiği ──────────────────────────────────────
ax1 = eksenler[0]
degerler = [teknikler[t]["bellek"] for t in etiketler]
barlar = ax1.bar(x_konumlar, degerler, width=bar_genisligi,
                  color=renkler, alpha=0.85)

# Her çubuğun üstüne değer yaz
for bar, val in zip(barlar, degerler):
    ax1.text(bar.get_x() + bar.get_width()/2,
              bar.get_height() + 0.3,
              f"{val:.0f}×",
              ha='center', va='bottom',
              fontsize=10, color='#e8eaf0', fontweight='bold')

ax1.set_xticks(x_konumlar)
ax1.set_xticklabels(etiketler, rotation=25, ha='right', fontsize=8)
ax1.set_ylabel("Kazanım (×)")
ax1.set_title("Bellek Tasarrufu", color='#9aa0b4')

# ── Hız Kazanımı Grafiği ─────────────────────────────────────────
ax2 = eksenler[1]
degerler2 = [teknikler[t]["hiz"] for t in etiketler]
barlar2 = ax2.bar(x_konumlar, degerler2, width=bar_genisligi,
                   color=renkler, alpha=0.85)

for bar, val in zip(barlar2, degerler2):
    ax2.text(bar.get_x() + bar.get_width()/2,
              bar.get_height() + 0.1,
              f"{val:.0f}×",
              ha='center', va='bottom',
              fontsize=10, color='#e8eaf0', fontweight='bold')

ax2.set_xticks(x_konumlar)
ax2.set_xticklabels(etiketler, rotation=25, ha='right', fontsize=8)
ax2.set_ylabel("Kazanım (×)")
ax2.set_title("Hız Kazanımı", color='#9aa0b4')

# ── Kalite Koruma Grafiği ─────────────────────────────────────────
ax3 = eksenler[2]
degerler3 = [teknikler[t]["kalite"] for t in etiketler]
barlar3 = ax3.bar(x_konumlar, degerler3, width=bar_genisligi,
                   color=renkler, alpha=0.85)

# 100% çizgisi — ideal kalite referansı
ax3.axhline(y=1.0, color='white', ls='--', lw=1.0, alpha=0.4, label='Mükemmel Kalite')

for bar, val in zip(barlar3, degerler3):
    ax3.text(bar.get_x() + bar.get_width()/2,
              bar.get_height() + 0.002,
              f"{val*100:.0f}%",
              ha='center', va='bottom',
              fontsize=10, color='#e8eaf0', fontweight='bold')

ax3.set_xticks(x_konumlar)
ax3.set_xticklabels(etiketler, rotation=25, ha='right', fontsize=8)
ax3.set_ylim(0.88, 1.06)
ax3.set_ylabel("Kalite Skoru")
ax3.set_title("Kalite Koruma (1.0 = kayıpsız)", color='#9aa0b4')
ax3.legend(fontsize=9)

plt.tight_layout()
plt.savefig('ozet_karsilastirma.png', dpi=150,
            bbox_inches='tight', facecolor='#0d0f14')
plt.show()

# ── Metin tabanlı karar rehberi ───────────────────────────────────
print("""
╔══════════════════════════════════════════════════════════════════╗
║            LLM OPTİMİZASYON KARAR REHBERİ                     ║
╠══════════════════════════════════════════════════════════════════╣
║                                                                  ║
║  🖥️  Laptop / Kişisel Bilgisayar                               ║
║      → GGUF Q4_K_M + llama.cpp                                  ║
║      → 7B model = ~4 GB RAM, CPU'da çalışır                    ║
║                                                                  ║
║  🎮  Orta Seviye GPU (RTX 3060 12GB)                            ║
║      → AWQ INT4 + Flash Attention 2                             ║
║      → 7B model = ~4 GB VRAM, hızlı çıkarım                    ║
║                                                                  ║
║  🖥️  Yüksek Seviye GPU (RTX 4090 24GB)                         ║
║      → INT8 BnB + GQA + Flash Attention 2                       ║
║      → 13B-30B model, dengeli kalite/hız                        ║
║                                                                  ║
║  ☁️  Üretim API Servisi (Multi-GPU)                             ║
║      → vLLM + Continuous Batching + FP16                        ║
║      → GPU başına 10-50× daha fazla throughput                  ║
║                                                                  ║
║  🔬  Araştırma / İnce Ayar (Fine-tuning)                        ║
║      → QLoRA (4-bit base + FP16 adapter)                        ║
║      → Gradient checkpointing + Flash Attention 2               ║
║                                                                  ║
╚══════════════════════════════════════════════════════════════════╝
""")

"""---
## 📚 Kaynaklar ve Daha Fazla Okuma

| Teknik | Paper | Kütüphane |
|--------|-------|-----------|
| GPTQ | [arxiv 2210.17323](https://arxiv.org/abs/2210.17323) | `auto-gptq` |
| AWQ | [arxiv 2306.00978](https://arxiv.org/abs/2306.00978) | `autoawq` |
| Flash Attention 1 | [arxiv 2205.14135](https://arxiv.org/abs/2205.14135) | `flash-attn` |
| Flash Attention 2 | [arxiv 2307.08691](https://arxiv.org/abs/2307.08691) | `flash-attn>=2` |
| GQA | [arxiv 2305.13245](https://arxiv.org/abs/2305.13245) | `transformers` |
| PagedAttention | [arxiv 2309.06180](https://arxiv.org/abs/2309.06180) | `vllm` |
| Continuous Batching | [OSDI 2022 Orca](https://www.usenix.org/conference/osdi22/presentation/yu) | `vllm`, `tgi` |
| Speculative Decoding | [arxiv 2302.01318](https://arxiv.org/abs/2302.01318) | `vllm` |


"""