# -*- coding: utf-8 -*-
"""sicaklikveotoregresyonodev.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tDszX1B_YqvWl11m5q2M6rKcC7Dc1cHD
"""

import re                        # metni temizlemek ve kelimelere ayırmak için düzenli ifadeler
import numpy as np                # softmax, olasılık vektörleri ve rastgele örnekleme için
import matplotlib.pyplot as plt   # olasılık dağılımlarını çubuk grafikle çizmek için

rng_global = np.random.default_rng(42)

plt.rcParams["figure.dpi"] = 110
plt.rcParams["axes.spines.top"] = False
plt.rcParams["axes.spines.right"] = False

def softmax_with_temperature(logits, T=1.0):
    """Logit vektörünü, T sıcaklığıyla ölçekleyip olasılık dağılımına çevirir."""
    logits = np.asarray(logits, dtype=float) / T   # 1. adım: her logiti T'ye böl (sıcaklık ölçekleme)
    logits = logits - logits.max()                 # 2. adım: en büyük değeri çıkar (sayısal kararlılık)
    exp_logits = np.exp(logits)                     # 3. adım: her ölçeklenmiş logitin e tabanındaki üssünü al
    return exp_logits / exp_logits.sum()             # 4. adım: toplama böl -> toplamı 1 olan bir olasılık dağılımı elde et

def greedy_index(probs):
    # En yüksek olasılığa sahip elemanın indeksi -> rastgelelik yok
    return int(np.argmax(probs))

def temperature_sample_index(probs, rng):
    # probs dizisini ağırlık olarak kullanarak rastgele bir indeks çeker
    return int(rng.choice(len(probs), p=probs))

def top_k_index(probs, k, rng):
    k = min(k, len(probs))
    top_idx = np.argsort(probs)[-k:]            # en yüksek k olasılığın indeksleri
    top_probs = probs[top_idx]
    top_probs = top_probs / top_probs.sum()      # havuzu yeniden normalize et
    return int(rng.choice(top_idx, p=top_probs))

def top_p_index(probs, p, rng):
    order = np.argsort(probs)[::-1]              # büyükten küçüğe sırala
    sorted_probs = probs[order]
    cumulative = np.cumsum(sorted_probs)          # kümülatif olasılık toplamı
    cutoff = int(np.searchsorted(cumulative, p)) + 1  # kümülatif toplam p'yi geçtiği ilk nokta
    pool_idx = order[:cutoff]                     # havuz oluştur
    pool_probs = probs[pool_idx]
    pool_probs = pool_probs / pool_probs.sum()     # havuzu yeniden normalize et
    return int(rng.choice(pool_idx, p=pool_probs))

# YENİ CORPUS: Teknoloji ve yapay zeka odaklı metin
corpus = """
Yapay zeka bugün hayatımızı büyük oranda değiştiriyor. Yapay zeka gelecekte dünyayı tamamen ele geçirebilir.
Yapay zeka insanlığa yeni ufuklar açıyor ve işlerimizi kolaylaştırıyor.
Teknoloji hızla gelişiyor ve yeni algoritmalar hayatımıza yön veriyor.
Teknoloji her sektörde devrim yaratıyor ama bazı riskler barındırıyor.
Gelecekte robotlar dünyayı yönetecek ve insanlar yeni yaşam alanları arayacak.
Gelecekte her şey çok daha hızlı olacak ama eski huzur kalmayacak.
Büyük veri analizi şirketlerin kaderini değiştiriyor. Büyük veri sayesinde geleceği tahmin etmek artık çok daha kolay.
"""

def tokenize(text):
    text = text.replace("İ", "i").replace("I", "ı")  # Türkçe harf tuzağı çözümü
    text = text.lower()                                # küçük harfe çevir
    text = re.sub(r"[^\w\sçğıöşüâî]", " ", text, flags=re.UNICODE)  # noktalama işaretlerini kaldır
    return text.split()                                  # kelimelere ayır

tokens = tokenize(corpus)
print(f"Yeni Toplam Token Sayısı: {len(tokens)}")
print(f"Yeni Benzersiz Kelime Sayısı: {len(set(tokens))}")

bigram_counts = {}
for current_word, next_word in zip(tokens[:-1], tokens[1:]):
    bigram_counts.setdefault(current_word, {})
    bigram_counts[current_word][next_word] = bigram_counts[current_word].get(next_word, 0) + 1

def predict_next_word(current_word, temperature=1.0):
    """Yeni veri tabanına göre bir sonraki kelimenin olasılıklarını hesaplar."""
    if current_word not in bigram_counts:
        return None
    candidates = list(bigram_counts[current_word].keys())
    counts = np.array([bigram_counts[current_word][c] for c in candidates], dtype=float)
    pseudo_logits = np.log(counts + 1.0)           # sayımlardan logit elde etme
    probs = softmax_with_temperature(pseudo_logits, temperature)
    return candidates, probs

def generate(seed_word, steps=12, temperature=1.0, strategy="temperature", k=3, p=0.9, seed=None):
    """Yeni veri setiyle otoregresif metin üretir."""
    rng = np.random.default_rng(seed)
    current = seed_word.lower()
    sequence = [current]

    for _ in range(steps):
        result = predict_next_word(current, temperature)
        if result is None:
            sequence.append("...[zincir koptu: devamı gözlenmedi]")
            break

        candidates, probs = result

        # Strateji seçimi
        if strategy == "greedy":
            idx = greedy_index(probs)
        elif strategy == "top_k":
            idx = top_k_index(probs, k, rng)
        elif strategy == "top_p":
            idx = top_p_index(probs, p, rng)
        else:  # "temperature"
            idx = temperature_sample_index(probs, rng)

        next_word = candidates[idx]
        sequence.append(next_word)
        current = next_word             # <-- AUTOREGRESSION

    return " ".join(sequence)

# GÜNCEL TEST SENARYOLARI
print("1. Greedy Stratejisi (Sıcaklık etkisiz, kısırdöngü kontrolü):")
print("  >", generate("yapay", steps=12, strategy="greedy"))
print()

print("2. Pure Temperature Sampling, T=0.3 (Düşük sıcaklık / Garantici):")
print("  >", generate("yapay", steps=12, temperature=0.3, strategy="temperature", seed=5))
print()

print("3. Pure Temperature Sampling, T=1.8 (Yüksek sıcaklık / Riskli-Çılgın):")
print("  >", generate("yapay", steps=12, temperature=1.8, strategy="temperature", seed=5))
print()

print("4. Top-K Sampling (k=2, T=1.0 - Sadece en popüler ilk iki kelime yarışır):")
print("  >", generate("yapay", steps=12, strategy="top_k", k=2, temperature=1.0, seed=5))
print()

print("5. Top-P Sampling (p=0.85, T=1.2 - Toplam kalitesi %85 eden dinamik havuz):")
print("  >", generate("yapay", steps=12, strategy="top_p", p=0.85, temperature=1.2, seed=5))

