# -*- coding: utf-8 -*-
"""goruntu_isleme.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zfMeqM3BAbMPCo_PTKQGv4TyodT-6Xqq
"""

# Gerekli kütüphaneleri kontrol edip kuruyoruz
!pip install torch torchvision matplotlib --quiet

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import DataLoader, Dataset
import torchvision
import torchvision.transforms as transforms
import numpy as np
import matplotlib.pyplot as plt

# Tekrar üretilebilirlik için seed ve cihaz seçimi
torch.manual_seed(42)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Kullanılan cihaz: {device}")

# --- 1.1. Veri Setinin Yüklenmesi ---
transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.1307,), (0.3081,))
])

train_dataset = torchvision.datasets.MNIST(root='./data', train=True, download=True, transform=transform)
test_dataset = torchvision.datasets.MNIST(root='./data', train=False, download=True, transform=transform)

# Hızlı çalışması için küçük batch_size ve subset alabiliriz (Opsiyonel)
train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=1000, shuffle=False)

# --- 1.2. Model Tanımı (Senin Kodun) ---
class BasitCNN(nn.Module):
    def __init__(self, num_classes=10):
        super().__init__()
        self.conv1 = nn.Conv2d(in_channels=1, out_channels=16, kernel_size=3, padding=1)
        self.bn1 = nn.BatchNorm2d(16)
        self.conv2 = nn.Conv2d(in_channels=16, out_channels=32, kernel_size=3, padding=1)
        self.bn2 = nn.BatchNorm2d(32)
        self.pool = nn.MaxPool2d(kernel_size=2, stride=2)
        self.fc1 = nn.Linear(32 * 7 * 7, 128)
        self.dropout = nn.Dropout(0.3)
        self.fc2 = nn.Linear(128, num_classes)

    def forward(self, x):
        x = self.pool(F.relu(self.bn1(self.conv1(x))))
        x = self.pool(F.relu(self.bn2(self.conv2(x))))
        x = torch.flatten(x, 1)
        x = F.relu(self.fc1(x))
        x = self.dropout(x)
        return self.fc2(x)

model_cnn = BasitCNN(num_classes=10).to(device)

# --- 1.3. Eğitim Döngüsü ---
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model_cnn.parameters(), lr=0.001)

model_cnn.train()
for batch_idx, (data, target) in enumerate(train_loader):
    data, target = data.to(device), target.to(device)
    optimizer.zero_grad()
    output = model_cnn(data)
    loss = criterion(output, target)
    loss.backward()
    optimizer.step()

    if batch_idx % 200 == 0:
        print(f"CNN Eğitim - Adım [{batch_idx}/{len(train_loader)}] Kalan Kayıp: {loss.item():.4f}")
    if batch_idx == 400: break # Zaman kazanmak için erken kesiyoruz

print("CNN Eğitimi Başarıyla Test Edildi!")

# --- 2.1. Yapay Segmentasyon Veri Üreticisi ---
class YapaySegmentasyonDataset(Dataset):
    def __init__(self, num_samples=200, size=160):
        self.num_samples = num_samples
        self.size = size

    def __len__(self):
        return self.num_samples

    def __getitem__(self, idx):
        # Siyah maske ve görsel oluştur
        img = np.zeros((self.size, self.size, 3), dtype=np.float32)
        mask = np.zeros((self.size, self.size), dtype=np.float32)

        # Rastgele daireler çiz
        for _ in range(np.random.randint(1, 4)):
            cx, cy = np.random.randint(20, self.size-20, size=2)
            r = np.random.randint(10, 30)

            # Basitçe pikselleri tara ve daire içine düşenleri boya
            y, x = np.ogrid[:self.size, :self.size]
            dist = (x - cx)**2 + (y - cy)**2
            img[dist <= r**2] = [np.random.rand(), np.random.rand(), np.random.rand()] # Renkli daire
            mask[dist <= r**2] = 1.0 # Maske alanı

        img = torch.from_numpy(img).permute(2, 0, 1) # (C, H, W)
        mask = torch.from_numpy(mask).unsqueeze(0)  # (1, H, W)
        return img, mask

unet_dataset = YapaySegmentasyonDataset()
unet_loader = DataLoader(unet_dataset, batch_size=4, shuffle=True)

# --- 2.2. U-Net Mimarisi (Senin Kodun) ---
class ConvBlok(nn.Module):
    def __init__(self, in_ch, out_ch):
        super().__init__()
        self.blok = nn.Sequential(
            nn.Conv2d(in_ch, out_ch, kernel_size=3, padding=1),
            nn.BatchNorm2d(out_ch),
            nn.ReLU(inplace=True),
            nn.Conv2d(out_ch, out_ch, kernel_size=3, padding=1),
            nn.BatchNorm2d(out_ch),
            nn.ReLU(inplace=True),
        )
    def forward(self, x): return self.blok(x)

class UNet(nn.Module):
    def __init__(self, in_ch=3, num_classes=1, ozellikler=[64, 128, 256]):
        super().__init__()
        self.encoder = nn.ModuleList()
        self.decoder = nn.ModuleList()
        self.pool = nn.MaxPool2d(kernel_size=2, stride=2)

        kanal = in_ch
        for f in ozellikler:
            self.encoder.append(ConvBlok(kanal, f))
            kanal = f

        self.bottleneck = ConvBlok(ozellikler[-1], ozellikler[-1] * 2)

        for f in reversed(ozellikler):
            self.decoder.append(nn.ConvTranspose2d(f * 2, f, kernel_size=2, stride=2))
            self.decoder.append(ConvBlok(f * 2, f))

        self.son_katman = nn.Conv2d(ozellikler[0], num_classes, kernel_size=1)

    def forward(self, x):
        skip_baglantilari = []
        for enc_blok in self.encoder:
            x = enc_blok(x)
            skip_baglantilari.append(x)
            x = self.pool(x)

        x = self.bottleneck(x)
        skip_baglantilari = skip_baglantilari[::-1]

        for i in range(0, len(self.decoder), 2):
            x = self.decoder[i](x)
            skip = skip_baglantilari[i // 2]
            if x.shape != skip.shape:
                x = F.interpolate(x, size=skip.shape[2:])
            x = torch.cat((skip, x), dim=1)
            x = self.decoder[i + 1](x)

        return self.son_katman(x)

model_unet = UNet(in_ch=3, num_classes=1).to(device)

# --- 2.3. U-Net Eğitim Döngüsü ---
criterion_unet = nn.BCEWithLogitsLoss() # İkili segmentasyon için en iyisi
optimizer_unet = optim.Adam(model_unet.parameters(), lr=0.001)

model_unet.train()
for batch_idx, (imgs, masks) in enumerate(unet_loader):
    imgs, masks = imgs.to(device), masks.to(device)
    optimizer_unet.zero_grad()
    outputs = model_unet(imgs)
    loss = criterion_unet(outputs, masks)
    loss.backward()
    optimizer_unet.step()

    if batch_idx % 10 == 0:
        print(f"U-Net Eğitim - Adım [{batch_idx}/{len(unet_loader)}] Kayıp: {loss.item():.4f}")

print("U-Net Eğitimi Başarıyla Test Edildi!")

# --- 3.1. Mask R-CNN Uyumlu Yapay Veri Seti ---
class MaskRCNNDataset(Dataset):
    def __init__(self, num_samples=10, size=300):
        self.num_samples = num_samples
        self.size = size

    def __len__(self): return self.num_samples

    def __getitem__(self, idx):
        img = np.zeros((self.size, self.size, 3), dtype=np.float32)

        # Koordinatları belirle (1 adet belirgin kare çizelim)
        xmin, ymin = np.random.randint(20, 100), np.random.randint(20, 100)
        xmax, ymax = xmin + np.random.randint(50, 100), ymin + np.random.randint(50, 100)

        img[ymin:ymax, xmin:xmax] = [1.0, 0.0, 0.0] # Kırmızı kare

        # Maske formatı oluştur: (N, H, W) -> N nesne sayısı
        mask = np.zeros((1, self.size, self.size), dtype=np.uint8)
        mask[0, ymin:ymax, xmin:xmax] = 1

        # Hedef sözlüğünü (target) hazırla
        target = {}
        target["boxes"] = torch.as_tensor([[xmin, ymin, xmax, ymax]], dtype=torch.float32)
        target["labels"] = torch.as_tensor([1], dtype=torch.int64) # Sınıf 1 (Kare)
        target["masks"] = torch.as_tensor(mask, dtype=torch.uint8)

        img = torch.from_numpy(img).permute(2, 0, 1)
        return img, target

# Custom collate_fn çünkü target boyutları değişken olabilir
def collate_fn(batch): return tuple(zip(*batch))

mask_dataset = MaskRCNNDataset()
mask_loader = DataLoader(mask_dataset, batch_size=2, shuffle=True, collate_fn=collate_fn)

# --- 3.2. Model Tanımı (Senin Kodun) ---
from torchvision.models.detection import maskrcnn_resnet50_fpn
from torchvision.models.detection.faster_rcnn import FastRCNNPredictor
from torchvision.models.detection.mask_rcnn import MaskRCNNPredictor

def mask_rcnn_olustur(num_classes):
    model = maskrcnn_resnet50_fpn(weights="DEFAULT")
    in_features = model.roi_heads.box_predictor.cls_score.in_features
    model.roi_heads.box_predictor = FastRCNNPredictor(in_features, num_classes)
    in_features_mask = model.roi_heads.mask_predictor.conv5_mask.in_channels
    hidden_layer = 256
    model.roi_heads.mask_predictor = MaskRCNNPredictor(in_features_mask, hidden_layer, num_classes)
    return model

# 0: Arka plan, 1: Kare (Toplam 2 sınıf)
model_maskrcnn = mask_rcnn_olustur(num_classes=2).to(device)

# --- 3.3. Mask R-CNN Eğitim Adımı ---
optimizer_rcnn = optim.SGD(model_maskrcnn.parameters(), lr=0.005, momentum=0.9)

model_maskrcnn.train() # Eğitim modu kayıpları döner
images, targets = next(iter(mask_loader))

images = list(image.to(device) for image in images)
targets = [{k: v.to(device) for k, v in t.items()} for t in targets]

loss_dict = model_maskrcnn(images, targets)
losses = sum(loss for loss in loss_dict.values())

optimizer_rcnn.zero_grad()
losses.backward()
optimizer_rcnn.step()

print(f"Mask R-CNN Eğitim Adımı Başarılı! Toplam Kayıp: {losses.item():.4f}")
print("Tüm mimariler başarıyla kuruldu, gerçek/yapay veri setleriyle bağlandı ve eğitildi!")

