# -*- coding: utf-8 -*-
"""finetunigodev.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QlA4ry40t-uBuMFyaVDHB_prm452CQAT
"""

# 1. KURULUMLAR VE KÜTÜPHANELER
!pip install -q transformers datasets peft accelerate pandas pyarrow --upgrade

import torch
import random
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datasets import Dataset
import transformers as hf_core
import peft as native_peft

CORE_SEED = 999
random.seed(CORE_SEED)
np.random.seed(CORE_SEED)
torch.manual_seed(CORE_SEED)
torch.cuda.manual_seed_all(CORE_SEED)

hardware_node = "cuda" if torch.cuda.is_available() else "cpu"

# 3. VERİ YÜKLEME VE DÖNÜŞTÜRME
# Kaggle'dan indirilen parquet dosyasını okuyoruz
raw_dataframe = pd.read_parquet("/content/alpaca-dataset.parquet")

# Hızlı bir test eğitimi için ilk 500 satırı seçiyoruz (Tüm veri için satırı silebilirsiniz)
raw_dataframe = raw_dataframe.head(500)

# Veriyi yeni yapıya (prompt/response) haritalıyoruz
structure_pool = []
for _, row in raw_dataframe.iterrows():
    user_task = row['instruction']
    if row['input'] and str(row['input']).strip() != "":
        user_task += f"\nContext: {row['input']}"

    structure_pool.append({
        "prompt": user_task,
        "response": row['output']
    })

# 4. YENİ ŞABLON TASARIMI (PROMPT TEMPLATE)
def structural_formatter(element):
    # Klasik Alpaca etiketleri '>>> REQUEST:' ve '>>> ANSWER:' olarak değiştirildi
    modified_text = (
        f">>> REQUEST:\n{element['prompt']}\n\n"
        f">>> ANSWER:\n{element['response']}"
    )
    return {"composed_stream": modified_text}

hf_dataset_source = Dataset.from_list(structure_pool)
mapped_dataset = hf_dataset_source.map(structural_formatter)

# 5. MODEL VE TOKENIZER AYARLARI (DEĞİŞTİRİLDİ)
BASE_NET_NAME = "gpt2" # Alternatif küçük model
text_processor = hf_core.AutoTokenizer.from_pretrained(BASE_NET_NAME)

if text_processor.pad_token is None:
    text_processor.add_special_tokens({'pad_token': '[PAD]'})

architecture_model = hf_core.AutoModelForCausalLM.from_pretrained(BASE_NET_NAME)
architecture_model.resize_token_embeddings(len(text_processor))
architecture_model.to(hardware_node)

# 6. TOKENIZATION SÜRECİ (YENİ HİPERPARAMETRELER)
MAX_SEQUENCE_BOUND = 200 # Uzunluk değiştirildi

def internal_tokenization_handler(batch_data):
    token_outputs = text_processor(
        batch_data["composed_stream"],
        truncation=True,
        max_length=MAX_SEQUENCE_BOUND,
        padding="max_length"
    )
    token_outputs["labels"] = token_outputs["input_ids"].copy()
    return token_outputs

final_token_dataset = mapped_dataset.map(
    internal_tokenization_handler,
    batched=True,
    remove_columns=mapped_dataset.column_names
)

print('LoRA yapılandırması sırasında `torchao` sürüm uyumsuzluğu hatasını düzeltmek için `torchao` güncelleniyor.')
!pip install torchao --upgrade

# 7. LoRA YAPILANDIRMASI (PARAMETRELER DEĞİŞTİRİLDİ)
lora_strategy_config = native_peft.LoraConfig(
    r=16,                         # Rank parametresi değiştirildi
    lora_alpha=32,                # Alpha parametresi değiştirildi
    target_modules=["c_attn"],    # GPT2 için özel katman hedeflemesi
    lora_dropout=0.05,
    bias="none",
    task_type=native_peft.TaskType.CAUSAL_LM
)

optimized_peft_model = native_peft.get_peft_model(architecture_model, lora_strategy_config)

# 8. EĞİTİM ARGÜMANLARI VE BAŞLATMA
execution_arguments = hf_core.TrainingArguments(
    output_dir="./modified_alpaca_checkpoint",
    num_train_epochs=2,           # Epoch sayısı değiştirildi
    per_device_train_batch_size=4,# Batch size değiştirildi
    learning_rate=3e-4,           # Öğrenme oranı değiştirildi
    logging_steps=10,
    save_steps=50,
    fp16=torch.cuda.is_available(),
    report_to="none"
)

batch_collator = hf_core.DataCollatorForLanguageModeling(tokenizer=text_processor, mlm=False)

runtime_trainer = hf_core.Trainer(
    model=optimized_peft_model,
    args=execution_arguments,
    train_dataset=final_token_dataset,
    data_collator=batch_collator
)

# Eğitimi başlatıyoruz
runtime_trainer.train()

# 9. MODEL KAYDETME
optimized_peft_model.save_pretrained("./final_lora_alpaca_weights")
print("İnce ayar süreci tamamlandı ve adaptör ağırlıkları kaydedildi.")