# -*- coding: utf-8 -*-
"""llmodev.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wgO_pRZDQqph7VsglH7YW-RlMmq0pzr7
"""

from datasets import load_dataset

# 1. Veri setini internetten jet hızıyla indiriyoruz
print("IMDB Veri seti indiriliyor...")
ds = load_dataset("stanfordnlp/imdb")

# 2. Verinin yapısını kontrol edelim (Kaç satır var?)
print("\n--- Veri Seti Yapısı ---")
print(ds)

# 3. İlk örneğe göz atalım (text ve label neye benziyor?)
print("\n--- İlk Örnek İncelemesi ---")
sample = ds['train'][0]
print(f"Etiket (Label): {sample['label']} (0 = Olumsuz, 1 = Olumlu)")
print(f"Yorum (Text): {sample['text'][:200]}...") # İlk 200 karakteri görelim

from transformers import AutoTokenizer

# Dünyaca ünlü açık kaynaklı bir modelin tokenizer'ını indiriyoruz
model_name = "mistralai/Mistral-7B-v0.1"
print(f"{model_name} Tokenizer indiriliyor...")
tokenizer = AutoTokenizer.from_pretrained(model_name)

# Mistral/Llama gibi modellerde varsayılan padding token'ı olmayabilir.
# Eğer yoksa, cümlenin bittiğini gösteren EOS token'ını doldurma (PAD) olarak atıyoruz.
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

print("\nTokenizer Hazır!")
print(f"Sözlük Boyutu (Vocab Size): {tokenizer.vocab_size:,}")
print(f"Padding Token: {tokenizer.pad_token}")

def preprocess_function(examples):
    """
    Kargo paketleme odamız!
    Gelen metinleri kırpar, doldurur ve yapay zekanın anlayacağı sayılara böler.
    """
    return tokenizer(
        examples["text"],           # İşlenecek metin sütunu
        truncation=True,            # Çok uzun yorumları kes (Hafıza taşmasın)
        max_length=128,             # Maksimum koli boyutu 128 token olsun (Hızlı çalışması için)
        padding="max_length",       # Kısa yorumların sonuna PAD token ekleyerek 128'e eşitle
        return_attention_mask=True  # Yapay zekaya köpükleri (pad) görmezden gelmesi için maske üret
    )

print("25.000 satırlık eğitim verisi tokenize ediliyor (Bu işlem birkaç saniye sürebilir)...")

# .map() fonksiyonu tüm satırları çoklu işlemci kullanarak jet hızıyla dönüştürür.
tokenized_ds = ds.map(preprocess_function, batched=True)

print("\nİşlem Tamamlandı!")

# Tokenize edilmiş ilk veriyi çekelim
final_sample = tokenized_ds['train'][0]

print("--- YAPAY ZEKANIN GÖRECEĞİ PAKET ---")
print(f"\n1. input_ids (Kelimelerin Sayı Karşılıkları - İlk 20 tanesi):")
print(final_sample['input_ids'][:20])

print(f"\n2. attention_mask (1 = Kelime, 0 = Boşluk Doldurma - İlk 20 tanesi):")
print(final_sample['attention_mask'][:20])

print(f"\n3. Hedef Etiket (Label): {final_sample['label']}")

# Sayıları tekrar insanca metne dönüştürüp kontrol edelim (Padding'leri göreceksiniz)
decoded_text = tokenizer.decode(final_sample['input_ids'])
print(f"\n4. Paketin İçindeki Metnin Tam Boy Hali (Decode):")
print(decoded_text[:300] + " ... [ve sonu padding ile bitiyor] ... " + decoded_text[-50:])

