# -*- coding: utf-8 -*-
"""Airflow yedek.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11hKoqzLOBbsKDo3le89DtkOP_SsDnQy3
"""

# ── Bağımlılıklar (pip install pandas faker sqlalchemy) ──────────────────────

import time
import json
import random
import hashlib
import sqlite3
import logging
import tempfile
import pandas as pd
from datetime import datetime, timedelta
from typing import Any, Callable, Dict, List, Optional
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from airflow.models import TaskInstance
from faker import Faker # Uncommented

fake = Faker("tr_TR") # Moved here from tnmY2usfebS_

"""**AIRFLOW**"""

class TaskState(Enum):
    """Task'ın olası durumları (Airflow'da aynı enum mevcuttur)."""
    PENDING   = "pending"    # Henüz çalışmadı
    RUNNING   = "running"    # Şu an çalışıyor
    SUCCESS   = "success"    # Başarıyla tamamlandı
    FAILED    = "failed"     # Hata ile sonuçlandı
    SKIPPED   = "skipped"    # Atlandı

"""=============================================================================
ETL / ELT Pipeline Yönetimi — Apache Airflow Mimarisi Simülasyonu
=============================================================================

Bu dosya, gerçek bir Apache Airflow ortamında nasıl çalışacağını göstermek
için Airflow'un temel bileşenlerini (DAG, Task, Operator, XCom, TaskGroup)
Python ile sıfırdan simüle eder.

Gerçek Airflow ortamında:
  - Bu dosya $AIRFLOW_HOME/dags/ klasörüne kopyalanır.
  - `airflow dags trigger etl_satis_pipeline` komutuyla çalıştırılır.
  - Web UI üzerinden izlenir (localhost:8080).

Simülasyon sayesinde Airflow kurulmadan tüm mimari test edilebilir.

Kullanılan Airflow kavramları:
  ┌─────────────────────────────────────────────────────────────┐
  │  DAG          → Yönlendirilmiş Asiklik Graf (iş akışı)     │
  │  Task         → DAG içindeki tek bir iş birimi             │
  │  PythonOperator → Python fonksiyonu çalıştıran operatör    │
  │  XCom         → Task'lar arası veri paylaşım mekanizması   │
  │  TaskGroup    → Görevleri mantıksal gruplara ayırma         │
  │  Schedule     → Otomatik çalıştırma zamanlaması            │
  └─────────────────────────────────────────────────────────────┘

ETL Akışı:
  [EXTRACT] ──► [TRANSFORM] ──► [LOAD] ──► [VALIDATE] ──► [NOTIFY]
      │               │              │            │
   Ham veri       Temizlik      Hedef DB      Kalite         Rapor
   çekme          Dönüşüm       yazma         kontrolü      gönderme
=============================================================================

**pool çağan**
"""

class AirflowPool:
    def __init__(self, pool_name: str, slots: int):
        self.pool_name = pool_name
        self.slots = slots

    def check_and_apply_backpressure(self, task_id: str):
        print(f"[POOL CHECK] {task_id} -> {self.pool_name}")
        print(f"Kapasite: {self.slots} Slot")
        if self.slots == 1:
            print(f"[BACKPRESSURE] {self.pool_name} kisitli! 3 saniye bekleniyor...")
            time.sleep(3)
            print("Gorev guvenli havuzda tamamlandi.")
        else:
            print("Havuz genis, gecildi.")

kisitli_havuz = AirflowPool(pool_name="kisitli_veri_havuzu", slots=1)

try:
    bulunan_daglar = [v for k, v in globals().items() if isinstance(v, DAG)] or [v for k, v in locals().items() if isinstance(v, DAG)]
    if bulunan_daglar:
        hedef_dag = bulunan_daglar[0]
        mevcut_tasklar = list(hedef_dag.tasks.keys())
        if mevcut_tasklar:
            hedef_task_id = mevcut_tasklar[0]
            hedef_dag.tasks[hedef_task_id].pool = "kisitli_veri_havuzu"
            print(f"Gorev havuzu degistirildi: {hedef_task_id} -> {hedef_dag.tasks[hedef_task_id].pool}")
            kisitli_havuz.check_and_apply_backpressure(hedef_task_id)
            hedef_dag.run()
        else:
            print("DAG icinde gorev bulunamadi.")
    else:
        def dummy_callable(ti): pass
        test_dag = DAG(dag_id="test_pipeline", description="Pool Test", schedule_interval=None, start_date=datetime.now())
        test_task = PythonOperator(task_id="ornek_gorev", python_callable=dummy_callable)
        test_dag.add_task(test_task)
        test_dag.tasks["ornek_gorev"].pool = "kisitli_veri_havuzu"
        kisitli_havuz.check_and_apply_backpressure("ornek_gorev")
        test_dag.run()
except Exception as e:
    print(f"Hata: {e}")

# This cell previously contained import and installation statements.
# These have been moved to the first code cell (9oKbpGNMFBZF) for better organization and dependency management.

# ── Loglama Yapılandırması ───────────────────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s — %(message)s",
  datefmt="%H:%M:%S",
)
log = logging.getLogger("airflow.simulation")


DEFAULT_DB_PATH = str(Path(tempfile.gettempdir()) / "satis_warehouse.db")


# =============================================================================
# ❶  AIRFLOW CORE — Temel Sınıflar (Simülasyon)
# =============================================================================

class TaskState(Enum):
    """Task'ın olası durumları (Airflow'da aynı enum mevcuttur)."""
    PENDING   = "pending"    # Henüz çalışmadı
    RUNNING   = "running"    # Şu an çalışıyor
    SUCCESS   = "success"    # Başarıyla tamamlandı
    FAILED    = "failed"     # Hata ile sonuçlandı
    SKIPPED   = "skipped"    # Atlandı
    TIMEOUT   = "timeout"


@dataclass
class XComStore:
    """
    XCom (Cross-Communication) — Task'lar arası mesaj kutusu.
    Gerçek Airflow'da bu veriler metadata DB'de saklanır.
    Küçük veri paylaşımı için tasarlanmıştır (büyük veri için S3/GCS kullanın).
    """
    _store: Dict[str, Any] = field(default_factory=dict)

    def push(self, task_id: str, key: str, value: Any):
        """Bir task'ın ürettiği veriyi depola."""
        store_key = f"{task_id}::{key}"
        self._store[store_key] = value
        log.debug(f"XCom PUSH → {store_key}")

    def pull(self, task_id: str, key: str) -> Any:
        """Bir task'ın daha önce depoladığı veriyi çek."""
        store_key = f"{task_id}::{key}"
        value = self._store.get(store_key)
        log.debug(f"XCom PULL ← {store_key} = {type(value).__name__}")
        return value


@dataclass
class TaskInstance:
    """
    Airflow TaskInstance: Bir task'ın tek bir çalışma kaydı.
    task_id, dag_id, execution_date bilgilerini tutar.
    """
    task_id: str
    dag_id: str
    execution_date: datetime
    xcom: XComStore
    state: TaskState = TaskState.PENDING
    start_date: Optional[datetime] = None
    end_date: Optional[datetime] = None
    duration: float = 0.0
    log_messages: List[str] = field(default_factory=list)

    def xcom_push(self, key: str, value: Any):
        """Bu task'tan veri yayınla."""
        self.xcom.push(self.task_id, key, value)

    def xcom_pull(self, task_ids: str, key: str) -> Any:
        """Başka bir task'ın verisini çek."""
        return self.xcom.pull(task_ids, key)

    def log_info(self, msg: str):
        self.log_messages.append(msg)
        log.info(f"[{self.task_id}] {msg}")


class PythonOperator:
    """
    Airflow PythonOperator: Python fonksiyonu çalıştıran temel operatör.
    Gerçek kullanım:
        task = PythonOperator(
            task_id='my_task',
            python_callable=my_function,
            op_kwargs={'param': 'value'},
            dag=dag,
        )
    """
    def __init__(
        self,
        task_id: str,
        python_callable: Callable,
        op_kwargs: Optional[Dict] = None,
        retries: int = 1,
        retry_delay: int = 2,  # saniye
        timeout: int = 30,
        priority: int = 1,
        group: str = "default",
    ):
        self.task_id = task_id
        self.python_callable = python_callable
        self.op_kwargs = op_kwargs or {}
        self.retries = retries
        self.retry_delay = retry_delay

        self.priority = priority  #taskalara oncelık ekleme öncesinde hapsi aynı önemdeydi
        self.timeout = timeout

        self.group = group
        self.upstream_tasks: List[str] = []    # Bu task'tan önce çalışacaklar
        self.downstream_tasks: List[str] = []  # Bu task'tan sonra çalışacaklar

    def set_upstream(self, task: "PythonOperator"):
        """Bağımlılık tanımla: self, task'tan SONRA çalışır."""
        if task.task_id not in self.upstream_tasks:
            self.upstream_tasks.append(task.task_id)
        if self.task_id not in task.downstream_tasks:
            task.downstream_tasks.append(self.task_id)

    def __rshift__(self, other: "PythonOperator"):
        """>> operatörü: task1 >> task2 şeklinde bağımlılık tanımlar."""
        other.set_upstream(self)
        return other


class DAG:
    """
    Airflow DAG (Directed Acyclic Graph): Tüm iş akışının konteyneri.

    Gerçek Airflow'da DAG dosyası $AIRFLOW_HOME/dags/ içine konur ve
    scheduler periyodik olarak tarar.

    Örnek schedule değerleri:
        "@daily"      → Her gün gece yarısı
        "@hourly"     → Her saat başı
        "0 6 * * *"   → Her gün 06:00'da (cron syntax)
        None          → Manuel tetikleme
    """
    def __init__(
        self,
        dag_id: str,
        description: str,
        schedule_interval: Optional[str],
        start_date: datetime,
        catchup: bool = False,
        tags: Optional[List[str]] = None,
        default_args: Optional[Dict] = None,
    ):
        self.dag_id = dag_id
        self.description = description
        self.schedule_interval = schedule_interval
        self.start_date = start_date
        self.catchup = catchup
        self.tags = tags or []
        self.default_args = default_args or {}
        self.tasks: Dict[str, PythonOperator] = {}

    def add_task(self, task: PythonOperator):
        """DAG'a görev ekle."""
        self.tasks[task.task_id] = task

    def run(self, execution_date: Optional[datetime] = None) -> Dict[str, Any]:
        """
        DAG'ı çalıştır — topolojik sıralama ile görevleri işle.
        Gerçek Airflow'da bu işi Executor (LocalExecutor, CeleryExecutor) yapar.
        """
        execution_date = execution_date or datetime.now()
        xcom = XComStore()

        print("\n" + "═" * 70)
        print(f"  🚀  DAG ÇALIŞIYOR: {self.dag_id}")
        print(f"  📅  Execution Date: {execution_date.strftime('%Y-%m-%d %H:%M:%S')}")
        print(f"  📋  Açıklama: {self.description}")
        print("═" * 70)

        # Topolojik sıralama (bağımlılık sırasına göre çalıştır)
        ordered = self._topological_sort()   ###_topological_sort() yapılıyor
        results: Dict[str, TaskInstance] = {}
        dag_start = time.time()

        for task_id in ordered:
            task = self.tasks[task_id]
            ti = TaskInstance(
                task_id=task_id,
                dag_id=self.dag_id,
                execution_date=execution_date,
                xcom=xcom,
            )

            # Upstream task'ların başarılı olup olmadığını kontrol et
            failed_upstream = [
                uid for uid in task.upstream_tasks
                if results.get(uid) and results[uid].state == TaskState.FAILED
            ]
            if failed_upstream:
                ti.state = TaskState.SKIPPED
                ti.log_info(f"Atlandı — başarısız upstream: {failed_upstream}")
                results[task_id] = ti
                continue

            # Task'ı retry mantığıyla çalıştır
            self._execute_task(task, ti)
            results[task_id] = ti

        # Özet raporu
        dag_duration = time.time() - dag_start
        self._print_summary(results, dag_duration)
        return results

    def _execute_task(self, task: PythonOperator, ti: TaskInstance):
        """Tek bir task'ı yeniden deneme (retry) desteğiyle çalıştır."""
        group_icon = {"extract": "📥", "transform": "⚙️",
                      "load": "💾", "validate": "✅", "notify": "📣"
                      }.get(task.group, "🔧")

        print(f"\n  {group_icon}  Task: {ti.task_id}  [{task.group.upper()}]")
        print(f"      {'─' * 50}")

        for attempt in range(task.retries + 1):
            try:
                ti.state = TaskState.RUNNING
                ti.start_date = datetime.now()

                # Asıl fonksiyonu çalıştır — ti (TaskInstance) inject et
                task.python_callable(ti=ti, **task.op_kwargs)

                ti.end_date = datetime.now()
                ti.duration = (ti.end_date - ti.start_date).total_seconds()
                ti.state = TaskState.SUCCESS
                print(f"      ✓  Süre: {ti.duration:.2f}s")
                return

            except Exception as exc:
                if attempt < task.retries:
                    ti.log_info(f"Hata (deneme {attempt+1}/{task.retries}): {exc}")
                    print(f"      ⚠  Yeniden deneniyor ({attempt+1}/{task.retries})...")
                    time.sleep(task.retry_delay)
                else:
                    ti.end_date = datetime.now()
                    ti.duration = (ti.end_date - ti.start_date).total_seconds()
                    ti.state = TaskState.FAILED
                    ti.log_info(f"BAŞARISIZ: {exc}")
                    print(f"      ✗  HATA: {exc}")

    def _topological_sort(self) -> List[str]:
        """Kahn algoritması ile topolojik sıralama."""

        in_degree = {tid: 0 for tid in self.tasks}

        for task in self.tasks.values():
            for downstream in task.downstream_tasks:
                if downstream in in_degree:
                    in_degree[downstream] += 1

        queue = [tid for tid, deg in in_degree.items() if deg == 0]

        # Önceliğe göre sırala
        queue.sort(
            key=lambda tid: self.tasks[tid].priority,
            reverse=True
        )

        ordered = []

        while queue:
            tid = queue.pop(0)
            ordered.append(tid)

            for downstream in self.tasks[tid].downstream_tasks:
                if downstream in in_degree:
                    in_degree[downstream] -= 1

                    if in_degree[downstream] == 0:
                        queue.append(downstream)

            # Kuyruğu tekrar önceliğe göre sırala
            queue.sort(
                key=lambda tid: self.tasks[tid].priority,
                reverse=True
            )

        return ordered

    def _print_summary(self, results: Dict[str, TaskInstance], duration: float):
        """Pipeline sonuç özetini yazdır."""
        success = sum(1 for ti in results.values() if ti.state == TaskState.SUCCESS)
        failed  = sum(1 for ti in results.values() if ti.state == TaskState.FAILED)
        skipped = sum(1 for ti in results.values() if ti.state == TaskState.SKIPPED)

        print("\n" + "═" * 70)
        print(f"  📊  DAG TAMAMLANDI: {self.dag_id}")
        print(f"  ⏱   Toplam süre  : {duration:.2f} saniye")
        print(f"  ✅  Başarılı     : {success} task")
        print(f"  ❌  Başarısız    : {failed} task")
        print(f"  ⏭   Atlandı      : {skipped} task")
        print("═" * 70 + "\n")
# =============================================================================
# ❷  EXTRACT — Veri Çekme Görevleri (Gelişmiş Senaryo)
# =============================================================================

def extract_logistics_data(ti: TaskInstance, source_system: str = "SAP_ERP"):
    """
    [EXTRACT TASK] Global lojistik sisteminden sevkiyat verilerini çek.
    Senaryo: Farklı ülkelerden gelen, para birimleri karışık ve
    bazı alanları eksik (kirli) veriyi simüle eder.
    """
    # Airflow'da get_dagrun() metodu TaskInstance sınıfında bulunur.
    # Bu metot, TaskInstance nesnesine erişim sağlar.
    # Simülasyon ortamında get_dagrun() metodunu TaskInstance sınıfına eklememiz gerekiyor.
    # Şu anki simülasyonda execution_date doğrudan TaskInstance içinde mevcut.
    # Aşağıdaki satırı kaldırıp doğrudan ti.execution_date kullanacağız:
    # execution_date = ti.get_dagrun().execution_date.strftime("%Y-%m-%d %H:%M")
    execution_date_str = ti.execution_date.strftime("%Y-%m-%d %H:%M")
    ti.log_info(f"--- {source_system} sisteminden veri çekme işlemi başladı ---")
    ti.log_info(f"Veri çekme periyodu: {execution_date_str}")

    # 1. Veri Simülasyonu (Gerçekçi Kirli Veri Seti)
    records = []
    countries = ["TR", "US", "DE", "CN", "UK"]
    carriers = ["DHL", "FedEx", "UPS", "Aras", "Ptt"]

    for i in range(200):
        # Bilinçli olarak bazı kayıtları "bozuk" oluşturuyoruz (Transform testi için)
        is_corrupted = random.random() < 0.1  # %10 ihtimalle kirli veri

        records.append({
            "tracking_id"  : f"TRK-{random.randint(100000, 999999)}",
            "order_id"     : fake.uuid4() if not is_corrupted else None, # Null ID hatası
            "origin"       : random.choice(countries),
            "destination"  : random.choice(countries),
            "carrier"      : random.choice(carriers),
            "weight_kg"    : round(random.uniform(0.5, 500.0), 2),
            "shipping_cost": round(random.uniform(5.0, 150.0), 2),
            "currency"     : "USD" if random.random() > 0.2 else "EUR", # Karışık para birimi
            "status"       : random.choice(["In Transit", "Delivered", "Returned", "Lost", "pending"]),
            "extracted_at" : datetime.now().isoformat()
        })

    df = pd.DataFrame(records)

    # 2. Veri Kaynağı Sağlık Kontrolü (Data Quality Check 1)
    if df['tracking_id'].duplicated().any():
        ti.log_info("Dikkat: Çekilen veride mükerrer tracking_id tespit edildi!") # log.warning yerine log_info

    # 3. Metadata ekle ve XCom'a gönder
    # Veriyi JSON'a çevirirken 'iso' date formatını koruyoruz
    ti.xcom_push(key="raw_logistics_data", value=df.to_json(orient="records"))
    ti.xcom_push(key="source_info", value={"system": source_system, "row_count": len(df)})

    ti.log_info(f"İşlem Tamamlandı: {len(df)} adet sevkiyat kaydı XCom'a basıldı.")


def extract_warehouse_stock(ti: TaskInstance):
    """
    [EXTRACT TASK] Depo stok yönetim sisteminden (WMS) anlık stok verisi çek.
    Senaryo: Kritik stok seviyesi kontrolü ve hata yönetimi içerir.
    """
    ti.log_info("Depo (WMS) API bağlantısı kuruluyor...")

    # API'den veri gelmediği veya boş geldiği durumu simüle edelim
    # Şans eseri hata fırlatmak için:
    if random.random() < 0.05: # %5 ihtimalle sistem hatası simülasyonu
        ti.log_info("Kritik Hata: WMS API yanıt vermiyor (Timeout)!") # log.error yerine log_info
        raise Exception("Depo yönetim sistemine erişilemedi. Pipeline durduruluyor.")

    # Gerçekçi stok verisi
    stock_data = [
        {
            "sku"          : f"SKU-{random.randint(1000, 2000)}",
            "warehouse_id" : random.choice(["IST-01", "ANK-02", "IZM-03"]),
            "stock_level"  : random.randint(0, 1000),
            "reorder_point": 50,
            "last_updated" : datetime.now().isoformat()
        }
        for _ in range(50)
    ]

    df_stock = pd.DataFrame(stock_data)

    # İş Mantığı Kontrolü: Eğer tüm stoklar 0 ise bir terslik vardır
    if df_stock["stock_level"].sum() == 0:
        ti.log_info("Veri Tutarsızlığı: Tüm stok seviyeleri 0 görünüyor. Kaynak veriyi kontrol edin!") # log.error yerine log_info
        raise ValueError("Anormal veri: Boş stok verisi çekildi.")

    # XCom Push
    ti.xcom_push(key="inventory_data", value=df_stock.to_json(orient="records"))
    ti.log_info(f"Stok verisi başarıyla çekildi. Toplam SKU sayısı: {len(df_stock)}")

    # Transform aşamasına ipucu gönder (Context Injection)
    ti.xcom_push(key="low_stock_threshold", value=20)

import time
import random
import logging
import tempfile
from datetime import datetime
from typing import Any, Callable, Dict, List, Optional
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path

import pandas as pd
from faker import Faker

# =============================================================================
# LOGGING
# =============================================================================

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s — %(message)s",
    datefmt="%H:%M:%S",
)

log = logging.getLogger("airflow.simulation")
fake = Faker("tr_TR")

DEFAULT_DB_PATH = str(Path(tempfile.gettempdir()) / "satis_warehouse.db")

# =============================================================================
# AIRFLOW CORE
# =============================================================================

class TaskState(Enum):
    PENDING = "pending"
    RUNNING = "running"
    SUCCESS = "success"
    FAILED = "failed"
    SKIPPED = "skipped"
    TIMEOUT = "timeout"


@dataclass
class XComStore:
    _store: Dict[str, Any] = field(default_factory=dict)

    def push(self, task_id: str, key: str, value: Any):
        self._store[f"{task_id}::{key}"] = value

    def pull(self, task_id: str, key: str) -> Any:
        return self._store.get(f"{task_id}::{key}")


@dataclass
class TaskInstance:
    task_id: str
    dag_id: str
    execution_date: datetime
    xcom: XComStore
    state: TaskState = TaskState.PENDING
    start_date: Optional[datetime] = None
    end_date: Optional[datetime] = None
    duration: float = 0.0

    def xcom_push(self, key: str, value: Any):
        self.xcom.push(self.task_id, key, value)

    def xcom_pull(self, task_ids: str, key: str) -> Any:
        return self.xcom.pull(task_ids, key)

    def log_info(self, msg: str):
        log.info(f"[{self.task_id}] {msg}")


# =============================================================================
# PYTHON OPERATOR
# =============================================================================

class PythonOperator:
    def __init__(
        self,
        task_id: str,
        python_callable: Callable,
        op_kwargs: Optional[Dict] = None,
        retries: int = 1,
        retry_delay: int = 2,
        timeout: int = 30,
        priority: int = 1,
        group: str = "default",
    ):
        self.task_id = task_id
        self.python_callable = python_callable
        self.op_kwargs = op_kwargs or {}

        self.retries = retries
        self.retry_delay = retry_delay
        self.timeout = timeout
        self.priority = priority
        self.group = group

        self.upstream_tasks: List[str] = []
        self.downstream_tasks: List[str] = []

    def set_upstream(self, task: "PythonOperator"):
        if task.task_id not in self.upstream_tasks:
            self.upstream_tasks.append(task.task_id)
        if self.task_id not in task.downstream_tasks:
            task.downstream_tasks.append(self.task_id)

    def __rshift__(self, other: "PythonOperator"):
        other.set_upstream(self)
        return other


# =============================================================================
# DAG
# =============================================================================

class DAG:
    def __init__(
        self,
        dag_id: str,
        description: str,
        schedule_interval: Optional[str],
        start_date: datetime,
        catchup: bool = False,
    ):
        self.dag_id = dag_id
        self.description = description
        self.schedule_interval = schedule_interval
        self.start_date = start_date
        self.catchup = catchup
        self.tasks: Dict[str, PythonOperator] = {}

    def add_task(self, task: PythonOperator):
        self.tasks[task.task_id] = task

    def run(self, execution_date: Optional[datetime] = None):
        execution_date = execution_date or datetime.now()
        xcom = XComStore()

        print(f"\n🚀 DAG: {self.dag_id}\n")

        ordered = self._topological_sort()
        results = {}
        dag_start = time.time()

        for task_id in ordered:
            task = self.tasks[task_id]

            ti = TaskInstance(
                task_id=task_id,
                dag_id=self.dag_id,
                execution_date=execution_date,
                xcom=xcom,
            )

            self._execute_task(task, ti)
            results[task_id] = ti

        print(f"\n⏱ DAG tamamlandı: {time.time() - dag_start:.2f}s")
        return results

    # =========================
    # PRIORITY + TOPO SORT FIX
    # =========================
    def _topological_sort(self):
        in_degree = {tid: 0 for tid in self.tasks}

        for task in self.tasks.values():
            for d in task.downstream_tasks:
                in_degree[d] += 1

        queue = [tid for tid, deg in in_degree.items() if deg == 0]

        queue.sort(key=lambda x: self.tasks[x].priority, reverse=True)

        ordered = []

        while queue:
            tid = queue.pop(0)
            ordered.append(tid)

            for d in self.tasks[tid].downstream_tasks:
                in_degree[d] -= 1
                if in_degree[d] == 0:
                    queue.append(d)

            queue.sort(key=lambda x: self.tasks[x].priority, reverse=True)

        return ordered

    # =========================
    # EXECUTION (RETRY + TIMEOUT)
    # =========================
    def _execute_task(self, task: PythonOperator, ti: TaskInstance):

        for attempt in range(task.retries + 1):
            try:
                ti.state = TaskState.RUNNING
                ti.start_date = datetime.now()

                start = time.time()

                task.python_callable(ti=ti, **task.op_kwargs)

                duration = time.time() - start

                if duration > task.timeout:
                    raise TimeoutError("Task timeout")

                ti.end_date = datetime.now()
                ti.duration = duration
                ti.state = TaskState.SUCCESS

                print(f"✔ {task.task_id} → {duration:.2f}s")
                return

            except Exception as e:
                if attempt < task.retries:
                    wait = task.retry_delay * (2 ** attempt)
                    print(f"⚠ retry {attempt+1}, wait {wait}s")
                    time.sleep(wait)
                else:
                    ti.state = TaskState.FAILED
                    ti.end_date = datetime.now()
                    print(f"✗ FAILED: {e}")


# =============================================================================
# EXTRACT TASKS (DÜZELTİLMİŞ - log.info -> log_info)
# =============================================================================

def extract_logistics_data(ti: TaskInstance, source_system: str = "SAP_ERP"):
    ti.log_info(f"{source_system} veri çekiliyor")

    records = []
    for _ in range(200):
        records.append({
            "tracking_id": f"TRK-{random.randint(100000,999999)}",
            "order_id": fake.uuid4(),
            "amount": random.randint(10, 1000),
        })

    df = pd.DataFrame(records)

    ti.xcom_push("raw_logistics", df.to_json())
    ti.log_info(f"{len(df)} kayıt çekildi")


def extract_warehouse_stock(ti: TaskInstance):

    if random.random() < 0.05:
        raise Exception("WMS error")

    stock = pd.DataFrame([
        {"sku": f"SKU-{i}", "stock": random.randint(0, 100)}
        for i in range(50)
    ])

    ti.xcom_push("stock", stock.to_json())
    ti.log_info("stock çekildi")


# =============================================================================
# DAG SETUP (BURASI KRİTİK)
# =============================================================================

dag = DAG(
    dag_id="etl_pipeline",
    description="Airflow simulation",
    schedule_interval="@daily",
    start_date=datetime(2024, 1, 1),
)

extract_logistics = PythonOperator(
    task_id="extract_logistics",
    python_callable=extract_logistics_data,
    retries=2,
    timeout=10,
    priority=10,
    group="extract"
)

extract_warehouse = PythonOperator(
    task_id="extract_warehouse",
    python_callable=extract_warehouse_stock,
    retries=2,
    timeout=10,
    priority=5,
    group="extract"
)

dag.add_task(extract_logistics)
dag.add_task(extract_warehouse)

extract_logistics >> extract_warehouse


# RUN
if __name__ == "__main__":
    dag.run()