# -*- coding: utf-8 -*-
"""glovevs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wLUEcIplqImy1m9wBJbK1TjCCRgW0a7Q
"""

pip install numpy mittens gensim

import numpy as np
from collections import defaultdict
from mittens import Mittens
from gensim.models import KeyedVectors

import warnings
warnings.filterwarnings("ignore")

from gensim.models import KeyedVectors
from mittens import Mittens
import numpy as np

print(" Kütüphaneler yüklendi!\n")

sentences_tr = [
    ["bu", "ürün", "harika", "kesinlikle", "tavsiye", "ederim"],
    ["kargo", "çok", "hızlı", "paketleme", "özenli", "geldi"],
    ["kumaşı", "kaliteli", "harika", "bir", "ürün"],
    ["hızlı", "teslimat", "için", "teşekkür", "ederim"],
    ["kesinlikle", "rezalet", "bir", "ürün", "tavsiye", "etmem"],
    ["kargo", "çok", "yavaş", "paketleme", "kötü", "geldi"],
    ["kalitesiz", "kumaş", "kesinlikle", "beğenmedim"],
    ["müşteri", "hizmetleri", "kötü", "hiç", "yardımcı", "olmadı"]
]

print("1. Adım: Yeni Kelimeler İçin Birlikte Geçiş Matrisi Oluşturuluyor...")

vocab = list(set(word for sentence in sentences_tr for word in sentence))
word2idx = {word: idx for idx, word in enumerate(vocab)}

co_matrix = np.zeros((len(vocab), len(vocab)))
window_size = 2

