# -*- coding: utf-8 -*-
"""LSTM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ArxnMyX7EhkpShx17paty87cosdYSVvl
"""

# Yüksek performanslı pip için güncelleyelim
!pip install --upgrade pip

# Çakışmaları önlemek için önemli kütüphaneleri kaldıralım
!pip uninstall -y numpy torch torchtext pandas

# Bilinen uyumlu versiyonları yükleyelim
# İlk olarak numpy ve pandas'ı yükleyelim.
!pip install numpy==1.26.4 pandas==2.2.2

# Ardından torch ve torchtext'i yükleyelim (Colab'ın varsayılan CUDA versiyonu ile uyumlu versiyonlar tercih edilmelidir)
# Burada belirtilen versiyonlar örnek olup, ortamınıza göre değişiklik gösterebilir.
# Hata durumunda sadece !pip install torchtext yazarak Colab'ın uyumlu versiyonu seçmesine izin verebilirsiniz.
!pip install torch==2.2.0 torchtext==0.16.2

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader, random_split

import torchtext
from torchtext.data.utils import get_tokenizer
from torchtext.vocab import build_vocab_from_iterator

import numpy as np
import pandas as pd

from tqdm import tqdm
import matplotlib.pyplot as plt

# Sabit tohumlama (reproducibility)
SEED = 42
torch.manual_seed(SEED)
np.random.seed(SEED)

print(f"✓ numpy sürümü: {np.__version__}")
print(f"✓ pandas sürümü: {pd.__version__}")
print(f"✓ torch sürümü: {torch.__version__}")
print(f"✓ torchtext sürümü: {torchtext.__version__}")

"""## 1. Veri Yükleme ve Ön İşleme

IMDB duygu analizi datasetini yükleyip ön işleme adımlarını gerçekleştireceğiz.
"""

df = pd.read_csv('/content/IMDB Dataset.csv')
print("Veri Setinin İlk 5 Satırı:")
display(df.head())
print("\nVeri Seti Bilgileri:")
df.info()

"""### 1.1 Tokenizasyon ve Kelime Dağarcığı Oluşturma

Metinleri kelimelere ayırmak için bir tokenizatör ve bu kelimelerden bir kelime dağarcığı (`vocab`) oluşturacağız. `VOCAB_SIZE` değerini `IMDBPyTorchLSTMClassifier` tanımında belirttiğiniz gibi kullanacağız.
"""

# İngilizce metinler için basit bir tokenizatör
tokenizer = get_tokenizer('basic_english')

# Yorumları token'lara ayırıp bir iterator oluşturalım
def yield_tokens(data_iter):
    for text in data_iter:
        yield tokenizer(text)

# VOCAB_SIZE, er47jQpk4rmV hücresinde IMDBPyTorchLSTMClassifier için tanımlandı.
# Eğer bu hücreden önce çalıştırılacaksa, VOCAB_SIZE'ın burada da tanımlı olması gerekir.
# Şu anki akışta, er47jQpk4rmV öncesinde bu adım geldiği için VOCAB_SIZE'ı burada tanımlıyoruz.
# Bu, er47jQpk4rmV'deki tanımı geçersiz kılar, ancak genel akışta sorun yaratmaz.
# Eğer istenirse, VOCAB_SIZE'ın tek bir yerde tanımlanıp her yerden erişilmesi sağlanabilir.
VOCAB_SIZE = 10000 # IMDB sözlüğündeki benzersiz kelime limiti (er47jQpk4rmV ile aynı)

vocab = build_vocab_from_iterator(yield_tokens(df['review']),
                                  min_freq=5, # En az 5 kez geçen kelimeleri al
                                  specials=['<unk>', '<pad>'],
                                  max_tokens=VOCAB_SIZE)

vocab.set_default_index(vocab['<unk>'])

print(f"Oluşturulan kelime dağarcığının boyutu: {len(vocab)}")
print(f"İlk 10 kelime: {vocab.get_itos()[:10]}")
print(f"'harika' kelimesinin indeksi: {vocab(['harika'])}") # Türkçe kelimeler nasıl işleniyor diye bakalım
print(f"'wonderful' kelimesinin indeksi: {vocab(['wonderful'])}")

# Duygu etiketlerini sayısal değerlere dönüştürelim
sentiment_map = {'positive': 1, 'negative': 0}
df['sentiment_encoded'] = df['sentiment'].map(sentiment_map)

"""### 1.2 Metinleri Sayısal Dizilere Dönüştürme ve Doldurma (Padding)

Şimdi yorumları kelime ID'lerine çevirecek ve tüm dizileri sabit bir uzunluğa getireceğiz. LSTM'in girdisi için `max_seq_len`'ı belirleyelim.
"""

MAX_SEQ_LEN = 256 # Tüm dizileri 256 uzunluğuna sabitleyelim

def text_pipeline(text):
    return vocab(tokenizer(text))

def pad_sequence(seq, max_len, padding_value):
    if len(seq) > max_len:
        return seq[:max_len]
    else:
        return seq + [padding_value] * (max_len - len(seq))

# Metinleri ID dizilerine çevir ve pad et
padded_reviews = []
for review in tqdm(df['review'], desc='Reviews processing'):
    token_ids = text_pipeline(review)
    padded_reviews.append(pad_sequence(token_ids, MAX_SEQ_LEN, vocab['<pad>']))

df['review_indexed'] = padded_reviews

print(f"\nİlk yorumun indekslenmiş ve padlenmiş hali (ilk 10 ID): {df['review_indexed'].iloc[0][:10]}")
print(f"İlk yorumun uzunluğu: {len(df['review_indexed'].iloc[0])}")
print(f"Duygu etiketleri:")
display(df[['sentiment', 'sentiment_encoded']].head())

"""### 1.3 Verileri PyTorch Tensorlarına Dönüştürme ve DataLoader Oluşturma

Ön işlenmiş verileri PyTorch tensorlarına çevirecek ve model eğitimi için `DataLoader` nesneleri oluşturacağız.
"""

BATCH_SIZE = 64

# Yorum indekslerini ve etiketleri PyTorch tensorlarına dönüştürelim
x = torch.tensor(df['review_indexed'].tolist(), dtype=torch.long)
y = torch.tensor(df['sentiment_encoded'].tolist(), dtype=torch.long)

# Dataset oluşturalım
dataset = TensorDataset(x, y)

# Veriyi eğitim ve doğrulama setlerine ayıralım
train_size = int(0.8 * len(dataset))
val_size = len(dataset) - train_size
train_dataset, val_dataset = random_split(dataset, [train_size, val_size])

# DataLoader'ları oluşturalım
train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=BATCH_SIZE, shuffle=False)

print(f"Eğitim seti boyutu: {len(train_dataset)}")
print(f"Doğrulama seti boyutu: {len(val_dataset)}")
print(f"Eğitim DataLoader'ından bir örnek batch (x şekli): {next(iter(train_loader))[0].shape}")
print(f"Eğitim DataLoader'ından bir örnek batch (y şekli): {next(iter(train_loader))[1].shape}")

import numpy as np
import torch
import torch.nn as nn
import matplotlib.pyplot as plt
from matplotlib.gridspec import GridSpec

# =====================================================================
# BÖLÜM 1: SIFIRDAN NUMPY ILE LSTM CLASSIFIER & GÖRSELLEŞTİRME VERİSİ
# =====================================================================

def sigmoid(x):
    """Sigmoid aktivasyon fonksiyonu. Değerleri [0, 1] arasına sıkıştırır."""
    return 1 / (1 + np.exp(-x))

class IMDBVanillaLSTMClassifier:
    """
    Sıfırdan NumPy ile yazılmış IMDB Duygu Analizi Sınıflandırıcısı.
    Toplu veri (Batch) işlemeyi ve kapı analizlerini çıkarmayı destekler.
    """

    def __init__(self, input_size: int, hidden_size: int, num_classes: int = 2):
        """
        Parametreler:
            input_size  (D): Her kelimenin embedding (vektör) boyutu
            hidden_size (H): LSTM'in iç hafıza boyutu
            num_classes (C): Sınıf sayısı (IMDB için 2: Pozitif/Negatif)
        """
        rng = np.random.default_rng(42)
        H, D = hidden_size, input_size
        scale = 0.1

        # ── 4 Kapı Ağırlık Matrisleri (H, H+D) ──────────────────────────
        self.W_f = rng.standard_normal((H, H + D)) * scale
        self.W_i = rng.standard_normal((H, H + D)) * scale
        self.W_g = rng.standard_normal((H, H + D)) * scale
        self.W_o = rng.standard_normal((H, H + D)) * scale

        # ── Bias Vektörleri (H,) ─────────────────────────────────────────
        self.b_f = np.ones(H)    # Hafızayı korumak için 1.0 ile başlıyoruz
        self.b_i = np.zeros(H)
        self.b_g = np.zeros(H)
        self.b_o = np.zeros(H)

        # ── Sınıflandırma (Linear / FC) Katmanı Ağırlıkları ──────────────
        self.W_fc = rng.standard_normal((num_classes, H)) * scale
        self.b_fc = np.zeros(num_classes)

        self.hidden_size = H
        self.input_size  = D
        self.num_classes = num_classes

    def _concat(self, h_prev, x_t):
        """Batch uyumlu yan yana birleştirme: (batch_size, H) + (batch_size, D) → (batch_size, H+D)"""
        return np.concatenate([h_prev, x_t], axis=1)

    def forward_step(self, x_t, h_prev, c_prev):
        """Tüm Batch için TEK bir zaman adımını işler."""
        combined = self._concat(h_prev, x_t)

        # Kapı Hesaplamaları: (batch_size, H+D) @ (H+D, H) → (batch_size, H)
        f_t = sigmoid(combined @ self.W_f.T + self.b_f)
        i_t = sigmoid(combined @ self.W_i.T + self.b_i)
        g_t = np.tanh(combined @ self.W_g.T + self.b_g)
        o_t = sigmoid(combined @ self.W_o.T + self.b_o)

        # Hücre ve Gizli durum güncellemeleri
        c_t = f_t * c_prev + i_t * g_t
        h_t = o_t * np.tanh(c_t)

        gates = {"f": f_t, "i": i_t, "g": g_t, "o": o_t}
        return h_t, c_t, gates

    def forward_sequence(self, X):
        """Tam bir veri paketini (Batch) baştan sona işler ve tüm adımları kaydeder."""
        batch_size, seq_len, _ = X.shape

        h = np.zeros((batch_size, self.hidden_size))
        c = np.zeros((batch_size, self.hidden_size))

        H_list, C_list, gates_list = [], [], []

        for t in range(seq_len):
            x_t = X[:, t, :]
            h, c, gates = self.forward_step(x_t, h, c)
            H_list.append(h.copy())
            C_list.append(c.copy())
            gates_list.append(gates)

        # Sınıflandırma katmanından geçiş (Sadece en son adımın h_t'si kullanılır)
        logits = h @ self.W_fc.T + self.b_fc

        # Matplotlib görselleştirmesi için şekilleri (seq_len, batch_size, hidden_size) formatına getiriyoruz
        return logits, np.array(H_list), np.array(C_list), gates_list

# =====================================================================
# BÖLÜM 2: NUMPY VERİLERİ İLE KAPILARIN GÖRSELLEŞTİRİLMESİ
# =====================================================================

INPUT_SIZE  = 50  # Kelime embedding boyutu
HIDDEN_SIZE = 32  # LSTM gizli nörön sayısı
SEQ_LEN     = 10  # Cümle uzunluğu (Zaman adımı)
BATCH_SIZE  = 4   # Batch boyutu

# Test için sentetik veri üretelim
X_numpy = np.random.randn(BATCH_SIZE, SEQ_LEN, INPUT_SIZE)
np_classifier = IMDBVanillaLSTMClassifier(INPUT_SIZE, HIDDEN_SIZE, num_classes=2)

# Modeli çalıştırıp tüm geçmiş verileri alalım
logits_np, H_out_seq, C_out_seq, gates_all = np_classifier.forward_sequence(X_numpy)

# Görselleştirme için 1. örneğin (Batch içindeki ilk cümlenin) verilerini seçelim
sample_idx = 0
H_sample = H_out_seq[:, sample_idx, :]  # Şekil: (seq_len, hidden_size)
C_sample = C_out_seq[:, sample_idx, :]  # Şekil: (seq_len, hidden_size)

# Kapıların ortalamasını ilk örnek (sample_idx) üzerinden hesaplayalım
gate_means = {k: [] for k in ["f", "i", "g", "o"]}
for step_gates in gates_all:
    for k in gate_means:
        # step_gates[k] şekli: (batch_size, hidden_size). Biz 0. indeksli örneğin ortalamasını alıyoruz.
        gate_means[k].append(step_gates[k][sample_idx].mean())

# Grafik Tasarım Alanı (GridSpec)
fig = plt.figure(figsize=(16, 10))
gs  = GridSpec(3, 2, figure=fig, hspace=0.45, wspace=0.35)

# ── 1. Grafik: Kapı aktivasyonları zaman içinde ─────────────────────────────
ax1 = fig.add_subplot(gs[0, :])
colors_g = {"f": "#E24B4A", "i": "#1D9E75", "g": "#534AB7", "o": "#BA7517"}
labels_g = {
    "f": "Unutma (f_t) — 'eski hafızadan ne kalsın?'",
    "i": "Giriş  (i_t) — 'yeni bilgiden ne eklensin?'",
    "g": "Aday   (g_t) — 'eklenecek değer nedir?'",
    "o": "Çıkış  (o_t) — 'hücreyi ne kadar göster?'"
}
for k, vals in gate_means.items():
    ax1.plot(vals, "o-", label=labels_g[k], color=colors_g[k], linewidth=2, markersize=7)
ax1.axhline(0.5, color="gray", linestyle="--", alpha=0.4, label="0.5 referans")
ax1.set_title("4 Kapı — Ortalama Aktivasyon (her adım)", fontsize=12)
ax1.set_xlabel("Zaman adımı (t)"); ax1.set_ylabel("Ortalama değer")
ax1.legend(fontsize=9, loc="upper right"); ax1.grid(alpha=0.3)

# ── 2. Grafik: h_t ısı haritası (Kısa Hafıza) ───────────────────────────────
ax2 = fig.add_subplot(gs[1, 0])
im2 = ax2.imshow(H_sample.T, aspect="auto", cmap="RdYlBu_r", vmin=-1, vmax=1)
ax2.set_title("Gizli Durum h_t\n(kısa vadeli hafıza)", fontsize=11)
ax2.set_xlabel("Zaman adımı"); ax2.set_ylabel("Gizli boyut")
plt.colorbar(im2, ax=ax2, fraction=0.046)

# ── 3. Grafik: c_t ısı haritası (Uzun Hafıza) ───────────────────────────────
ax3 = fig.add_subplot(gs[1, 1])
im3 = ax3.imshow(C_sample.T, aspect="auto", cmap="RdYlBu_r")
ax3.set_title("Hücre Durumu c_t\n(uzun vadeli hafıza)", fontsize=11)
ax3.set_xlabel("Zaman adımı"); ax3.set_ylabel("Hücre boyutu")
plt.colorbar(im3, ax=ax3, fraction=0.046)

# ── 4. Grafik: Norm karşılaştırması ──────────────────────────────────────────
ax4 = fig.add_subplot(gs[2, :])
h_norms = [np.linalg.norm(H_sample[t]) for t in range(SEQ_LEN)]
c_norms = [np.linalg.norm(C_sample[t]) for t in range(SEQ_LEN)]
ax4.plot(h_norms, "o-", label="‖h_t‖ gizli (kısa hafıza)", color="#534AB7", lw=2, ms=7)
ax4.plot(c_norms, "s--", label="‖c_t‖ hücre (uzun hafıza)", color="#E24B4A", lw=2, ms=7)
ax4.set_title("Gizli vs Hücre Durumu — L2 Norm\n"
              "c_t büyüyorsa: uzun hafıza bilgi biriktiriyor", fontsize=11)
ax4.set_xlabel("Zaman adımı"); ax4.set_ylabel("L2 normu")
ax4.legend(fontsize=10); ax4.grid(alpha=0.3)

plt.suptitle("VanillaLSTMCell — Kapı ve Durum Görselleştirmesi (IMDB Örneği)", fontsize=13)
plt.tight_layout()
plt.show()
print("Görselleştirme Başarıyla Çizildi! ✓\n")


# =====================================================================
# BÖLÜM 3: IMDB PROJESİ İÇİN ESAS PYTORCH MODELİ (PROJEDE KULLANILACAK)
# =====================================================================

class IMDBPyTorchLSTMClassifier(nn.Module):
    """
    Dizi (Kelime İndeksleri) → Etiket Sınıflandırması.
    Mimari: Girdi → Embedding (Kelime Vektörü) → LSTM (2 Katman) → Dropout → Linear → Sınıf
    """

    def __init__(self, vocab_size, embedding_dim, hidden_size, num_classes=2,
                 num_layers=2, dropout=0.3):
        """
        super().__init__() zorunluluğu:
        → nn.Module'ün iç kayıt defterini kurar ve parametreleri izlenebilir kılar.
        """
        super().__init__()

        # 1. Metin Projeleri İçin Gerekli Embedding Katmanı
        # Kelime ID'lerini yoğun anlamsal vektörlere dönüştürür.
        self.embedding = nn.Embedding(num_embeddings=vocab_size, embedding_dim=embedding_dim)

        # 2. PyTorch Hazır LSTM Katmanı
        self.lstm = nn.LSTM(
            input_size  = embedding_dim, # LSTM girdisi artık embedding vektör boyutudur
            hidden_size = hidden_size,
            num_layers  = num_layers,
            batch_first = True,          # Girdi düzeni: (batch, seq, feat)
            dropout     = dropout if num_layers > 1 else 0,
        )

        # 3. Dropout Katmanı (Aşırı öğrenmeyi - Overfitting engellemek için)
        self.dropout = nn.Dropout(dropout)

        # 4. Tam Bağlı (Linear) Çıkış Katmanı
        # Son zaman adımındaki özet bilgiyi (hidden_size) alıp sınıf skorlarına dönüştürür.
        self.fc = nn.Linear(hidden_size, num_classes)

    def forward(self, x):
        """
        İleri geçiş adımları.
        x : (batch_size, seq_len) -> Kelime indeks matrisi
        """
        # x: (batch_size, seq_len) → embedded: (batch_size, seq_len, embedding_dim)
        embedded = self.embedding(x)
        embedded = self.dropout(embedded)

        # output: (batch, seq_len, hidden) -> her adımın h_t'si
        # h_n   : (num_layers, batch, hidden) -> son zaman adımındaki gizli durumlar
        output, (h_n, c_n) = self.lstm(embedded)

        # h_n[-1]: en üstteki (son) LSTM katmanının son zaman adımındaki durumu.
        # Bu vektör tüm cümleyi özetleyen ana yapıdır. Şekil: (batch_size, hidden_size)
        last_hidden = h_n[-1]

        # Eğitim modunda nöronları rastgele söndürür
        last_hidden = self.dropout(last_hidden)

        # Ham sınıf skorları (Logits): (batch_size, num_classes)
        logits = self.fc(last_hidden)
        return logits

    def get_all_hidden(self, x):
        """Tüm adımların h_t'sini döndürür (ileride analiz yapmak istersen)."""
        with torch.no_grad():
            embedded = self.embedding(x)
            output, (h_n, c_n) = self.lstm(embedded)
        return output, h_n, c_n


# ==========================================
# PYTORCH MODEL YAPISINI VE PARAMETRELERİNİ İNCELEYELİM
# ==========================================

VOCAB_SIZE = 10000     # IMDB sözlüğündeki benzersiz kelime limiti
EMBEDDING_DIM = 100   # Her kelimenin vektör uzunluğu
HIDDEN_SIZE = 64      # LSTM hafıza hücresi boyutu
NUM_CLASSES = 2       # Pozitif mi? Negatif mi?

# PyTorch Model Nesnesini Oluşturuyoruz
model_pytorch = IMDBPyTorchLSTMClassifier(
    vocab_size=VOCAB_SIZE,
    embedding_dim=EMBEDDING_DIM,
    hidden_size=HIDDEN_SIZE,
    num_classes=NUM_CLASSES,
    num_layers=2,
    dropout=0.3
)

print("--- PYTORCH IMDB MODEL MİMARİSİ ---")
print(model_pytorch)
print()

# Katman bazında parametre analizi döngüsü
for name, param in model_pytorch.named_parameters():
    print(f"  {name:35s}  şekil={str(tuple(param.shape)):20s}  "
          f"{param.numel():>8,} parametre")

total_params = sum(p.numel() for p in model_pytorch.parameters())
print(f"\n  PYTORCH MODELİ TOPLAM: {total_params:,} PARAMETRE")

print("\n--- MATEMATİKSEL PARAMETRE FORMÜL KONTROLÜ ---")
print(f"  Embedding Katmanı       : {VOCAB_SIZE} × {EMBEDDING_DIM} = {VOCAB_SIZE * EMBEDDING_DIM:,}")
H, D = HIDDEN_SIZE, EMBEDDING_DIM
print(f"  LSTM 1. Katman (H, D)   : 4 × {H} × ({H} + {D}) + 4 × {H} = {4*H*(H+D)+4*H:,}")
H, D_2 = HIDDEN_SIZE, HIDDEN_SIZE
print(f"  LSTM 2. Katman (H, H)   : 4 × {H} × ({H} + {D_2}) + 4 × {H} = {4*H*(H+D_2)+4*H:,}")
print(f"  Linear Katman (FC)      : ({H} × {NUM_CLASSES}) + {NUM_CLASSES} = {(H * NUM_CLASSES) + NUM_CLASSES:,}")

"""## 2. IMDBPyTorchLSTMClassifier Modelini Uygulama ve Eğitme

Şimdi `er47jQpk4rmV` hücresinde tanımladığınız `IMDBPyTorchLSTMClassifier` modelini gerçek veri üzerinde eğiteceğiz.

### 2.1 Model Eğitim ve Değerlendirme Fonksiyonları

Modeli eğitmek ve her epoch sonunda performansını değerlendirmek için fonksiyonlar oluşturalım.
"""

def train(model, dataloader, criterion, optimizer, device):
    model.train() # Modeli eğitim moduna al
    total_loss = 0
    correct_predictions = 0
    total_samples = 0

    for batch_x, batch_y in tqdm(dataloader, desc="Eğitim"): # `tqdm` import edildi
        batch_x, batch_y = batch_x.to(device), batch_y.to(device)

        optimizer.zero_grad() # Gradyanları sıfırla
        outputs = model(batch_x) # Modelden tahmin al
        loss = criterion(outputs, batch_y) # Kaybı hesapla
        loss.backward() # Geri yayılım
        optimizer.step() # Parametreleri güncelle

        total_loss += loss.item()
        _, predicted = torch.max(outputs.data, 1) # Tahmin edilen sınıfı al
        total_samples += batch_y.size(0)
        correct_predictions += (predicted == batch_y).sum().item()

    avg_loss = total_loss / len(dataloader)
    accuracy = correct_predictions / total_samples
    return avg_loss, accuracy

def evaluate(model, dataloader, criterion, device):
    model.eval() # Modeli değerlendirme moduna al (dropout vb. kapatır)
    total_loss = 0
    correct_predictions = 0
    total_samples = 0

    with torch.no_grad(): # Gradyan hesaplamayı kapat
        for batch_x, batch_y in tqdm(dataloader, desc="Değerlendirme"): # `tqdm` import edildi
            batch_x, batch_y = batch_x.to(device), batch_y.to(device)

            outputs = model(batch_x)
            loss = criterion(outputs, batch_y)

            total_loss += loss.item()
            _, predicted = torch.max(outputs.data, 1)
            total_samples += batch_y.size(0)
            correct_predictions += (predicted == batch_y).sum().item()

    avg_loss = total_loss / len(dataloader)
    accuracy = correct_predictions / total_samples
    return avg_loss, accuracy

# Model hiperparametrelerini tanımlayalım (VOCAB_SIZE, EMBEDDING_DIM vb. er47jQpk4rmV içinde tanımlı)

# `IMDBPyTorchLSTMClassifier` zaten `er47jQpk4rmV` hücresinde tanımlanmış ve parametreleri belirlenmiştir.
# Bu nedenle, burada sadece model nesnesini yeniden oluşturmamız ve cihazı ayarlamamız yeterlidir.

# VOCAB_SIZE, EMBEDDING_DIM, HIDDEN_SIZE, NUM_CLASSES değerleri er47jQpk4rmV hücresinden alınacaktır.
# Eğer bu hücreden önce çalıştırılıyorsa, yukarıdaki 1.1 Tokenizasyon hücresindeki tanım kullanılacaktır.

model = IMDBPyTorchLSTMClassifier(
    vocab_size=VOCAB_SIZE, # 1.1 Tokenizasyon hücresinden gelen VOCAB_SIZE'ı kullanır
    embedding_dim=EMBEDDING_DIM,
    hidden_size=HIDDEN_SIZE,
    num_classes=NUM_CLASSES,
    num_layers=2,
    dropout=0.3
)

# Modelin cihazını belirle (GPU varsa GPU, yoksa CPU)
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model.to(device)

# Kayıp fonksiyonu ve optimize ediciyi tanımla
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

print(f"Model şu cihaza taşındı: {device}")
print(model)
print(f"Toplam eğitilebilir parametre sayısı: {sum(p.numel() for p in model.parameters() if p.requires_grad):,}")

"""### 2.2 Model Eğitim Döngüsü

Modeli belirlediğimiz epoch sayısı kadar eğitelim.
"""

NUM_EPOCHS = 5 # Kaç epoch eğiteceğimizi belirleyelim

history = {'train_loss': [], 'train_acc': [], 'val_loss': [], 'val_acc': []}

for epoch in range(NUM_EPOCHS):
    train_loss, train_acc = train(model, train_loader, criterion, optimizer, device)
    val_loss, val_acc = evaluate(model, val_loader, criterion, device)

    history['train_loss'].append(train_loss)
    history['train_acc'].append(train_acc)
    history['val_loss'].append(val_loss)
    history['val_acc'].append(val_acc)

    print(f"Epoch {epoch+1}/{NUM_EPOCHS} - "
          f"Eğitim Kaybı: {train_loss:.4f}, Eğitim Başarımı: {train_acc:.4f} - "
          f"Doğrulama Kaybı: {val_loss:.4f}, Doğrulama Başarımı: {val_acc:.4f}")

print("Eğitim tamamlandı!")

"""### 2.3 Eğitim Sonuçlarını Görselleştirme

Eğitim ve doğrulama kayıp/başarım grafiklerini çizerek modelin performansını inceleyelim.
"""

plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
plt.plot(history['train_loss'], label='Eğitim Kaybı')
plt.plot(history['val_loss'], label='Doğrulama Kaybı')
plt.title('Kayıp Eğrisi')
plt.xlabel('Epoch')
plt.ylabel('Kayıp')
plt.legend()
plt.grid(True)

plt.subplot(1, 2, 2)
plt.plot(history['train_acc'], label='Eğitim Başarımı')
plt.plot(history['val_acc'], label='Doğrulama Başarımı')
plt.title('Başarım Eğrisi')
plt.xlabel('Epoch')
plt.ylabel('Başarım')
plt.legend()
plt.grid(True)

plt.tight_layout()
plt.show()